In [ ]:
# Utility cell — Convert a copied Excel column from clipboard
# into a simple comma-separated text file
#

# Purpose:
# EIM Helper
# - Copy a single column from Excel
# - Read the raw clipboard text directly using tkinter
# - Split into lines
# - Remove blank lines
# - De-duplicate while preserving original order
# - Save as a one-line comma-separated .txt file
#
# Output:
# - field_param_list_comma_separated.txt
#
# Notes:
# - This stays inside the R80_ZonalRun notebook flow
# - Assumes the clipboard currently contains one Excel column
# - Uses only Python standard library + pathlib

from pathlib import Path
import tkinter as tk

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
OUT_FILE = WORK_DIR / "field_param_list_comma_separated.txt"

# ------------------------------------------------------------------
# Read raw clipboard text using tkinter
# ------------------------------------------------------------------
# Example workflow:
# 1. In Excel, copy one full column of values
# 2. Run this cell
# 3. The output file will contain one comma-separated line
root = tk.Tk()
root.withdraw()

try:
    raw = root.clipboard_get()
finally:
    root.destroy()

# ------------------------------------------------------------------
# Normalize values
# ------------------------------------------------------------------
# - Split on line breaks
# - Strip surrounding whitespace
# - Remove blanks
items = [line.strip() for line in raw.splitlines()]
items = [x for x in items if x != ""]

# ------------------------------------------------------------------
# De-duplicate while preserving original order
# ------------------------------------------------------------------
seen = set()
items_unique = []

for x in items:
    if x not in seen:
        seen.add(x)
        items_unique.append(x)

# ------------------------------------------------------------------
# Write one-line comma-separated text file
# ------------------------------------------------------------------
OUT_FILE.write_text(", ".join(items_unique), encoding="utf-8")

print(f"Saved: {OUT_FILE}")
print(f"Unique items written: {len(items_unique):,}")

In [29]:
print("kernel_alive")

kernel_alive

In [30]:
WORK_DIR

WindowsPath('C:/Users/kylian.robinson/MapRebuildItems/R80_ZonalRun')

In [2]:
from pathlib import Path; print('\n'.join(sorted(f.name for f in Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun").iterdir())))

.ipynb_checkpoints
2018HGM_wells.xlsx
Alkalinity_zonal.xlsx
AllWells_LabelData.csv
Copy of R-80 zonal data.xlsx
EDDtoIntellusNamesV2.xlsx
Effluent_ao_9_3_2026.csv
InfEff_ao_09_23_2026.csv
IntellusLocs.csv
IntellusLocs.txt
R-80 Unlabelled Samples.xlsx
Results
Results_v2
Untitled.ipynb
WedgeWells1a_ao_09_22_2026.csv
WedgeWells2a_ao_09_22_2026.csv
WedgeWells3a_ao_09_22_2026.csv
WedgeWells4a_ao_09_22_2026.csv
WellsOfInterest_v2.xls

In [5]:
# Cell _0 (process survey only) — Spreadsheet awareness for well-source remap
#
# Purpose:
# - Load the three upstream well spreadsheets/files
# - Normalize and inspect column headers
# - Print workbook/sheet awareness for Excel files
# - Show row counts and column names for each source
# - Optionally preview a few rows from each sheet
#
# Big-picture source priority:
# 1. AllWells_LabelList.csv      -> target wells / row labels to keep
# 2. 2018HGM_Wells.xlsx         -> preferred primary source for well parameter data
# 3. WellsOfInterest_v2.xls     -> backfill / patch P-data for wells not covered by 2018 HGM
#
# Notes:
# - This cell is for awareness only; it does not merge or alter pipeline outputs.
# - After running it, paste back the printed column names and we can map keys/fields.

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")

FILE_LABEL_LIST = WORK_DIR / "AllWells_LabelData.csv"
FILE_HGM_2018 = WORK_DIR / "2018HGM_Wells.xlsx"
FILE_WOI = WORK_DIR / "WellsOfInterest_v2.xls"

PREVIEW_ROWS = 5

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def normalize_cols(cols):
    return [str(c).strip() for c in cols]

def print_header(title):
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)

def describe_dataframe(df, label, preview_rows=5):
    df = df.copy()
    df.columns = normalize_cols(df.columns)

    print(f"\n[{label}]")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns):,}")
    print("Column names:")
    for i, col in enumerate(df.columns, start=1):
        print(f"  {i:>3}. {col}")

    if preview_rows and len(df) > 0:
        print(f"\nPreview ({min(preview_rows, len(df))} rows):")
        with pd.option_context("display.max_columns", None, "display.width", 200):
            print(df.head(preview_rows))

def inspect_csv(path, label):
    print_header(f"CSV FILE: {label}")
    if not path.exists():
        print(f"Missing file: {path}")
        return

    df = pd.read_csv(path, dtype=str, low_memory=False)
    describe_dataframe(df, label, preview_rows=PREVIEW_ROWS)

def inspect_excel(path, label):
    print_header(f"EXCEL FILE: {label}")
    if not path.exists():
        print(f"Missing file: {path}")
        return

    xls = pd.ExcelFile(path)
    print(f"Workbook: {path.name}")
    print("Sheets found:")
    for i, sheet in enumerate(xls.sheet_names, start=1):
        print(f"  {i:>3}. {sheet}")

    for sheet in xls.sheet_names:
        try:
            df = pd.read_excel(path, sheet_name=sheet, dtype=str)
            describe_dataframe(df, f"{label} | sheet={sheet}", preview_rows=PREVIEW_ROWS)
        except Exception as e:
            print(f"\n[{label} | sheet={sheet}]")
            print(f"Could not read sheet: {e}")

# ------------------------------------------------------------------
# Run awareness scan
# ------------------------------------------------------------------
print_header("UPSTREAM WELL SOURCE AWARENESS")

print("Files configured:")
print(f" - Label list:        {FILE_LABEL_LIST}")
print(f" - Preferred primary: {FILE_HGM_2018}")
print(f" - Patch/backfill:    {FILE_WOI}")

inspect_csv(FILE_LABEL_LIST, "AllWells_LabelList.csv")
inspect_excel(FILE_HGM_2018, "2018HGM_Wells.xlsx")
inspect_excel(FILE_WOI, "WellsOfInterest_v2.xls")

print("\nDone.")

================================================================================
UPSTREAM WELL SOURCE AWARENESS
================================================================================
Files configured:
 - Label list:        C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\AllWells_LabelData.csv
 - Preferred primary: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\2018HGM_Wells.xlsx
 - Patch/backfill:    C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\WellsOfInterest_v2.xls

================================================================================
CSV FILE: AllWells_LabelList.csv
================================================================================

[AllWells_LabelList.csv]
Rows: 78
Columns: 2
Column names:
    1. Location
    2. Cat

Preview (5 rows):
  Location         Cat
0   CRPZ-1   Pumicious
1  CRPZ-2A        Puye
2   CRPZ-3        Puye
3   CRPZ-5   Pumicious
4   CrEX-2  Extraction

================================================================================
EXCEL FILE: 2018HGM_Wells.xlsx
================================================================================
Workbook: 2018HGM_Wells.xlsx
Sheets found:
    1. wells

[2018HGM_Wells.xlsx | sheet=wells]
Rows: 432
Columns: 28
Column names:
    1. ID
    2. ULI
    3. LOCATION_NAME
    4. LOCATION_TYPE_CODE
    5. DATE_WELL_COMPLETED
    6. WELL_STATUS_CODE
    7. X_COORD
    8. Y_COORD
    9. SURFACE_ELEVATION
   10. DRILLED_TO_DEPTH
   11. COMPL_DEPTH
   12. SCREEN_ID
   13. SCREEN_COMMON_NAME
   14. SCRN_TYPE_CODE
   15. SCREEN_MAT_CODE
   16. OPEN_TOP_DEPTH
   17. OPEN_BOTTOM_DEPTH
   18. DEPTH_UOM
   19. Screen Length (ft)
   20. scrn_midpt
   21. SOURCE_ORG_CODE
   22. RELEASE_FLAG
   23. MODIFIED_DATE
   24. HYDRO_ZONE_TYPE_CODE
   25. GEOLOGIC_UNIT_CODE
   26. azimuth
   27. dip
   28. Source

Preview (5 rows):
  ID    ULI LOCATION_NAME LOCATION_TYPE_CODE  DATE_WELL_COMPLETED WELL_STATUS_CODE       X_COORD       Y_COORD SURFACE_ELEVATION DRILLED_TO_DEPTH COMPL_DEPTH SCREEN_ID  SCREEN_COMMON_NAME  \
0  1  23811       03-B-10                MON  2005-06-04 00:00:00               PA   1616682.082   1773307.214           7458.28               35        31.1      3131   03-B-10 Screen #1
1  2  23821       03-B-13                MON  2005-06-10 00:00:00                A   1616691.691  1773317.0704           7458.26               35          32      3151   03-B-13 Screen #1
2  3  23801        03-B-9                MON  2005-06-03 00:00:00               PA  1616671.8977  1773331.3818           7457.98               35        31.8      3121    03-B-9 Screen #1
3  4  15051       03-MW-1                MON  1994-09-22 00:00:00               PA     1616678.9     1773314.3            7457.7               29        28.8      2951   03-MW-1 Screen #1
4  5  29231      16-26644                MON  2007-08-17 00:00:00                A   1612087.156   1763729.938           7591.43              150         150      4281  16-26644 Screen #1

  SCRN_TYPE_CODE SCREEN_MAT_CODE OPEN_TOP_DEPTH OPEN_BOTTOM_DEPTH DEPTH_UOM Screen Length (ft) scrn_midpt SOURCE_ORG_CODE RELEASE_FLAG        MODIFIED_DATE HYDRO_ZONE_TYPE_CODE GEOLOGIC_UNIT_CODE  \
0          MSPVC             PVC           20.6              30.6         1                 10    7432.68             WQH            Y  2006-05-24 00:00:00                    I               Qbt3
1          MSPVC             PVC           21.5              31.5         1                 10    7431.76             WQH            Y  2009-01-23 00:00:00                    I               Qbt3
2          MSPVC             PVC           21.3              31.3         1                 10    7431.68             WQH            Y  2006-05-24 00:00:00                    I               Qbt3
3             WR           SS304             23                28         1                  5     7432.2             WQH            Y  2006-04-13 00:00:00                    I               Qbt3
4          MSPVC             PVC            130               145         1                 15    7453.93              ER            Y  2009-11-25 00:00:00                    I               Qbt3

  azimuth dip Source
0       0  90    NaN
1       0  90    NaN
2       0  90    NaN
3       0  90    NaN
4       0  90    NaN

================================================================================
EXCEL FILE: WellsOfInterest_v2.xls
================================================================================
Workbook: WellsOfInterest_v2.xls
Sheets found:
    1. WedgeWells_Cats

[WellsOfInterest_v2.xls | sheet=WedgeWells_Cats]
Rows: 108
Columns: 26
Column names:
    1. OBJECTID
    2. Site_ID
    3. Location_ID
    4. Location_Type
    5. Well_ID
    6. Ground_Elevation
    7. Well_Total_Depth
    8. Depth_Units
    9. Well_Diameter
   10. Well_Diameter_Units
   11. Well_Use
   12. Well_Status
   13. Well_Installation_Date
   14. Drilling_Method_Code
   15. Perforation_Zone_Start_Depth
   16. Perforation_Zone_End_Depth
   17. Geological_Unit_Code
   18. Aquifer
   19. Hydrostratigraphic_Unit
   20. Chamber_Effective_Top_Depth
   21. Chamber_Effective_Bottom_Depth
   22. Well_Completion_Report_Url
   23. Latitude
   24. Longitude
   25. Top_of_Casing_Elevation
   26. Cat

Preview (5 rows):
  OBJECTID Site_ID Location_ID Location_Type Well_ID Ground_Elevation Well_Total_Depth Depth_Units Well_Diameter Well_Diameter_Units Well_Use Well_Status Well_Installation_Date Drilling_Method_Code  \
0        1     N3B      CrEX-1           EXT  CrEX-1          6829.28             1211          ft             8                  in      NaN           A    2014-08-17 00:00:00                  NaN
1        2     N3B      CrEX-2           EXT  CrEX-2         6950.229              NaN         NaN           NaN                 NaN      NaN         NaN                    NaN                  NaN
2        3     N3B      CrEX-3           EXT  CrEX-3         6734.601           1004.5          ft             8                  in      NaN           A    2016-04-11 00:00:00                  NaN
3        4     N3B      CrEX-4           EXT  CrEX-4         6754.056              NaN         NaN           NaN                 NaN      NaN         NaN                    NaN                  NaN
4        5     N3B      CrIN-1           INJ  CrIN-1         6705.362             1040          ft             8                  in      NaN           A    2016-06-23 00:00:00                  NaN

  Perforation_Zone_Start_Depth Perforation_Zone_End_Depth Geological_Unit_Code   Aquifer Hydrostratigraphic_Unit Chamber_Effective_Top_Depth Chamber_Effective_Bottom_Depth  \
0                          NaN                        NaN                  NaN       NSD                     NaN                         NaN                            NaN
1                          NaN                        NaN                  NaN       NSD                     NaN                         NaN                            NaN
2                        909.6                      948.8                  Tpf  Regional            Regional Top                           0                          958.7
3                          NaN                        NaN                  NaN       NSD                     NaN                         NaN                            NaN
4                        883.9                      933.9                  NaN       NSD                     NaN                         NaN                            NaN

                          Well_Completion_Report_Url     Latitude     Longitude Top_of_Casing_Elevation         Cat
0  https://www.intellusnm.com/documents/document-...   35.8577827   -106.256363                     NaN  Extraction
1                                                NaN  35.85898059  -106.2607242                     NaN  Extraction
2  https://www.intellusnm.com/documents/document-...  35.85966751  -106.2549516                 6733.16  Extraction
3                                                NaN  35.85995329  -106.2579893                     NaN  Extraction
4                                                NaN  35.85996843  -106.2511032                6702.379   Injection

Done.

In [1]:
# Cell 1 — Build minimal WellMeta table from label data + 2018 HGM
#
# Purpose:
# - Start from AllWells_LabelData.csv as the authoritative target well list
# - Match each label-data location to 2018HGM_Wells.xlsx
# - Respect curated S1 / S2 designators in label data where present
# - Apply explicit legacy-name overrides where label-data names do not
#   directly match 2018 HGM structural well names
# - Apply family-level alias transforms for known naming systems
# - Carry over only essential metadata fields for numerical analysis
# - Preserve unmatched label-data rows in output for later patch/fill
#
# Matching rules:
# - LabelData.Location is the target geochemical location label
# - Base well name = Location with trailing S1/S2 stripped
# - Match base well name to 2018HGM_Wells.LOCATION_NAME
# - If label-data location has S1 or S2, search all HGM rows for that base well
#   and select the row matching the requested screen number
# - Do NOT require lower-numbered screens to exist
# - Apply explicit overrides first for known cross-dataset naming mismatches
# - Apply case-insensitive family-level transforms next
# - If no S-designator is present, use the first available HGM row for that base location
#
# Output columns (in this exact order):
# 1. Location
# 2. Cat
# 3. GEOLOGIC_UNIT_CODE
# 4. OPEN_BOTTOM_DEPTH
# 5. Screen Length (ft)
#
# Output:
# - WellMeta.xlsx
#
# Notes:
# - Unmatched label-data locations persist in the output with blank metadata fields.
# - This cell intentionally does not yet patch from WellsOfInterest_v2.xls.

from pathlib import Path
import pandas as pd
import re

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

FILE_LABEL = WORK_DIR / "AllWells_LabelData.csv"
FILE_HGM = WORK_DIR / "2018HGM_Wells.xlsx"

OUT_FILE = RESULTS_DIR / "WellMeta.xlsx"

# ------------------------------------------------------------------
# Explicit legacy-name overrides
# Keys are normalized to lowercase for case-insensitive matching.
# ------------------------------------------------------------------
LOCATION_BASE_OVERRIDES = {
    # CrPZ-2A corresponds to 2018 HGM structural well CrCH-2
    "crpz-2a": "CrCH-2",
}

LOCATION_SCREEN_OVERRIDES = {
    # CrPZ-2A corresponds to CrCH-2 Screen #1
    "crpz-2a": "1",
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_cols(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def clean_text(series):
    return series.fillna("").astype(str).str.strip()

def norm_key(value):
    return str(value).strip().lower()

def parse_location_parts(location_value):
    s = str(location_value).strip()
    m = re.match(r"^(.*?)(?:\s+S([12]))?$", s, flags=re.IGNORECASE)
    if not m:
        return s, ""
    base = (m.group(1) or "").strip()
    screen_num = (m.group(2) or "").strip()
    return base, screen_num

def parse_hgm_screen_num(screen_common_name):
    s = str(screen_common_name).strip()
    m = re.search(r"SCREEN\s*#\s*([0-9]+)", s, flags=re.IGNORECASE)
    return (m.group(1) if m else "").strip()

def family_base_override(parsed_base_location):
    """
    Family-level alias transforms for known naming mismatches.
    Explicit per-location overrides should already have been checked first.
    """
    s = str(parsed_base_location).strip()

    # Chromium Piezometer labels map to Chromium Corehole structural wells
    # Examples:
    #   CrPZ-1   -> CrCH-1
    #   CrPZ-3   -> CrCH-3
    #   CrPZ-2A  -> handled by explicit override before this function
    m = re.match(r"^crpz-(.+)$", s, flags=re.IGNORECASE)
    if m:
        suffix = m.group(1).strip()
        return f"CrCH-{suffix}"

    return parsed_base_location

# ------------------------------------------------------------------
# Read inputs
# ------------------------------------------------------------------
label = pd.read_csv(FILE_LABEL, dtype=str, low_memory=False)
hgm = pd.read_excel(FILE_HGM, sheet_name="wells", dtype=str)

label = clean_cols(label)
hgm = clean_cols(hgm)

required_label = ["Location", "Cat"]
required_hgm = ["LOCATION_NAME", "SCREEN_COMMON_NAME", "GEOLOGIC_UNIT_CODE", "OPEN_BOTTOM_DEPTH", "Screen Length (ft)"]

missing_label = [c for c in required_label if c not in label.columns]
missing_hgm = [c for c in required_hgm if c not in hgm.columns]

if missing_label:
    raise ValueError(f"Missing required label-data columns: {missing_label}")
if missing_hgm:
    raise ValueError(f"Missing required HGM columns: {missing_hgm}")

label["Location"] = clean_text(label["Location"])
label["Cat"] = clean_text(label["Cat"])

for col in required_hgm:
    hgm[col] = clean_text(hgm[col])

# ------------------------------------------------------------------
# Parse label-data base location + requested screen,
# then apply explicit overrides and family-level transforms
# ------------------------------------------------------------------
label_parts = label["Location"].apply(parse_location_parts)
label["parsed_base_location"] = label_parts.apply(lambda x: x[0])
label["parsed_screen_num"] = label_parts.apply(lambda x: x[1])
label["location_key_norm"] = label["Location"].apply(norm_key)

# Base location resolution priority:
# 1. explicit override
# 2. family-level transform
# 3. parsed base location
label["base_location"] = label["location_key_norm"].map(LOCATION_BASE_OVERRIDES)
label["base_location"] = label["base_location"].fillna(
    label["parsed_base_location"].apply(family_base_override)
)

# Requested screen resolution priority:
# 1. explicit override
# 2. parsed screen number
label["requested_screen_num"] = label["location_key_norm"].map(LOCATION_SCREEN_OVERRIDES)
label["requested_screen_num"] = label["requested_screen_num"].fillna(label["parsed_screen_num"])

# ------------------------------------------------------------------
# Parse HGM screen number
# ------------------------------------------------------------------
hgm["LOCATION_NAME"] = clean_text(hgm["LOCATION_NAME"])
hgm["location_name_norm"] = hgm["LOCATION_NAME"].apply(norm_key)
hgm["hgm_screen_num"] = hgm["SCREEN_COMMON_NAME"].apply(parse_hgm_screen_num)

# ------------------------------------------------------------------
# Build WellMeta row by row from label data
# ------------------------------------------------------------------
out_rows = []

for _, lab_row in label.iterrows():
    location = lab_row["Location"]
    cat = lab_row["Cat"]
    base_location = str(lab_row["base_location"]).strip()
    requested_screen_num = str(lab_row["requested_screen_num"]).strip()

    candidates = hgm.loc[hgm["location_name_norm"] == norm_key(base_location)].copy()
    selected = None

    if not candidates.empty:
        if requested_screen_num != "":
            screen_matches = candidates.loc[
                candidates["hgm_screen_num"].astype(str).str.strip() == requested_screen_num
            ].copy()

            if not screen_matches.empty:
                selected = screen_matches.iloc[0]
            else:
                screen_text_matches = candidates.loc[
                    candidates["SCREEN_COMMON_NAME"].astype(str).str.contains(
                        rf"screen\s*#?\s*{requested_screen_num}\b",
                        case=False,
                        regex=True,
                        na=False,
                    )
                ].copy()

                if not screen_text_matches.empty:
                    selected = screen_text_matches.iloc[0]
                elif len(candidates) == 1:
                    selected = candidates.iloc[0]
        else:
            selected = candidates.iloc[0]

    out_rows.append({
        "Location": location,
        "Cat": cat,
        "GEOLOGIC_UNIT_CODE": "" if selected is None else str(selected["GEOLOGIC_UNIT_CODE"]).strip(),
        "OPEN_BOTTOM_DEPTH": "" if selected is None else str(selected["OPEN_BOTTOM_DEPTH"]).strip(),
        "Screen Length (ft)": "" if selected is None else str(selected["Screen Length (ft)"]).strip(),
    })

wellmeta = pd.DataFrame(out_rows, columns=[
    "Location",
    "Cat",
    "GEOLOGIC_UNIT_CODE",
    "OPEN_BOTTOM_DEPTH",
    "Screen Length (ft)",
])

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
wellmeta.to_excel(OUT_FILE, index=False)

matched_mask = (
    wellmeta["GEOLOGIC_UNIT_CODE"].astype(str).str.strip().ne("") |
    wellmeta["OPEN_BOTTOM_DEPTH"].astype(str).str.strip().ne("") |
    wellmeta["Screen Length (ft)"].astype(str).str.strip().ne("")
)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Total label-data rows: {len(wellmeta):,}")
print(f"Matched rows with at least some HGM metadata: {int(matched_mask.sum()):,}")
print(f"Unmatched / still blank rows: {int((~matched_mask).sum()):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\WellMeta.xlsx
Total label-data rows: 79
Matched rows with at least some HGM metadata: 72
Unmatched / still blank rows: 7

In [10]:
# Cell _1 (survey process) — Inspect MostRecentWellData.csv
#
# Purpose:
# - Load MostRecentWellData.csv from the project folder
# - Print row count, column count, and column names
# - Show a small preview for quick inspection
#
# Notes:
# - Awareness only; does not modify any pipeline outputs.

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
FILE_MRWD = WORK_DIR / "MostRecentWellData.csv"

PREVIEW_ROWS = 10

# ------------------------------------------------------------------
# Read and inspect
# ------------------------------------------------------------------
if not FILE_MRWD.exists():
    raise FileNotFoundError(f"File not found: {FILE_MRWD}")

df = pd.read_csv(FILE_MRWD, dtype=str, low_memory=False)
df.columns = [str(c).strip() for c in df.columns]

print("=" * 80)
print("INSPECT: MostRecentWellData.csv")
print("=" * 80)
print(f"File: {FILE_MRWD}")
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns):,}")
print("\nColumn names:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i:>3}. {col}")

print(f"\nPreview ({min(PREVIEW_ROWS, len(df))} rows):")
with pd.option_context("display.max_columns", None, "display.width", 220):
    print(df.head(PREVIEW_ROWS))

print("\nDone.")

================================================================================
INSPECT: MostRecentWellData.csv
================================================================================
File: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\MostRecentWellData.csv
Rows: 7
Columns: 39

Column names:
  1. WELL_ID
  2. LOCATION_ID
  3. SITE_ID
  4. WELL_USE
  5. WELL_INSTALLATION_DATE
  6. WELL_TOTAL_DEPTH
  7. TOP_OF_CASING_ELEVATION
  8. DRILLING_COMPANY
  9. DRILLER
 10. DRILLING_METHOD_CODE
 11. FIELD_GEOLOGIST
 12. WELL_COMPLETION_METHOD
 13. WELL_STATUS
 14. WELL_OWNER
 15. PROJECT_NO
 16. PHASE
 17. TASK
 18. WELL_COMMENTS
 19. WELL_RECNO
 20. MULTIPORT_WELL
 21. BUBBLER_TUBE_LENGTH
 22. DEPTH_UNITS
 23. WELL_RISER_STICKUP
 24. WELL_DIAMETER
 25. WELL_DIAMETER_UNITS
 26. WELL_WEATHER
 27. LOGGING_COMPANY
 28. INSERTED_BY
 29. INSERT_DATE
 30. LAST_MODIFIED_BY
 31. LAST_MODIFIED_DATE
 32. PERFORATION_ZONE_START_DEPTH
 33. PERFORATION_ZONE_END_DEPTH
 34. PERFORATION_ZONE_SEQUENCE_NO
 35. AQUIFER
 36. WELL_PERFORATION_ZONE_COMMENTS
 37. HYDROSTRATIGRAPHIC_UNIT
 38. REPORT_HYDROSTRATIGRAPHIC_UNIT
 39. GEOLOGICAL_UNIT_CODE

Preview (7 rows):
  WELL_ID LOCATION_ID SITE_ID    WELL_USE WELL_INSTALLATION_DATE WELL_TOTAL_DEPTH TOP_OF_CASING_ELEVATION DRILLING_COMPANY                        DRILLER DRILLING_METHOD_CODE FIELD_GEOLOGIST WELL_COMPLETION_METHOD  \
0    R-71     R-71 S1     N3B         NaN             12/21/2021             1370                 6985.56              NaN                            NaN                  NaN             NaN                    NaN
1    R-71     R-71 S2     N3B         NaN             12/21/2021             1370                 6985.56              NaN                            NaN                  NaN             NaN                    NaN
2    R-72     R-72 S1     N3B         NaN             11/21/2021             1320                 7032.96   Boart Longyear  J. Lamb, R. Parkin, M. Foster                  NaN     J. Richeson                    NaN
3    R-72     R-72 S2     N3B         NaN             11/21/2021             1320                 7032.96   Boart Longyear  J. Lamb, R. Parkin, M. Foster                  NaN     J. Richeson                    NaN
4    R-76        R-76     N3B  Monitoring              12/2/2024              970                    6729   Boart Longyear                            NaN                  NaN             NaN                    NaN
5  SIMR-3   SIMR-3 S1     N3B  Monitoring                    NaN             1060                    6751              NaN                            NaN                  NaN             NaN                    NaN
6  SIMR-3   SIMR-3 S2     N3B  Monitoring                    NaN             1060                    6751              NaN                            NaN                  NaN             NaN                    NaN

  WELL_STATUS WELL_OWNER PROJECT_NO PHASE TASK                                      WELL_COMMENTS WELL_RECNO MULTIPORT_WELL BUBBLER_TUBE_LENGTH DEPTH_UNITS WELL_RISER_STICKUP WELL_DIAMETER WELL_DIAMETER_UNITS  \
0           A        NaN        NaN   NaN  NaN  Well casing drilled 25 degrees from vertical. ...       3812            Yes                 NaN          ft                NaN             8                  in
1           A        NaN        NaN   NaN  NaN  Well casing drilled 25 degrees from vertical. ...       3812            Yes                 NaN          ft                NaN             8                  in
2           A        NaN        NaN   NaN  NaN  Ground elevation at brass cap marker at 7030.2...       3808            Yes                 NaN          ft                NaN           7.9                  in
3           A        NaN        NaN   NaN  NaN  Ground elevation at brass cap marker at 7030.2...       3808            Yes                 NaN          ft                NaN           7.9                  in
4           A        NaN        NaN   NaN  NaN  EM2025-0008 Well Completion Report (total dept...       3849            NaN                 NaN          ft                NaN             5                  in
5           A        NaN        NaN   NaN  NaN                                                NaN       3855            Yes                 NaN          ft                NaN             5                  in
6           A        NaN        NaN   NaN  NaN                                                NaN       3855            Yes                 NaN          ft                NaN             5                  in

  WELL_WEATHER LOGGING_COMPANY INSERTED_BY      INSERT_DATE LAST_MODIFIED_BY LAST_MODIFIED_DATE PERFORATION_ZONE_START_DEPTH PERFORATION_ZONE_END_DEPTH PERFORATION_ZONE_SEQUENCE_NO   AQUIFER  \
0          NaN             NaN       markp   4/7/2022 16:07            markp      9/3/2024 8:51                         1285                       1305                            1  Regional
1          NaN             NaN       markp   4/7/2022 16:07            markp      9/3/2024 8:51                       1349.7                       1360                            2  Regional
2          NaN             NaN       markp  1/13/2022 10:03            markp    12/7/2023 13:26                         1220                       1240                            1  Regional
3          NaN             NaN       markp  1/13/2022 10:03            markp    12/7/2023 13:26                         1290                       1310                            2  Regional
4          NaN             NaN       markp  4/21/2025 13:30        donaldson    12/5/2025 10:16                          940                        960                            1  Regional
5          NaN             NaN   donaldson   1/23/2026 7:54        donaldson    1/23/2026 11:47                          943                        963                            1  Regional
6          NaN             NaN   donaldson   1/23/2026 7:54        donaldson    1/23/2026 11:47                         1027                       1047                            2  Regional

  WELL_PERFORATION_ZONE_COMMENTS HYDROSTRATIGRAPHIC_UNIT REPORT_HYDROSTRATIGRAPHIC_UNIT GEOLOGICAL_UNIT_CODE
0                            NaN            Regional Top                            NaN                 Tjfp
1                            NaN           Regional Deep                            NaN                 Tjfp
2                            NaN            Regional Top                            NaN                 Tjfp
3                            NaN           Regional Deep                            NaN                 Tjfp
4                            NaN            Regional Top                            NaN                 Tjfp
5                            NaN            Regional Top                            NaN                  NaN
6                            NaN           Regional Deep                            NaN                  NaN

Done.

In [2]:
# Cell 1_a — Fill remaining WellMeta orphans from MostRecentWellData.csv
#
# Purpose:
# - Load WellMeta_HGMonly.xlsx
# - Patch remaining blank fields using MostRecentWellData.csv
# - Keep existing HGM-derived values unchanged
# - Fill only to the same minimal standard:
#     GEOLOGIC_UNIT_CODE
#     OPEN_BOTTOM_DEPTH
#     Screen Length (ft)
#
# Join rule:
# - WellMeta_HGMonly.Location == MostRecentWellData.LOCATION_ID
#
# Field mapping:
# - GEOLOGIC_UNIT_CODE <- GEOLOGICAL_UNIT_CODE
# - OPEN_BOTTOM_DEPTH  <- PERFORATION_ZONE_END_DEPTH
# - Screen Length (ft) <- PERFORATION_ZONE_END_DEPTH - PERFORATION_ZONE_START_DEPTH
#
# Output:
# - Saves completed result to WellMeta_Complete.xlsx

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

FILE_WELLMETA = RESULTS_DIR / "WellMeta_HGMonly.xlsx"
FILE_RECENT = WORK_DIR / "MostRecentWellData.csv"
OUT_FILE = WORK_DIR / "WellMeta_Complete.xlsx"

# ------------------------------------------------------------------
# Read files
# ------------------------------------------------------------------
wellmeta = pd.read_excel(FILE_WELLMETA, dtype=str)
recent = pd.read_csv(FILE_RECENT, dtype=str, low_memory=False)

wellmeta.columns = [str(c).strip() for c in wellmeta.columns]
recent.columns = [str(c).strip() for c in recent.columns]

wellmeta = wellmeta.fillna("")
recent = recent.fillna("")

required_wellmeta = ["Location", "Cat", "GEOLOGIC_UNIT_CODE", "OPEN_BOTTOM_DEPTH", "Screen Length (ft)"]
required_recent = ["LOCATION_ID", "GEOLOGICAL_UNIT_CODE", "PERFORATION_ZONE_START_DEPTH", "PERFORATION_ZONE_END_DEPTH"]

missing_wellmeta = [c for c in required_wellmeta if c not in wellmeta.columns]
missing_recent = [c for c in required_recent if c not in recent.columns]

if missing_wellmeta:
    raise ValueError(f"Missing required WellMeta columns: {missing_wellmeta}")
if missing_recent:
    raise ValueError(f"Missing required MostRecentWellData columns: {missing_recent}")

# ------------------------------------------------------------------
# Normalize key fields
# ------------------------------------------------------------------
wellmeta["Location"] = wellmeta["Location"].astype(str).str.strip()
recent["LOCATION_ID"] = recent["LOCATION_ID"].astype(str).str.strip()

# ------------------------------------------------------------------
# Compute patch fields from MostRecentWellData
# ------------------------------------------------------------------
recent["PERFORATION_ZONE_START_DEPTH_num"] = pd.to_numeric(
    recent["PERFORATION_ZONE_START_DEPTH"], errors="coerce"
)
recent["PERFORATION_ZONE_END_DEPTH_num"] = pd.to_numeric(
    recent["PERFORATION_ZONE_END_DEPTH"], errors="coerce"
)

recent["Screen Length (ft)_fill"] = (
    recent["PERFORATION_ZONE_END_DEPTH_num"] - recent["PERFORATION_ZONE_START_DEPTH_num"]
)

recent_patch = recent[[
    "LOCATION_ID",
    "GEOLOGICAL_UNIT_CODE",
    "PERFORATION_ZONE_END_DEPTH_num",
    "Screen Length (ft)_fill",
]].copy()

recent_patch = recent_patch.rename(columns={
    "LOCATION_ID": "Location",
    "GEOLOGICAL_UNIT_CODE": "GEOLOGIC_UNIT_CODE_fill",
    "PERFORATION_ZONE_END_DEPTH_num": "OPEN_BOTTOM_DEPTH_fill",
})

def fmt_num(x):
    if pd.isna(x):
        return ""
    if float(x).is_integer():
        return str(int(x))
    return str(float(x))

recent_patch["GEOLOGIC_UNIT_CODE_fill"] = recent_patch["GEOLOGIC_UNIT_CODE_fill"].astype(str).str.strip()
recent_patch["OPEN_BOTTOM_DEPTH_fill"] = recent_patch["OPEN_BOTTOM_DEPTH_fill"].apply(fmt_num)
recent_patch["Screen Length (ft)_fill"] = recent_patch["Screen Length (ft)_fill"].apply(fmt_num)

# If LOCATION_ID is duplicated, keep the first occurrence
recent_patch = recent_patch.drop_duplicates(subset=["Location"], keep="first")

# ------------------------------------------------------------------
# Merge patch data onto WellMeta_HGMonly
# ------------------------------------------------------------------
patched = wellmeta.merge(recent_patch, on="Location", how="left")

for c in ["GEOLOGIC_UNIT_CODE_fill", "OPEN_BOTTOM_DEPTH_fill", "Screen Length (ft)_fill"]:
    patched[c] = patched[c].fillna("").astype(str).str.strip()

# Fill each field only where it is currently blank
for target_col, fill_col in [
    ("GEOLOGIC_UNIT_CODE", "GEOLOGIC_UNIT_CODE_fill"),
    ("OPEN_BOTTOM_DEPTH", "OPEN_BOTTOM_DEPTH_fill"),
    ("Screen Length (ft)", "Screen Length (ft)_fill"),
]:
    blank_target = patched[target_col].astype(str).str.strip().eq("")
    has_fill = patched[fill_col].astype(str).str.strip().ne("")
    patched.loc[blank_target & has_fill, target_col] = patched.loc[blank_target & has_fill, fill_col]

# Keep only final output columns in required order
patched = patched[["Location", "Cat", "GEOLOGIC_UNIT_CODE", "OPEN_BOTTOM_DEPTH", "Screen Length (ft)"]].copy()

# ------------------------------------------------------------------
# Save completed result
# ------------------------------------------------------------------
patched.to_excel(OUT_FILE, index=False)

remaining_blank_mask = (
    patched["GEOLOGIC_UNIT_CODE"].astype(str).str.strip().eq("") &
    patched["OPEN_BOTTOM_DEPTH"].astype(str).str.strip().eq("") &
    patched["Screen Length (ft)"].astype(str).str.strip().eq("")
)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Rows in WellMeta_Complete: {len(patched):,}")
print(f"Remaining fully blank rows: {int(remaining_blank_mask.sum()):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\WellMeta_Complete.xlsx
Rows in WellMeta_Complete: 79
Remaining fully blank rows: 0

In [3]:
# Cell 2 — Process zonal data into review tables for zonal screening and downstream PCA work
#
# Outputs:
# 1. zonal_detects_matrix.xlsx
#    Sample-by-analyte categorical screening matrix.
#    Zones are ordered 7, 6, 5, 4, 3, 2, 1 from top to bottom.
#
# 2. zonal_rotated_numeric_matrix.xlsx
#    Sample-by-analyte numeric matrix for downstream multivariate work.
#
# 3. zonal_value_qualifier_pql_matrix.xlsx
#    Review matrix with MultiIndex columns:
#        analyte -> {value, qualifier, pql}
#    The qualifier field in this table is the resolved output qualifier:
#    either the original lab qualifier or our elaborated code such as D or D_sub.
#
# Key logic notes:
# - ALK is preferred when directly reported.
# - If ALK is absent, ALK-HCO3 is remapped into ALK for output purposes.
# - Alternate alkalinity forms are removed from final output tables after remap.
# - LAB_DETECTION_LIMIT is treated as the PQL.
# - A row earns D (or D_sub for substituted ALK) only when LAB_RESULT > PQL.
# - Otherwise, the detect/category code comes from LAB_QUALIFIER.

from pathlib import Path
import re
import numpy as np
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
INPUT_FILE = WORK_DIR / "copy of R-80 zonal data.xlsx"
INPUT_SHEET = 0

RESULTS_DIR = WORK_DIR / "Results_v2"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

OUT_DETECTS = RESULTS_DIR / "zonal_detects_matrix.xlsx"
OUT_ROTATED = RESULTS_DIR / "zonal_rotated_numeric_matrix.xlsx"
OUT_VALUE_QUAL = RESULTS_DIR / "zonal_value_qualifier_pql_matrix.xlsx"

# Use ALK-HCO3 as fallback ALK where ALK is missing.
ALK_REMAP_SOURCE = "ALK-HCO3"

# Remove alternate alkalinity forms from final outputs after remapping.
DROP_ANALYTES = {
    "ALK-CO3",
    "ALK-CO3+HCO3",
    "ALK-HCO3",
    "ALK-OH",
    "ALK-PHEN",
    "CO3(-2)",
    "HCO3(-1)",
}

# ------------------------------------------------------------------
# Read and validate input
# ------------------------------------------------------------------
raw = pd.read_excel(INPUT_FILE, sheet_name=INPUT_SHEET, dtype=str)
raw.columns = [str(c).strip() for c in raw.columns]

required_cols = [
    "FIELD_SAMPLE_ID",
    "PARAMETER_CODE",
    "PARAMETER_NAME",
    "LAB_RESULT",
    "LAB_QUALIFIER",
    "ANALYSIS_DATE",
    "LAB_DETECTION_LIMIT",
]
missing = [c for c in required_cols if c not in raw.columns]
if missing:
    raise ValueError(f"Missing required columns in zonal file: {missing}")

df = raw.copy()

sample = df["FIELD_SAMPLE_ID"].fillna("").astype(str).str.strip()
analyte = df["PARAMETER_CODE"].fillna("").astype(str).str.strip().str.upper()
analyte_name = df["PARAMETER_NAME"].fillna("").astype(str).str.strip()
qual = df["LAB_QUALIFIER"].fillna("").astype(str).str.strip().str.upper()
res_txt = df["LAB_RESULT"].fillna("").astype(str).str.strip()
pql_txt = df["LAB_DETECTION_LIMIT"].fillna("").astype(str).str.strip()

# ------------------------------------------------------------------
# Parse numeric fields
# Numeric parsing extracts the first numeric token after stripping
# leading comparator symbols and commas.
# ------------------------------------------------------------------
res_core = (
    res_txt
    .str.replace(r"^[<>]\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)
pql_core = (
    pql_txt
    .str.replace(r"^[<>]\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

res_num = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+)")[0],
    errors="coerce"
)
pql_num = pd.to_numeric(
    pql_core.str.extract(r"([-+]?\d*\.?\d+)")[0],
    errors="coerce"
)

# ------------------------------------------------------------------
# Build base detect/category state
#
# Rule:
# - D is assigned only when result_num > pql_num.
# - Otherwise use LAB_QUALIFIER if present.
# - If qualifier is blank and result is not above PQL, fall back to:
#     N  for explicit nondetect-style reporting
#     NF for anything else not clearly classifiable
# ------------------------------------------------------------------
nd_text = res_txt.str.contains(
    r"\bND\b|NON[- ]?DETECT|NOT DETECT|BDL",
    case=False,
    regex=True,
    na=False,
)
above_pql = res_num.notna() & pql_num.notna() & (res_num > pql_num)

state = np.where(
    above_pql,
    "D",
    np.where(
        qual != "",
        qual,
        np.where(nd_text, "N", "NF")
    )
)

# ------------------------------------------------------------------
# Build working long table
# ------------------------------------------------------------------
zonal_long = pd.DataFrame({
    "sample": sample,
    "analyte": analyte,
    "analyte_name": analyte_name,
    "result_text": res_txt,
    "result_num": res_num,
    "qualifier": qual,
    "pql": pql_num,
    "state": state,
    "analysis_date": pd.to_datetime(df["ANALYSIS_DATE"], errors="coerce"),
})

zonal_long = zonal_long[
    (zonal_long["sample"] != "") &
    (zonal_long["analyte"] != "")
].copy()

# ------------------------------------------------------------------
# Derive zone number and order samples from Zone 7 to Zone 1
# Expected naming pattern: Zone 1, Zone 2, ... Zone 7
# ------------------------------------------------------------------
def extract_zone_number(text):
    if pd.isna(text):
        return np.nan
    m = re.search(r"\bZONE\s*([0-9]+)\b", str(text).upper())
    return int(m.group(1)) if m else np.nan

zonal_long["zone"] = zonal_long["sample"].apply(extract_zone_number)

sample_zone = zonal_long[["sample", "zone"]].drop_duplicates().copy()
sample_order = (
    sample_zone
    .sort_values(["zone", "sample"], ascending=[False, True], na_position="last")
    ["sample"]
    .tolist()
)

# ------------------------------------------------------------------
# Keep the best row per sample/analyte.
# Preference order:
# 1. higher information rank
# 2. higher numeric value
# 3. more recent analysis date
# ------------------------------------------------------------------
info_rank_map = {
    "D": 6,
    "D_SUB": 5,
    "J": 4,
    "UJ": 3,
    "N": 2,
    "NF": 1,
}
zonal_long["info_rank"] = zonal_long["state"].map(info_rank_map).fillna(2).astype(int)

best_rows = (
    zonal_long
    .sort_values(
        ["sample", "analyte", "info_rank", "result_num", "analysis_date"],
        ascending=[True, True, False, False, False],
        na_position="last"
    )
    .drop_duplicates(["sample", "analyte"], keep="first")
    .copy()
)

# ------------------------------------------------------------------
# Remap ALK-HCO3 into ALK when ALK is absent.
# The substituted rows retain the same value, qualifier, and pql.
# Their detect/category code becomes D_sub only if result > pql.
# Otherwise the detect/category code remains the LAB_QUALIFIER-derived code.
# ------------------------------------------------------------------
best_rows["alk_substituted"] = False

alk_rows = best_rows[best_rows["analyte"] == "ALK"].copy()
alt_alk_rows = best_rows[best_rows["analyte"] == ALK_REMAP_SOURCE].copy()

samples_with_alk = set(alk_rows["sample"])
alt_alk_sub = alt_alk_rows[~alt_alk_rows["sample"].isin(samples_with_alk)].copy()

if not alt_alk_sub.empty:
    alt_alk_sub["analyte"] = "ALK"
    alt_alk_sub["alk_substituted"] = True
    alt_alk_sub["state"] = np.where(
        alt_alk_sub["result_num"].notna() &
        alt_alk_sub["pql"].notna() &
        (alt_alk_sub["result_num"] > alt_alk_sub["pql"]),
        "D_sub",
        np.where(
            alt_alk_sub["qualifier"] != "",
            alt_alk_sub["qualifier"],
            np.where(
                alt_alk_sub["result_text"].str.contains(
                    r"\bND\b|NON[- ]?DETECT|NOT DETECT|BDL",
                    case=False,
                    regex=True,
                    na=False,
                ),
                "N",
                "NF"
            )
        )
    )

final_rows = pd.concat([best_rows, alt_alk_sub], ignore_index=True)

# Remove alternate alkalinity analytes from final outputs after remap.
final_rows = final_rows[
    ~final_rows["analyte"].isin(DROP_ANALYTES)
].copy()

# If both direct ALK and substituted ALK exist, keep direct ALK.
final_rows["alk_priority"] = np.where(final_rows["alk_substituted"], 0, 1)

final_rows = (
    final_rows
    .sort_values(
        ["sample", "analyte", "alk_priority", "info_rank", "result_num", "analysis_date"],
        ascending=[True, True, False, False, False, False],
        na_position="last"
    )
    .drop_duplicates(["sample", "analyte"], keep="first")
    .copy()
)

# Refresh information rank after ALK substitution state updates.
final_rows["info_rank"] = final_rows["state"].map(info_rank_map).fillna(2).astype(int)

# ------------------------------------------------------------------
# Table 1 — Detects matrix
# This is the categorical screening matrix used for quick review.
# ------------------------------------------------------------------
detect_priority = {
    "D_sub": 7,
    "D": 6,
    "J": 5,
    "UJ": 4,
    "N": 3,
    "NF": 2,
}

detects_long = final_rows[["sample", "analyte", "state"]].copy()
detects_long["prio"] = detects_long["state"].map(detect_priority).fillna(1).astype(int)

detects_long = (
    detects_long
    .sort_values(["sample", "analyte", "prio"], ascending=[True, True, False])
    .drop_duplicates(["sample", "analyte"], keep="first")
)

detects_matrix = (
    detects_long
    .pivot(index="sample", columns="analyte", values="state")
    .fillna("NF")
)
detects_matrix = detects_matrix.reindex(sample_order).sort_index(axis=1)

# ------------------------------------------------------------------
# Table 2 — Rotated numeric matrix
# Only direct-above-PQL detections and substituted-above-PQL detections
# carry numeric values into this matrix.
# ------------------------------------------------------------------
rot_long = final_rows[["sample", "analyte", "state", "result_num"]].copy()
rot_long["value_num"] = np.where(
    rot_long["state"].isin(["D", "D_sub"]),
    rot_long["result_num"],
    np.nan
)

rotated_matrix = rot_long.pivot(index="sample", columns="analyte", values="value_num")
rotated_matrix = rotated_matrix.reindex(sample_order).sort_index(axis=1)

# ------------------------------------------------------------------
# Table 3 — Value / qualifier / pql matrix
# MultiIndex column structure:
#   analyte -> {value, qualifier, pql}
# The qualifier field here is the resolved output qualifier/category:
# it may be the original lab qualifier or our elaborated code (e.g., D, D_sub).
# ------------------------------------------------------------------
vq_long = final_rows[["sample", "analyte", "result_num", "state", "pql"]].copy()
vq_long = vq_long.rename(columns={
    "result_num": "value",
    "state": "qualifier",
})

value_part = vq_long.pivot(index="sample", columns="analyte", values="value")
qual_part = vq_long.pivot(index="sample", columns="analyte", values="qualifier")
pql_part = vq_long.pivot(index="sample", columns="analyte", values="pql")

value_part.columns = pd.MultiIndex.from_product([value_part.columns, ["value"]])
qual_part.columns = pd.MultiIndex.from_product([qual_part.columns, ["qualifier"]])
pql_part.columns = pd.MultiIndex.from_product([pql_part.columns, ["pql"]])

value_qualifier_matrix = pd.concat([value_part, qual_part, pql_part], axis=1)

ordered_analytes = sorted(set(value_qualifier_matrix.columns.get_level_values(0)))
ordered_cols = []
for a in ordered_analytes:
    for sub in ["value", "qualifier", "pql"]:
        if (a, sub) in value_qualifier_matrix.columns:
            ordered_cols.append((a, sub))

value_qualifier_matrix = value_qualifier_matrix.reindex(
    columns=pd.MultiIndex.from_tuples(ordered_cols)
)
value_qualifier_matrix = value_qualifier_matrix.reindex(sample_order)

# ------------------------------------------------------------------
# Save outputs
# ------------------------------------------------------------------
detects_matrix.to_excel(OUT_DETECTS)
rotated_matrix.to_excel(OUT_ROTATED)
value_qualifier_matrix.to_excel(OUT_VALUE_QUAL)

print("\nCell 2 complete. Files written:")
for f in [OUT_DETECTS, OUT_ROTATED, OUT_VALUE_QUAL]:
    print(f" - {f}")

Cell 2 complete. Files written:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\zonal_detects_matrix.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\zonal_rotated_numeric_matrix.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\zonal_value_qualifier_pql_matrix.xlsx

In [5]:
## Cell _0c (Survey Process)
## 
## Maps columns from files of interest for Agent ingestion

import pandas as pd
from pathlib import Path

work_dir = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")

# 1) EIM file
eim_file = work_dir / "WedgeWells1a_ao_09_22_2026.csv"
eim = pd.read_csv(eim_file, nrows=5)
print("EIM columns:", eim.columns.tolist())

# 2) Wells of interest
woi = pd.read_excel(work_dir / "WellsOfInterest_v2.xls", nrows=5)
print("WOI columns:", woi.columns.tolist())

# 3) EDD mapping
map_file = work_dir / "EDDtoIntellusNamesV2.xlsx"
mapping = pd.read_excel(map_file, nrows=5)
print("Mapping columns:", mapping.columns.tolist())

# 4) Zonal matrix columns
zonal = pd.read_excel(work_dir / "Results" / "zonal_value_qualifier_pql_matrix.xlsx", header=[0,1], nrows=2)
print("Zonal top-level analytes:", zonal.columns.get_level_values(0).unique().tolist()[:20])

EIM columns: ['Site ID', 'Screening Flag', 'Parameter Group', 'Field Sample ID', 'Location ID', 'Sample Date', 'Parameter Name', 'Report Result', 'Report Units', 'Lab Qualifier', 'Validation Qualifier', 'Validation Reason Codes', 'Detected', 'Sample Matrix', 'Sample Purpose', 'Sample Type', 'Sample Time', 'Sample Usage Code', 'Latitude (Decimal)', 'Longitude (Decimal)', 'Filtered', 'Field Sample Comments', 'Lab Matrix', 'COC #', 'Lab Method', 'Report Detection Limit', 'Best Value', 'Usable', 'Field Preparation Code', 'Method Detection Limit']
WOI columns: ['OBJECTID', 'Site_ID', 'Location_ID', 'Location_Type', 'Well_ID', 'Ground_Elevation', 'Well_Total_Depth', 'Depth_Units', 'Well_Diameter', 'Well_Diameter_Units', 'Well_Use', 'Well_Status', 'Well_Installation_Date', 'Drilling_Method_Code', 'Perforation_Zone_Start_Depth', 'Perforation_Zone_End_Depth', 'Geological_Unit_Code', 'Aquifer', 'Hydrostratigraphic_Unit', 'Chamber_Effective_Top_Depth', 'Chamber_Effective_Bottom_Depth', 'Well_Completion_Report_Url', 'Latitude', 'Longitude', 'Top_of_Casing_Elevation', 'Cat']
Mapping columns: ['EDD', 'Intellus']
Zonal top-level analytes: ['Unnamed: 0_level_0', 'AG', 'AL', 'ALK', 'AS', 'B', 'BA', 'BE', 'BR(-1)', 'CA', 'CD', 'CL(-1)', 'CO', 'CR', 'CU', 'F(-1)', 'FE', 'HG', 'K', 'LI']

In [4]:
# Cell 4a — WellMeta to EIM matching audit
#
# Purpose:
# - Combine EIM exports into one raw file using the current long-term schema
# - Check which WellMeta_Complete locations are present in EIM
# - For each matched location, retain the closest sample date to TARGET_DATE
# - Retain unmatched WellMeta_Complete locations with blank Matched_Date
#
# Output:
# - combined EIM CSV using the current long-term export schema
# - Excel audit file with columns:
#     Location
#     Matched_Date
#
# Matching logic:
# - WellMeta_Complete.Location is the authoritative well list
# - Match to EIM Location by exact normalized string match
# - Matching is case-insensitive and trim-insensitive

from pathlib import Path
import pandas as pd

WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")

EIM_FILES = [
    WORK_DIR / "WedgeWells1a_ao_09_22_2026.csv",
    WORK_DIR / "WedgeWells2a_ao_09_22_2026.csv",
    WORK_DIR / "WedgeWells3a_ao_09_22_2026.csv",
    WORK_DIR / "WedgeWells4a_ao_09_22_2026.csv",
]

WELLMETA_FILE = WORK_DIR /  "WellMeta_Complete.xlsx"
RESULTS_DIR = WORK_DIR / "Results_v2"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

OUT_COMBINED_EIM_RAW = RESULTS_DIR / "combined_eim_full_timeline_raw.csv"
OUT_MATCH_AUDIT = RESULTS_DIR / "synoptic_wellmeta_match_audit.xlsx"

TARGET_DATE = pd.Timestamp("2026-06-15")

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def norm_text(x):
    return str(x).strip().lower()

# ------------------------------------------------------------------
# Read and combine EIM files
# ------------------------------------------------------------------
eim_parts = [pd.read_csv(f, dtype=str, low_memory=False) for f in EIM_FILES]
eim_raw = pd.concat(eim_parts, ignore_index=True)
wellmeta = pd.read_excel(WELLMETA_FILE, dtype=str)

eim_raw.columns = [str(c).strip() for c in eim_raw.columns]
wellmeta.columns = [str(c).strip() for c in wellmeta.columns]

# Save the combined raw EIM export exactly in the current long-term schema
eim_raw.to_csv(OUT_COMBINED_EIM_RAW, index=False)

# ------------------------------------------------------------------
# Build working EIM copy for notebook logic
# ------------------------------------------------------------------
eim = eim_raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
})

required_eim = ["Location", "Date Sampled"]
required_wellmeta = ["Location"]

missing_eim = [c for c in required_eim if c not in eim.columns]
missing_wellmeta = [c for c in required_wellmeta if c not in wellmeta.columns]

if missing_eim:
    raise ValueError(f"Missing required EIM columns after working rename: {missing_eim}")
if missing_wellmeta:
    raise ValueError(f"Missing required WellMeta columns: {missing_wellmeta}")

eim["Location"] = eim["Location"].fillna("").astype(str).str.strip()
eim["Date Sampled"] = eim["Date Sampled"].fillna("").astype(str).str.strip()
wellmeta["Location"] = wellmeta["Location"].fillna("").astype(str).str.strip()

eim["Location_norm"] = eim["Location"].apply(norm_text)
wellmeta["Location_norm"] = wellmeta["Location"].apply(norm_text)

eim["Date Sampled_dt"] = pd.to_datetime(eim["Date Sampled"], errors="coerce")

# ------------------------------------------------------------------
# Closest date per EIM location
# ------------------------------------------------------------------
sample_dates = (
    eim.loc[
        (eim["Location_norm"] != "") & eim["Date Sampled_dt"].notna(),
        ["Location", "Location_norm", "Date Sampled_dt"]
    ]
    .drop_duplicates()
    .copy()
)

sample_dates["date_delta_days"] = (sample_dates["Date Sampled_dt"] - TARGET_DATE).abs().dt.days

closest_dates = (
    sample_dates
    .sort_values(
        ["Location_norm", "date_delta_days", "Date Sampled_dt"],
        ascending=[True, True, True]
    )
    .drop_duplicates("Location_norm", keep="first")
    .copy()
)

date_map = dict(zip(closest_dates["Location_norm"], closest_dates["Date Sampled_dt"]))

# ------------------------------------------------------------------
# Build simple match audit from WellMeta_Complete
# ------------------------------------------------------------------
match_audit = wellmeta[["Location", "Location_norm"]].drop_duplicates().copy()
match_audit["Matched_Date"] = match_audit["Location_norm"].map(date_map)

match_audit["Matched_Date"] = match_audit["Matched_Date"].apply(
    lambda x: x.strftime("%Y-%m-%d") if pd.notna(x) else ""
)

match_audit = (
    match_audit[["Location", "Matched_Date"]]
    .sort_values(["Location", "Matched_Date"], na_position="last")
    .reset_index(drop=True)
)

match_audit.to_excel(OUT_MATCH_AUDIT, index=False)

matched_count = (match_audit["Matched_Date"].astype(str).str.strip() != "").sum()
unmatched_count = len(match_audit) - matched_count

print(f"Combined EIM rows: {len(eim_raw):,}")
print(f"Saved: {OUT_COMBINED_EIM_RAW}")
print(f"Saved: {OUT_MATCH_AUDIT}")
print(f"Total WellMeta locations: {len(match_audit):,}")
print(f"Matched locations: {matched_count:,}")
print(f"Unmatched locations: {unmatched_count:,}")

Combined EIM rows: 1,955,821
Saved: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\combined_eim_full_timeline_raw.csv
Saved: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_wellmeta_match_audit.xlsx
Total WellMeta locations: 79
Matched locations: 75
Unmatched locations: 4

In [5]:
# Cell 4b — Build synoptic tables from checked 4a match audit
#
# Updated revision:
# - Uses WellMeta_Complete as canonical well metadata source
# - Uses simplified 4a match audit schema: Location, Matched_Date
# - Prepends all WellMeta_Complete columns to the rotated numeric matrix
# - Drops WOI dependency entirely
# - Excludes temperature analyte
# - Keeps value/qualifier matrix lean: only Location and Sample_Date metadata
# - Report Detection Limit replaces old Lab Detection Limit
# - Added qualifier/provenance fields
# - Sample Usage Code included
# - Filtered = N becomes analyte suffix _NF
# - Exclude Sample Purpose FB / PEB / EQB
# - Exclude Sample Usage Code WST
# - Keep FD
# - Wide value/qualifier matrix trimmed through filtered

from pathlib import Path
import numpy as np
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")

EIM_FILE = WORK_DIR / "Results_v2" / "combined_eim_full_timeline_raw.csv"
MATCH_AUDIT_FILE = WORK_DIR / "Results_v2" / "synoptic_wellmeta_match_audit.xlsx"
WELLMETA_FILE = WORK_DIR / "WellMeta_Complete.xlsx"

RESULTS_DIR = WORK_DIR / "Results_v2"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

OUT_RETAINED_LONG = RESULTS_DIR / "synoptic_retained_long.xlsx"
OUT_ROTATED = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix.xlsx"
OUT_VALUE_QUAL = RESULTS_DIR / "synoptic_all_value_qualifier_matrix.xlsx"

COMPOSITE_WINDOW_DAYS = 28

# ------------------------------------------------------------------
# Read inputs
# ------------------------------------------------------------------
eim_raw = pd.read_csv(EIM_FILE, dtype=str, low_memory=False)
match_audit = pd.read_excel(MATCH_AUDIT_FILE, dtype=str)
wellmeta = pd.read_excel(WELLMETA_FILE, dtype=str)

eim_raw.columns = [str(c).strip() for c in eim_raw.columns]
match_audit.columns = [str(c).strip() for c in match_audit.columns]
wellmeta.columns = [str(c).strip() for c in wellmeta.columns]

# ------------------------------------------------------------------
# Harmonize EIM schema to internal working names
# ------------------------------------------------------------------
eim = eim_raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
    "Report Units": "Units",
    "Detected": "Detect?",
})

required_eim = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Sample Purpose",
    "Sample Usage Code",
    "Filtered",
    "Best Value",
    "Usable",
    "Method Detection Limit",
    "Report Detection Limit",
]

required_audit = [
    "Location",
    "Matched_Date",
]

required_wellmeta = [
    "Location",
]

missing_eim = [c for c in required_eim if c not in eim.columns]
missing_audit = [c for c in required_audit if c not in match_audit.columns]
missing_wellmeta = [c for c in required_wellmeta if c not in wellmeta.columns]

if missing_eim:
    raise ValueError(f"Missing required columns in EIM file after rename: {missing_eim}")
if missing_audit:
    raise ValueError(f"Missing required columns in match audit file: {missing_audit}")
if missing_wellmeta:
    raise ValueError(f"Missing required columns in WellMeta file: {missing_wellmeta}")

# ------------------------------------------------------------------
# Normalize fields
# ------------------------------------------------------------------
df = eim.copy()

normalize_cols = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Sample Purpose",
    "Sample Usage Code",
    "Filtered",
    "Best Value",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
]

for col in normalize_cols:
    if col not in df.columns:
        df[col] = ""
    df[col] = df[col].fillna("").astype(str).str.strip()

match_audit["Location"] = match_audit["Location"].fillna("").astype(str).str.strip()
match_audit["Matched_Date"] = match_audit["Matched_Date"].fillna("").astype(str).str.strip()

for col in wellmeta.columns:
    wellmeta[col] = wellmeta[col].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")
match_audit["Matched_Date_dt"] = pd.to_datetime(match_audit["Matched_Date"], errors="coerce")

# ------------------------------------------------------------------
# Keep only checked matched locations with nonblank matched dates
# ------------------------------------------------------------------
retained_matches = (
    match_audit.loc[
        (match_audit["Location"] != "") &
        match_audit["Matched_Date_dt"].notna(),
        ["Location", "Matched_Date_dt"]
    ]
    .drop_duplicates()
    .copy()
)

# ------------------------------------------------------------------
# Deduplicate WellMeta on Location, preserving first occurrence
# ------------------------------------------------------------------
wellmeta_meta = (
    wellmeta.loc[wellmeta["Location"] != ""]
    .drop_duplicates(subset=["Location"], keep="first")
    .copy()
)

# ------------------------------------------------------------------
# Parse result values and derive state in full EIM table
# ------------------------------------------------------------------
res_txt = df["Result"].fillna("").astype(str).str.strip()
qual = df["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper()
detect = df["Detect?"].fillna("").astype(str).str.strip().str.upper()
analyte = df["Parameter"].fillna("").astype(str).str.strip()
filtered = df["Filtered"].fillna("").astype(str).str.strip().str.upper()

res_core = (
    res_txt
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

res_num = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

best_value_num = pd.to_numeric(
    df["Best Value"].fillna("").astype(str).str.strip().str.replace(",", "", regex=False),
    errors="coerce"
)

nd_text = res_txt.str.contains(
    r"\bND\b|NON[- ]?DETECT|NOT DETECT|BDL|U\b",
    case=False,
    regex=True,
    na=False,
)

state = np.where(
    detect.isin(["Y", "YES", "TRUE", "T"]),
    "D",
    np.where(
        qual != "",
        qual,
        np.where(
            detect.isin(["N", "NO", "FALSE", "F"]) | nd_text,
            "N",
            "NF"
        )
    )
)

# Build analyte key with filtered/nonfiltered split.
# Convention:
# - Filtered = N  -> analyte_NF
# - otherwise     -> analyte
analyte_key = np.where(
    filtered == "N",
    analyte + "_NF",
    analyte
)

df["result_text"] = res_txt
df["result_num"] = res_num
df["best_value_num"] = best_value_num
df["analyte_base"] = analyte
df["analyte"] = analyte_key
df["filtered_flag"] = filtered
df["qualifier_state"] = state

# ------------------------------------------------------------------
# Exclude temperature analyte
# ------------------------------------------------------------------
df["analyte_base_norm"] = df["analyte_base"].fillna("").astype(str).str.strip().str.lower()

# ------------------------------------------------------------------
# Keep only rows with real location, sample date, analyte
# Exclude known blank / equipment blank sample purposes and waste usage code
# Exclude temperature
# ------------------------------------------------------------------
df_valid = df.loc[
    (df["Location"] != "") &
    (df["Date Sampled_dt"].notna()) &
    (df["analyte"] != "") &
    (df["analyte_base_norm"] != "temperature") &
    (~df["Sample Purpose"].fillna("").astype(str).str.strip().str.upper().isin(["FB", "PEB", "EQB"])) &
    (df["Sample Usage Code"].fillna("").astype(str).str.strip().str.upper() != "WST")
].copy()

# ------------------------------------------------------------------
# Distinct candidate dates by location
# ------------------------------------------------------------------
candidate_dates = (
    df_valid[["Location", "Date Sampled_dt"]]
    .drop_duplicates()
    .copy()
)

# ------------------------------------------------------------------
# Build retained date list per location using coverage pruning
# ------------------------------------------------------------------
retained_date_rows = []

for _, r in retained_matches.iterrows():
    loc = str(r["Location"]).strip()
    matched_date = r["Matched_Date_dt"]

    loc_dates = candidate_dates.loc[candidate_dates["Location"] == loc].copy()

    if loc_dates.empty:
        continue

    loc_dates["delta_days"] = (loc_dates["Date Sampled_dt"] - matched_date).abs().dt.days
    loc_dates = loc_dates.sort_values(
        ["delta_days", "Date Sampled_dt"],
        ascending=[True, False],
        na_position="last"
    )

    anchor_date = loc_dates.iloc[0]["Date Sampled_dt"]
    window_start = anchor_date - pd.Timedelta(days=COMPOSITE_WINDOW_DAYS)
    window_end = anchor_date + pd.Timedelta(days=COMPOSITE_WINDOW_DAYS)

    candidate_loc_dates = loc_dates.loc[
        (loc_dates["Date Sampled_dt"] >= window_start) &
        (loc_dates["Date Sampled_dt"] <= window_end)
    ].copy()

    if candidate_loc_dates.empty:
        continue

    date_analyte_sets = {}
    for dt in candidate_loc_dates["Date Sampled_dt"].tolist():
        analytes_this_date = set(
            df_valid.loc[
                (df_valid["Location"] == loc) &
                (df_valid["Date Sampled_dt"] == dt) &
                (df_valid["analyte"] != ""),
                "analyte"
            ].dropna().astype(str).str.strip().tolist()
        )
        date_analyte_sets[dt] = analytes_this_date

    kept_dates = []
    covered_analytes = set()

    for _, drow in candidate_loc_dates.iterrows():
        dt = drow["Date Sampled_dt"]
        analytes_this_date = date_analyte_sets.get(dt, set())

        if len(kept_dates) == 0:
            kept_dates.append(dt)
            covered_analytes |= analytes_this_date
        else:
            new_analytes = analytes_this_date - covered_analytes
            if len(new_analytes) > 0:
                kept_dates.append(dt)
                covered_analytes |= analytes_this_date

    for dt in kept_dates:
        retained_date_rows.append({
            "Location": loc,
            "Sample_Date_dt": dt,
            "Matched_Date_dt": matched_date,
        })

retained_dates = pd.DataFrame(retained_date_rows)

if retained_dates.empty:
    raise ValueError("No retained sample dates were found after coverage pruning.")

# ------------------------------------------------------------------
# Pull only rows from retained contributing sample dates
# ------------------------------------------------------------------
retained_long = df_valid.merge(
    retained_dates,
    left_on=["Location", "Date Sampled_dt"],
    right_on=["Location", "Sample_Date_dt"],
    how="inner"
).copy()

retained_long["sample_event_key"] = (
    retained_long["Location"].fillna("").astype(str).str.strip()
    + " | "
    + retained_long["Date Sampled_dt"].dt.strftime("%Y-%m-%d").fillna("")
)

# ------------------------------------------------------------------
# Save intermediate retained long table for inspection
# ------------------------------------------------------------------
retained_long_audit = retained_long[[
    "sample_event_key",
    "Location",
    "Date Sampled",
    "Date Sampled_dt",
    "Matched_Date_dt",
    "Field Sample ID",
    "Parameter",
    "analyte",
    "Filtered",
    "Sample Purpose",
    "Sample Usage Code",
    "Result",
    "result_num",
    "Best Value",
    "best_value_num",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
    "qualifier_state",
]].copy()

retained_long_audit = retained_long_audit.sort_values(
    ["Location", "Date Sampled_dt", "Field Sample ID", "analyte", "Parameter"],
    ascending=[True, True, True, True, True],
    na_position="last"
).reset_index(drop=True)

date_cols = ["Date Sampled_dt", "Matched_Date_dt"]
for col in date_cols:
    if col in retained_long_audit.columns:
        retained_long_audit[col] = pd.to_datetime(retained_long_audit[col], errors="coerce").dt.strftime("%Y-%m-%d")
        retained_long_audit[col] = retained_long_audit[col].fillna("")

retained_long_audit.to_excel(OUT_RETAINED_LONG, index=False)

# ------------------------------------------------------------------
# Working long table
# Keep separate rows by retained actual sample date
# ------------------------------------------------------------------
syn_long = pd.DataFrame({
    "sample_event_key": retained_long["sample_event_key"],
    "location": retained_long["Location"],
    "sample_date": retained_long["Date Sampled_dt"],
    "field_sample_id": retained_long["Field Sample ID"],
    "analyte": retained_long["analyte"],
    "analyte_base": retained_long["analyte_base"],
    "filtered": retained_long["Filtered"].fillna("").astype(str).str.strip().str.upper(),
    "result_text": retained_long["result_text"],
    "result_num": retained_long["result_num"],
    "best_value_text": retained_long["Best Value"].fillna("").astype(str).str.strip(),
    "best_value_num": retained_long["best_value_num"],
    "units": retained_long["Units"],
    "lab_qualifier": retained_long["Lab Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_qualifier": retained_long["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_reason_codes": retained_long["Validation Reason Codes"].fillna("").astype(str).str.strip(),
    "detect_flag": retained_long["Detect?"].fillna("").astype(str).str.strip().str.upper(),
    "sample_purpose": retained_long["Sample Purpose"].fillna("").astype(str).str.strip(),
    "sample_usage_code": retained_long["Sample Usage Code"].fillna("").astype(str).str.strip(),
    "usable": retained_long["Usable"].fillna("").astype(str).str.strip(),
    "lab_method": retained_long["Lab Method"].fillna("").astype(str).str.strip(),
    "mdl": retained_long["Method Detection Limit"].fillna("").astype(str).str.strip(),
    "rdl": retained_long["Report Detection Limit"].fillna("").astype(str).str.strip(),
    "state": retained_long["qualifier_state"],
})

syn_long = syn_long[
    (syn_long["sample_event_key"] != "") &
    (syn_long["analyte"] != "")
].copy()

# ------------------------------------------------------------------
# Keep best row per Location + Sample_Date + analyte
# ------------------------------------------------------------------
info_rank_map = {
    "D": 6,
    "J": 5,
    "UJ": 4,
    "N": 3,
    "U": 3,
    "R": 2,
    "NF": 1,
}

syn_long["info_rank"] = syn_long["state"].map(info_rank_map).fillna(2).astype(int)

final_rows = (
    syn_long
    .sort_values(
        [
            "sample_event_key",
            "analyte",
            "info_rank",
            "result_num",
            "best_value_num",
            "sample_date",
            "field_sample_id",
        ],
        ascending=[True, True, False, False, False, False, True],
        na_position="last"
    )
    .drop_duplicates(["sample_event_key", "analyte"], keep="first")
    .copy()
)

# ------------------------------------------------------------------
# Keep analytes with at least one real numeric value in retained data
# ------------------------------------------------------------------
kept_analytes_final = sorted(
    final_rows.loc[final_rows["result_num"].notna(), "analyte"].dropna().unique().tolist()
)

final_rows = final_rows[final_rows["analyte"].isin(kept_analytes_final)].copy()

# ------------------------------------------------------------------
# Row metadata
# - Sample metadata for all outputs
# - WellMeta metadata only for rotated numeric matrix
# ------------------------------------------------------------------
sample_meta = (
    final_rows[["sample_event_key", "location", "sample_date"]]
    .drop_duplicates()
    .sort_values(["location", "sample_date", "sample_event_key"], ascending=[True, True, True], na_position="last")
)

sample_order = sample_meta["sample_event_key"].tolist()

rotated_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

rotated_meta["Sample_Date"] = pd.to_datetime(rotated_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
rotated_meta["Sample_Date"] = rotated_meta["Sample_Date"].fillna("")

rotated_meta = rotated_meta.merge(
    wellmeta_meta,
    on="Location",
    how="left"
)

# Preserve WellMeta column order, but avoid duplicating Location
wellmeta_cols = [c for c in wellmeta_meta.columns if c != "Location"]

rotated_meta = rotated_meta[["sample_event_key", "Location", "Sample_Date"] + wellmeta_cols].copy()

# ------------------------------------------------------------------
# Table 1 — Rotated numeric matrix with WellMeta columns first
# Keep numeric result whenever result_num exists, regardless of qualifier
# ------------------------------------------------------------------
rot_long = final_rows[["sample_event_key", "analyte", "result_num"]].copy()
rot_long = rot_long[rot_long["analyte"].isin(kept_analytes_final)].copy()
rot_long["value_num"] = rot_long["result_num"]

rotated_matrix = rot_long.pivot(index="sample_event_key", columns="analyte", values="value_num")
rotated_matrix = rotated_matrix.reindex(index=sample_order, columns=kept_analytes_final)

rotated_out = rotated_meta.set_index("sample_event_key")
rotated_out = rotated_out.reindex(sample_order)
rotated_out = rotated_out.join(rotated_matrix, how="left")
rotated_out = rotated_out.reset_index(drop=True)

rotated_out.to_excel(OUT_ROTATED, index=False)

# ------------------------------------------------------------------
# Table 2 — Value / qualifier / selected review fields matrix
# Lean metadata: Location and Sample_Date only
# ------------------------------------------------------------------
vq_long = final_rows[[
    "sample_event_key",
    "analyte",
    "result_num",
    "state",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detect_flag",
    "best_value_text",
    "best_value_num",
    "usable",
    "filtered",
]].copy()

vq_long = vq_long[vq_long["analyte"].isin(kept_analytes_final)].copy()

vq_long = vq_long.rename(columns={
    "result_num": "value",
    "state": "qualifier",
    "detect_flag": "detected",
    "best_value_text": "best_value",
    "best_value_num": "best_value_num",
})

subfields = [
    "value",
    "qualifier",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detected",
    "best_value",
    "best_value_num",
    "usable",
    "filtered",
]

parts = []
for sub in subfields:
    part = vq_long.pivot(index="sample_event_key", columns="analyte", values=sub)
    part = part.reindex(index=sample_order, columns=kept_analytes_final)
    part.columns = pd.MultiIndex.from_product([part.columns, [sub]])
    parts.append(part)

value_qualifier_matrix = pd.concat(parts, axis=1)

ordered_cols = []
for a in kept_analytes_final:
    for sub in subfields:
        ordered_cols.append((a, sub))

value_qualifier_matrix = value_qualifier_matrix.reindex(
    columns=pd.MultiIndex.from_tuples(ordered_cols)
)
value_qualifier_matrix = value_qualifier_matrix.reindex(sample_order)

vq_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

vq_meta["Sample_Date"] = pd.to_datetime(vq_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
vq_meta["Sample_Date"] = vq_meta["Sample_Date"].fillna("")

vq_meta = vq_meta.set_index("sample_event_key")
vq_meta = vq_meta.reindex(sample_order)

value_qualifier_export = pd.concat([vq_meta, value_qualifier_matrix], axis=1)
value_qualifier_export = value_qualifier_export.reset_index(drop=True)

value_qualifier_export.to_excel(OUT_VALUE_QUAL, index=False)

print("Saved:")
print(f" - {OUT_RETAINED_LONG}")
print(f" - {OUT_ROTATED}")
print(f" - {OUT_VALUE_QUAL}")
print(f"Retained sample events: {len(sample_order):,}")
print(f"Retained analytes: {len(kept_analytes_final):,}")
print(f"Composite window: +/- {COMPOSITE_WINDOW_DAYS} days from selected anchor date")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_retained_long.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_rotated_numeric_matrix.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_value_qualifier_matrix.xlsx
Retained sample events: 97
Retained analytes: 442
Composite window: +/- 28 days from selected anchor date

In [6]:
# Cell 4c — Build treatment/influent/effluent candidate rows in revised 4b-aligned format
#
# Purpose:
# - Read influent/effluent EIM export
# - Harmonize current EIM-native schema to notebook working names
# - Parse numeric results and derive qualifier state
# - Apply the same screening logic established in revised 4b
# - Exclude temperature analyte
# - Build candidate summary rows for each unique Location:
#     MostRecent = most recent actual sample event, full analyte row-set
#     MaxCr      = actual sample event with highest Chromium, full analyte row-set
#     MinS       = actual sample event with lowest Sulfate, full analyte row-set
#     GeoMean    = analyte-wise geometric mean across positive numeric values,
#                  with qualifier/provenance fields filled using most frequent
#                  value per analyte within location; Sample_Date set to most recent
# - Write outputs aligned to revised 4b structure:
#     * rotated numeric matrix: Location, Sample_Date, then WellMeta-style metadata columns (blank here), then analytes
#     * value/qualifier matrix: lean metadata only (Location, Sample_Date)
#
# Outputs:
# 1. treatment_candidate_retained_long.xlsx
# 2. treatment_candidate_rotated_numeric_matrix.xlsx
# 3. treatment_candidate_value_qualifier_matrix.xlsx
#
# Notes:
# - No violin plots.
# - Output row identity is carried in Location using suffixes:
#     _MostRecent, _GeoMean, _MaxCr, _MinS
# - sample_event_key remains internal only.
# - Metadata columns matching WellMeta_Complete are included in the rotated numeric matrix
#   but left blank for now, pending custom treatment/zonal sample labeling.
# - For GeoMean rows:
#     * value = geometric mean of positive numeric values
#     * Sample_Date = most recent sample date at that location
#     * qualifier-style fields = most frequent observed value for that analyte in that location
# - MaxCr is selected by highest Chromium numeric result after the general 4b-style screening.
#   No extra Validation Qualifier == NQ gate is applied.

from pathlib import Path
import numpy as np
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")

EIM_FILE = WORK_DIR / "InfEff_ao_09_23_2026.csv"
WELLMETA_FILE = WORK_DIR / "WellMeta_Complete.xlsx"

RESULTS_DIR = WORK_DIR / "Results_v2"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

OUT_RETAINED_LONG = RESULTS_DIR / "treatment_candidate_retained_long.xlsx"
OUT_ROTATED = RESULTS_DIR / "treatment_candidate_rotated_numeric_matrix.xlsx"
OUT_VALUE_QUAL = RESULTS_DIR / "treatment_candidate_value_qualifier_matrix.xlsx"

MAX_SELECTOR_ANALYTE = "Chromium"
MIN_SELECTOR_ANALYTE = "Sulfate"

# ------------------------------------------------------------------
# Read inputs
# ------------------------------------------------------------------
eim_raw = pd.read_csv(EIM_FILE, dtype=str, low_memory=False)
wellmeta = pd.read_excel(WELLMETA_FILE, dtype=str)

eim_raw.columns = [str(c).strip() for c in eim_raw.columns]
wellmeta.columns = [str(c).strip() for c in wellmeta.columns]

# ------------------------------------------------------------------
# Harmonize EIM schema to internal working names
# ------------------------------------------------------------------
eim = eim_raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
    "Report Units": "Units",
    "Detected": "Detect?",
})

required_eim = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Validation Qualifier",
    "Detect?",
]

missing_eim = [c for c in required_eim if c not in eim.columns]
if missing_eim:
    raise ValueError(f"Missing required columns in influent/effluent EIM file after rename: {missing_eim}")

if "Location" not in wellmeta.columns:
    raise ValueError("WellMeta_Complete.xlsx must contain a 'Location' column.")

# Preserve WellMeta column order for rotated output metadata block
wellmeta_cols = [c for c in wellmeta.columns if c != "Location"]

# ------------------------------------------------------------------
# Normalize fields
# ------------------------------------------------------------------
df = eim.copy()

normalize_cols = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Sample Purpose",
    "Sample Usage Code",
    "Filtered",
    "Best Value",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
]

for col in normalize_cols:
    if col not in df.columns:
        df[col] = ""
    df[col] = df[col].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")

# ------------------------------------------------------------------
# Parse result values and derive state
# ------------------------------------------------------------------
res_txt = df["Result"].fillna("").astype(str).str.strip()
qual = df["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper()
detect = df["Detect?"].fillna("").astype(str).str.strip().str.upper()
analyte = df["Parameter"].fillna("").astype(str).str.strip()
filtered = df["Filtered"].fillna("").astype(str).str.strip().str.upper()

res_core = (
    res_txt
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

res_num = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

best_value_num = pd.to_numeric(
    df["Best Value"].fillna("").astype(str).str.strip().str.replace(",", "", regex=False),
    errors="coerce"
)

nd_text = res_txt.str.contains(
    r"\bND\b|NON[- ]?DETECT|NOT DETECT|BDL|U\b",
    case=False,
    regex=True,
    na=False,
)

state = np.where(
    detect.isin(["Y", "YES", "TRUE", "T"]),
    "D",
    np.where(
        qual != "",
        qual,
        np.where(
            detect.isin(["N", "NO", "FALSE", "F"]) | nd_text,
            "N",
            "NF"
        )
    )
)

analyte_key = np.where(
    filtered == "N",
    analyte + "_NF",
    analyte
)

df["result_text"] = res_txt
df["result_num"] = res_num
df["best_value_num"] = best_value_num
df["analyte_base"] = analyte
df["analyte"] = analyte_key
df["filtered_flag"] = filtered
df["qualifier_state"] = state
df["analyte_base_norm"] = df["analyte_base"].fillna("").astype(str).str.strip().str.lower()

# ------------------------------------------------------------------
# Keep only rows with real location, sample date, analyte
# Exclude known blank / equipment blank sample purposes and waste usage code
# Exclude temperature
# ------------------------------------------------------------------
df_valid = df.loc[
    (df["Location"] != "") &
    (df["Date Sampled_dt"].notna()) &
    (df["analyte"] != "") &
    (df["analyte_base_norm"] != "temperature") &
    (~df["Sample Purpose"].fillna("").astype(str).str.strip().str.upper().isin(["FB", "PEB", "EQB"])) &
    (df["Sample Usage Code"].fillna("").astype(str).str.strip().str.upper() != "WST")
].copy()

# ------------------------------------------------------------------
# Stable sample_event_key
# ------------------------------------------------------------------
df_valid["sample_event_key"] = np.where(
    df_valid["Field Sample ID"].fillna("").astype(str).str.strip() != "",
    df_valid["Location"].fillna("").astype(str).str.strip()
    + " | "
    + df_valid["Date Sampled_dt"].dt.strftime("%Y-%m-%d").fillna("")
    + " | "
    + df_valid["Field Sample ID"].fillna("").astype(str).str.strip(),
    df_valid["Location"].fillna("").astype(str).str.strip()
    + " | "
    + df_valid["Date Sampled_dt"].dt.strftime("%Y-%m-%d").fillna("")
)

# ------------------------------------------------------------------
# Deduplicate within sample_event_key + analyte
# ------------------------------------------------------------------
info_rank_map = {
    "D": 6,
    "J": 5,
    "UJ": 4,
    "N": 3,
    "U": 3,
    "R": 2,
    "NF": 1,
}

dedup = df_valid.copy()
dedup["info_rank"] = dedup["qualifier_state"].map(info_rank_map).fillna(2).astype(int)

dedup = (
    dedup
    .sort_values(
        [
            "sample_event_key",
            "analyte",
            "info_rank",
            "result_num",
            "best_value_num",
            "Date Sampled_dt",
            "Field Sample ID",
        ],
        ascending=[True, True, False, False, False, False, True],
        na_position="last"
    )
    .drop_duplicates(["sample_event_key", "analyte"], keep="first")
    .copy()
)

# ------------------------------------------------------------------
# Keep analytes with at least one real numeric value
# ------------------------------------------------------------------
kept_analytes = sorted(
    dedup.loc[dedup["result_num"].notna(), "analyte"].dropna().unique().tolist()
)
dedup = dedup[dedup["analyte"].isin(kept_analytes)].copy()

# ------------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------------
def geom_mean(series):
    vals = pd.to_numeric(series, errors="coerce")
    vals = vals[np.isfinite(vals)]
    vals = vals[vals > 0]
    if len(vals) == 0:
        return np.nan
    return float(np.exp(np.mean(np.log(vals))))

def mode_or_blank(series):
    s = pd.Series(series).fillna("").astype(str).str.strip()
    s = s[s != ""]
    if s.empty:
        return ""
    vc = s.value_counts(dropna=False)
    return str(vc.index[0]).strip()

# ------------------------------------------------------------------
# Build candidate rows per location
# ------------------------------------------------------------------
candidate_long_rows = []

for loc in sorted(dedup["Location"].dropna().astype(str).str.strip().unique().tolist()):
    loc_df = dedup.loc[dedup["Location"] == loc].copy()
    if loc_df.empty:
        continue

    sample_dates = (
        loc_df[["sample_event_key", "Date Sampled_dt"]]
        .drop_duplicates()
        .sort_values(["Date Sampled_dt", "sample_event_key"], ascending=[False, True], na_position="last")
    )

    if sample_dates.empty:
        continue

    most_recent_key = sample_dates.iloc[0]["sample_event_key"]
    most_recent_date = sample_dates.iloc[0]["Date Sampled_dt"]

    # MostRecent row
    mr = loc_df.loc[loc_df["sample_event_key"] == most_recent_key].copy()
    mr["Location_out"] = loc + "_MostRecent"
    mr["Sample_Date_out"] = most_recent_date
    candidate_long_rows.append(mr)

    # MaxCr row
    max_cr_rows = loc_df.loc[
        (loc_df["analyte_base"] == MAX_SELECTOR_ANALYTE) &
        loc_df["result_num"].notna()
    ].copy()

    if not max_cr_rows.empty:
        max_cr_rows = max_cr_rows.sort_values(
            ["result_num", "Date Sampled_dt", "Field Sample ID"],
            ascending=[False, False, True],
            na_position="last"
        )
        max_cr_key = max_cr_rows.iloc[0]["sample_event_key"]
        max_cr_date = max_cr_rows.iloc[0]["Date Sampled_dt"]

        maxr = loc_df.loc[loc_df["sample_event_key"] == max_cr_key].copy()
        maxr["Location_out"] = loc + "_MaxCr"
        maxr["Sample_Date_out"] = max_cr_date
        candidate_long_rows.append(maxr)

    # MinS row
    min_s_rows = loc_df.loc[
        (loc_df["analyte_base"] == MIN_SELECTOR_ANALYTE) &
        loc_df["result_num"].notna()
    ].copy()

    if not min_s_rows.empty:
        min_s_rows = min_s_rows.sort_values(
            ["result_num", "Date Sampled_dt", "Field Sample ID"],
            ascending=[True, False, True],
            na_position="last"
        )
        min_s_key = min_s_rows.iloc[0]["sample_event_key"]
        min_s_date = min_s_rows.iloc[0]["Date Sampled_dt"]

        minr = loc_df.loc[loc_df["sample_event_key"] == min_s_key].copy()
        minr["Location_out"] = loc + "_MinS"
        minr["Sample_Date_out"] = min_s_date
        candidate_long_rows.append(minr)

    # GeoMean row
    geo_rows = []
    for analyte_name in kept_analytes:
        grp = loc_df.loc[loc_df["analyte"] == analyte_name].copy()
        if grp.empty:
            continue

        geo_value = geom_mean(grp["result_num"])

        geo_rows.append({
            "Location": loc,
            "Location_out": loc + "_GeoMean",
            "Sample_Date_out": most_recent_date,
            "Field Sample ID": "",
            "Date Sampled_dt": most_recent_date,
            "Date Sampled": most_recent_date.strftime("%Y-%m-%d") if pd.notna(most_recent_date) else "",
            "Parameter": grp["Parameter"].iloc[0] if "Parameter" in grp.columns and len(grp) else "",
            "analyte": analyte_name,
            "analyte_base": grp["analyte_base"].iloc[0] if "analyte_base" in grp.columns and len(grp) else analyte_name,
            "Filtered": grp["Filtered"].iloc[0] if "Filtered" in grp.columns and len(grp) else "",
            "Result": "",
            "result_text": "",
            "result_num": geo_value,
            "Best Value": "",
            "best_value_num": np.nan,
            "Units": mode_or_blank(grp["Units"]),
            "Lab Qualifier": mode_or_blank(grp["Lab Qualifier"]),
            "Validation Qualifier": mode_or_blank(grp["Validation Qualifier"]),
            "Validation Reason Codes": mode_or_blank(grp["Validation Reason Codes"]),
            "Detect?": mode_or_blank(grp["Detect?"]),
            "Sample Purpose": mode_or_blank(grp["Sample Purpose"]),
            "Sample Usage Code": mode_or_blank(grp["Sample Usage Code"]),
            "Usable": mode_or_blank(grp["Usable"]),
            "Lab Method": mode_or_blank(grp["Lab Method"]),
            "Method Detection Limit": mode_or_blank(grp["Method Detection Limit"]),
            "Report Detection Limit": mode_or_blank(grp["Report Detection Limit"]),
            "qualifier_state": mode_or_blank(grp["qualifier_state"]),
            "sample_event_key": loc + " | GeoMean",
        })

    if geo_rows:
        candidate_long_rows.append(pd.DataFrame(geo_rows))

# ------------------------------------------------------------------
# Combine candidate rows
# ------------------------------------------------------------------
if not candidate_long_rows:
    raise ValueError("No treatment candidate rows were built.")

candidate_long = pd.concat(candidate_long_rows, ignore_index=True)

candidate_long["sample_event_key_out"] = (
    candidate_long["Location_out"].fillna("").astype(str).str.strip()
    + " | "
    + pd.to_datetime(candidate_long["Sample_Date_out"], errors="coerce").dt.strftime("%Y-%m-%d").fillna("")
)

# ------------------------------------------------------------------
# Save retained long / audit table
# ------------------------------------------------------------------
retained_long_audit = candidate_long[[
    "sample_event_key_out",
    "Location_out",
    "Sample_Date_out",
    "Location",
    "Date Sampled",
    "Date Sampled_dt",
    "Field Sample ID",
    "Parameter",
    "analyte",
    "Filtered",
    "Sample Purpose",
    "Sample Usage Code",
    "Result",
    "result_num",
    "Best Value",
    "best_value_num",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
    "qualifier_state",
]].copy()

for col in ["Sample_Date_out", "Date Sampled_dt"]:
    retained_long_audit[col] = pd.to_datetime(retained_long_audit[col], errors="coerce").dt.strftime("%Y-%m-%d")
    retained_long_audit[col] = retained_long_audit[col].fillna("")

retained_long_audit = retained_long_audit.sort_values(
    ["Location_out", "analyte", "Field Sample ID"],
    ascending=[True, True, True],
    na_position="last"
).reset_index(drop=True)

retained_long_audit.to_excel(OUT_RETAINED_LONG, index=False)

# ------------------------------------------------------------------
# Build 4b-style working long table
# ------------------------------------------------------------------
syn_long = pd.DataFrame({
    "sample_event_key": candidate_long["sample_event_key_out"],
    "location": candidate_long["Location_out"],
    "sample_date": pd.to_datetime(candidate_long["Sample_Date_out"], errors="coerce"),
    "analyte": candidate_long["analyte"],
    "analyte_base": candidate_long["analyte_base"],
    "filtered": candidate_long["Filtered"].fillna("").astype(str).str.strip().str.upper(),
    "result_text": candidate_long["result_text"].fillna("").astype(str).str.strip(),
    "result_num": pd.to_numeric(candidate_long["result_num"], errors="coerce"),
    "best_value_text": candidate_long["Best Value"].fillna("").astype(str).str.strip(),
    "best_value_num": pd.to_numeric(candidate_long["best_value_num"], errors="coerce"),
    "units": candidate_long["Units"].fillna("").astype(str).str.strip(),
    "lab_qualifier": candidate_long["Lab Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_qualifier": candidate_long["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_reason_codes": candidate_long["Validation Reason Codes"].fillna("").astype(str).str.strip(),
    "detect_flag": candidate_long["Detect?"].fillna("").astype(str).str.strip().str.upper(),
    "sample_purpose": candidate_long["Sample Purpose"].fillna("").astype(str).str.strip(),
    "sample_usage_code": candidate_long["Sample Usage Code"].fillna("").astype(str).str.strip(),
    "usable": candidate_long["Usable"].fillna("").astype(str).str.strip(),
    "lab_method": candidate_long["Lab Method"].fillna("").astype(str).str.strip(),
    "mdl": candidate_long["Method Detection Limit"].fillna("").astype(str).str.strip(),
    "rdl": candidate_long["Report Detection Limit"].fillna("").astype(str).str.strip(),
    "state": candidate_long["qualifier_state"].fillna("").astype(str).str.strip().str.upper(),
})

syn_long = syn_long[
    (syn_long["sample_event_key"] != "") &
    (syn_long["analyte"] != "")
].copy()

# ------------------------------------------------------------------
# Keep best row per output-row/analyte
# ------------------------------------------------------------------
syn_long["info_rank"] = syn_long["state"].map(info_rank_map).fillna(2).astype(int)

final_rows = (
    syn_long
    .sort_values(
        [
            "sample_event_key",
            "analyte",
            "info_rank",
            "result_num",
            "best_value_num",
            "sample_date",
        ],
        ascending=[True, True, False, False, False, False],
        na_position="last"
    )
    .drop_duplicates(["sample_event_key", "analyte"], keep="first")
    .copy()
)

kept_analytes_final = sorted(
    final_rows.loc[final_rows["result_num"].notna(), "analyte"].dropna().unique().tolist()
)

final_rows = final_rows[final_rows["analyte"].isin(kept_analytes_final)].copy()

# ------------------------------------------------------------------
# Row metadata and order
# ------------------------------------------------------------------
row_type_order = {
    "MostRecent": 1,
    "GeoMean": 2,
    "MaxCr": 3,
    "MinS": 4,
}

sample_meta = final_rows[[
    "sample_event_key", "location", "sample_date"
]].drop_duplicates().copy()

sample_meta["base_location"] = sample_meta["location"].astype(str).str.replace(
    r"_(MostRecent|GeoMean|MaxCr|MinS)$", "", regex=True
)
sample_meta["row_type"] = sample_meta["location"].astype(str).str.extract(
    r"_(MostRecent|GeoMean|MaxCr|MinS)$", expand=False
).fillna("")
sample_meta["row_sort"] = sample_meta["row_type"].map(row_type_order).fillna(99).astype(int)

sample_meta = sample_meta.sort_values(
    ["base_location", "row_sort", "location"],
    ascending=[True, True, True],
    na_position="last"
)

sample_order = sample_meta["sample_event_key"].tolist()

# ------------------------------------------------------------------
# Build blank WellMeta-style metadata block for rotated output
# ------------------------------------------------------------------
rotated_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

rotated_meta["Sample_Date"] = pd.to_datetime(rotated_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
rotated_meta["Sample_Date"] = rotated_meta["Sample_Date"].fillna("")

for col in wellmeta_cols:
    rotated_meta[col] = ""

rotated_meta = rotated_meta[["sample_event_key", "Location", "Sample_Date"] + wellmeta_cols].copy()

# ------------------------------------------------------------------
# Table 1 — Rotated numeric matrix with revised 4b-aligned metadata columns
# ------------------------------------------------------------------
rot_long = final_rows[["sample_event_key", "analyte", "result_num"]].copy()
rot_long["value_num"] = rot_long["result_num"]

rotated_matrix = rot_long.pivot(index="sample_event_key", columns="analyte", values="value_num")
rotated_matrix = rotated_matrix.reindex(index=sample_order, columns=kept_analytes_final)

rotated_out = rotated_meta.set_index("sample_event_key")
rotated_out = rotated_out.reindex(sample_order)
rotated_out = rotated_out.join(rotated_matrix, how="left")
rotated_out = rotated_out.reset_index(drop=True)

rotated_out.to_excel(OUT_ROTATED, index=False)

# ------------------------------------------------------------------
# Table 2 — Value / qualifier / selected review fields matrix
# Lean metadata: Location and Sample_Date only
# ------------------------------------------------------------------
vq_long = final_rows[[
    "sample_event_key",
    "analyte",
    "result_num",
    "state",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detect_flag",
    "best_value_text",
    "best_value_num",
    "usable",
    "filtered",
]].copy()

vq_long = vq_long.rename(columns={
    "result_num": "value",
    "state": "qualifier",
    "detect_flag": "detected",
    "best_value_text": "best_value",
})

subfields = [
    "value",
    "qualifier",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detected",
    "best_value",
    "best_value_num",
    "usable",
    "filtered",
]

parts = []
for sub in subfields:
    part = vq_long.pivot(index="sample_event_key", columns="analyte", values=sub)
    part = part.reindex(index=sample_order, columns=kept_analytes_final)
    part.columns = pd.MultiIndex.from_product([part.columns, [sub]])
    parts.append(part)

value_qualifier_matrix = pd.concat(parts, axis=1)

ordered_cols = []
for a in kept_analytes_final:
    for sub in subfields:
        ordered_cols.append((a, sub))

value_qualifier_matrix = value_qualifier_matrix.reindex(
    columns=pd.MultiIndex.from_tuples(ordered_cols)
)
value_qualifier_matrix = value_qualifier_matrix.reindex(sample_order)

vq_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

vq_meta["Sample_Date"] = pd.to_datetime(vq_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
vq_meta["Sample_Date"] = vq_meta["Sample_Date"].fillna("")

vq_meta = vq_meta.set_index("sample_event_key")
vq_meta = vq_meta.reindex(sample_order)

value_qualifier_export = pd.concat(
    [vq_meta[["Location", "Sample_Date"]], value_qualifier_matrix],
    axis=1
)
value_qualifier_export = value_qualifier_export.reset_index(drop=True)

value_qualifier_export.to_excel(OUT_VALUE_QUAL, index=False)

print("Saved:")
print(f" - {OUT_RETAINED_LONG}")
print(f" - {OUT_ROTATED}")
print(f" - {OUT_VALUE_QUAL}")
print(f"Candidate output rows: {len(sample_order):,}")
print(f"Candidate analytes: {len(kept_analytes_final):,}")
print(f"Unique source locations: {dedup['Location'].nunique():,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\treatment_candidate_retained_long.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\treatment_candidate_rotated_numeric_matrix.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\treatment_candidate_value_qualifier_matrix.xlsx
Candidate output rows: 23
Candidate analytes: 328
Unique source locations: 6

In [8]:
# Cell 4d — Append selected treatment GeoMean rows into final synoptic tables
# using revised 4b / 4c output structure
#
# Purpose:
# - Read the synoptic outputs from revised 4b
# - Read the treatment candidate outputs from revised 4c
# - Select only:
#     VS-CTUA-2-INF_GeoMean
#     VS-CTUA-6-EFF_GeoMean
# - Append those rows to the bottoms of the three synoptic tables
# - Preserve revised 4b numeric-table structure:
#     Location, Sample_Date, then WellMeta-style metadata columns, then analytes
# - Preserve qualifier table in its current pre-finalized structure
# - Allow treatment metadata gaps to remain blank
#
# Outputs:
# 1. synoptic_retained_long_plus_treatment_geomean.xlsx
# 2. synoptic_all_rotated_numeric_matrix_plus_treatment_geomean.xlsx
# 3. synoptic_all_value_qualifier_matrix_plus_treatment_geomean.xlsx
#
# Notes:
# - No header beautification is done here.
# - Blank metadata cells from treatment rows are retained as blank.
# - GeoMean rows are appended pragmatically for PCA preparation.

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

# 4b outputs
SYN_LONG_FILE = RESULTS_DIR / "synoptic_retained_long.xlsx"
SYN_ROTATED_FILE = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix.xlsx"
SYN_VALUE_QUAL_FILE = RESULTS_DIR / "synoptic_all_value_qualifier_matrix.xlsx"

# 4c outputs
TRT_LONG_FILE = RESULTS_DIR / "treatment_candidate_retained_long.xlsx"
TRT_ROTATED_FILE = RESULTS_DIR / "treatment_candidate_rotated_numeric_matrix.xlsx"
TRT_VALUE_QUAL_FILE = RESULTS_DIR / "treatment_candidate_value_qualifier_matrix.xlsx"

# 4d outputs
OUT_LONG = RESULTS_DIR / "synoptic_retained_long_plus_treatment_geomean.xlsx"
OUT_ROTATED = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean.xlsx"
OUT_VALUE_QUAL = RESULTS_DIR / "synoptic_all_value_qualifier_matrix_plus_treatment_geomean.xlsx"

TARGET_LOCATIONS = [
    "VS-CTUA-2-INF_GeoMean",
    "VS-CTUA-6-EFF_GeoMean",
]

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def align_columns_with_concat(left_df, right_df, fill_value_left=pd.NA, fill_value_right=pd.NA):
    """
    Align two flat DataFrames to the union of their columns.
    Column order follows left_df columns first, then right-only columns appended.
    """
    left_df = left_df.copy()
    right_df = right_df.copy()

    left_cols = list(left_df.columns)
    right_cols = list(right_df.columns)

    missing_in_right = [c for c in left_cols if c not in right_cols]
    if missing_in_right:
        right_missing_df = pd.DataFrame(
            {c: fill_value_right for c in missing_in_right},
            index=right_df.index
        )
        right_df = pd.concat([right_df, right_missing_df], axis=1)

    missing_in_left = [c for c in right_df.columns if c not in left_cols]
    if missing_in_left:
        left_missing_df = pd.DataFrame(
            {c: fill_value_left for c in missing_in_left},
            index=left_df.index
        )
        left_df = pd.concat([left_df, left_missing_df], axis=1)

    final_cols = list(left_cols) + [c for c in right_df.columns if c not in left_cols]
    left_df = left_df.reindex(columns=final_cols).copy()
    right_df = right_df.reindex(columns=final_cols).copy()

    return left_df, right_df

# ------------------------------------------------------------------
# Read source files
# ------------------------------------------------------------------
syn_long = clean_columns(pd.read_excel(SYN_LONG_FILE, dtype=str))
syn_rotated = clean_columns(pd.read_excel(SYN_ROTATED_FILE, header=0))
trt_long = clean_columns(pd.read_excel(TRT_LONG_FILE, dtype=str))
trt_rotated = clean_columns(pd.read_excel(TRT_ROTATED_FILE, header=0))

# Read qualifier tables flat on purpose.
# At this stage they are still in pre-finalized form.
syn_vq = clean_columns(pd.read_excel(SYN_VALUE_QUAL_FILE, header=0))
trt_vq = clean_columns(pd.read_excel(TRT_VALUE_QUAL_FILE, header=0))

# ------------------------------------------------------------------
# 1. Append retained-long rows
# ------------------------------------------------------------------
trt_long_loc_col = "Location_out" if "Location_out" in trt_long.columns else "Location"

trt_long_select = trt_long.loc[
    trt_long[trt_long_loc_col].fillna("").astype(str).str.strip().isin(TARGET_LOCATIONS)
].copy()

if trt_long_select.empty:
    available_vals = sorted(
        trt_long[trt_long_loc_col].fillna("").astype(str).str.strip().unique().tolist()
    )
    print("Available treatment long location values (first 50):")
    print(available_vals[:50])
    raise ValueError(f"No matching GeoMean rows found in treatment long table for {TARGET_LOCATIONS}")

syn_long_aligned, trt_long_aligned = align_columns_with_concat(
    syn_long,
    trt_long_select,
    fill_value_left="",
    fill_value_right=""
)

long_out = pd.concat([syn_long_aligned, trt_long_aligned], ignore_index=True)
long_out.to_excel(OUT_LONG, index=False)

# ------------------------------------------------------------------
# 2. Append rotated numeric rows
# ------------------------------------------------------------------
if "Location" not in syn_rotated.columns:
    raise ValueError("Synoptic rotated numeric table is missing Location.")
if "Location" not in trt_rotated.columns:
    raise ValueError("Treatment rotated numeric table is missing Location.")

trt_rotated_select = trt_rotated.loc[
    trt_rotated["Location"].fillna("").astype(str).str.strip().isin(TARGET_LOCATIONS)
].copy()

if trt_rotated_select.empty:
    available_vals = sorted(
        trt_rotated["Location"].fillna("").astype(str).str.strip().unique().tolist()
    )
    print("Available treatment rotated location values (first 50):")
    print(available_vals[:50])
    raise ValueError(f"No matching GeoMean rows found in treatment rotated table for {TARGET_LOCATIONS}")

syn_rotated_aligned, trt_rotated_aligned = align_columns_with_concat(
    syn_rotated,
    trt_rotated_select,
    fill_value_left=pd.NA,
    fill_value_right=pd.NA
)

rotated_out = pd.concat([syn_rotated_aligned, trt_rotated_aligned], ignore_index=True)
rotated_out.to_excel(OUT_ROTATED, index=False)

# ------------------------------------------------------------------
# 3. Append qualifier rows in current pre-finalized flat structure
# ------------------------------------------------------------------
if "Location" not in syn_vq.columns:
    raise ValueError("Synoptic qualifier table is missing Location.")
if "Location" not in trt_vq.columns:
    raise ValueError("Treatment qualifier table is missing Location.")

trt_vq_select = trt_vq.loc[
    trt_vq["Location"].fillna("").astype(str).str.strip().isin(TARGET_LOCATIONS)
].copy()

if trt_vq_select.empty:
    available_vals = sorted(
        trt_vq["Location"].fillna("").astype(str).str.strip().unique().tolist()
    )
    print("Available treatment qualifier location values (first 50):")
    print(available_vals[:50])
    raise ValueError(f"No matching GeoMean rows found in treatment qualifier table for {TARGET_LOCATIONS}")

syn_vq_aligned, trt_vq_aligned = align_columns_with_concat(
    syn_vq,
    trt_vq_select,
    fill_value_left="",
    fill_value_right=""
)

vq_out = pd.concat([syn_vq_aligned, trt_vq_aligned], ignore_index=True)
vq_out.to_excel(OUT_VALUE_QUAL, index=False)

# ------------------------------------------------------------------
# Save messages
# ------------------------------------------------------------------
print("Saved:")
print(f" - {OUT_LONG}")
print(f" - {OUT_ROTATED}")
print(f" - {OUT_VALUE_QUAL}")
print("Appended GeoMean rows:")
for x in TARGET_LOCATIONS:
    print(f" - {x}")
print(f"Results directory: {RESULTS_DIR}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_retained_long_plus_treatment_geomean.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_rotated_numeric_matrix_plus_treatment_geomean.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_value_qualifier_matrix_plus_treatment_geomean.xlsx
Appended GeoMean rows:
 - VS-CTUA-2-INF_GeoMean
 - VS-CTUA-6-EFF_GeoMean
Results directory: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2

In [9]:
# Cell 4e — Append selected R-80 zonal and borehole-fluid rows into final synoptic tables
#
# Purpose:
# - Read the appended synoptic outputs from 4d
# - Re-read combined_eim_full_timeline_raw.csv
# - Apply the same screening / parsing logic as 4b / 4c
# - Select:
#     1) the 7 distinct R-80 June 2026 sample dates, labeled:
#           R-80_z1 ... R-80_z7
#        in ascending sample-date order
#     2) the 2026-05-30 R-80 borehole-fluid event where Chromium has:
#           result_num = 23.4
#           Best Value = Y
#        labeled:
#           R-80_BHfluid
# - Append those 8 rows into:
#     * retained long
#     * rotated numeric matrix
#     * qualifier matrix
#
# Outputs:
# 1. synoptic_retained_long_plus_treatment_geomean_plus_r80zonal.xlsx
# 2. synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
# 3. synoptic_all_value_qualifier_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
#
# Notes:
# - Metadata columns matching WellMeta-style fields in the rotated numeric matrix
#   are left blank for the appended zonal/borehole-fluid rows.
# - Qualifier table remains in the current pre-finalized flat structure.
# - Temperature is excluded, matching revised 4b / 4c behavior.

from pathlib import Path
import numpy as np
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

# Current appended synoptic outputs from 4d
SYN_LONG_FILE = RESULTS_DIR / "synoptic_retained_long_plus_treatment_geomean.xlsx"
SYN_ROTATED_FILE = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean.xlsx"
SYN_VALUE_QUAL_FILE = RESULTS_DIR / "synoptic_all_value_qualifier_matrix_plus_treatment_geomean.xlsx"

# Source EIM export
EIM_FILE = RESULTS_DIR / "combined_eim_full_timeline_raw.csv"
WELLMETA_FILE = WORK_DIR / "WellMeta_Complete.xlsx"

# 4e outputs
OUT_LONG = RESULTS_DIR / "synoptic_retained_long_plus_treatment_geomean_plus_r80zonal.xlsx"
OUT_ROTATED = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx"
OUT_VALUE_QUAL = RESULTS_DIR / "synoptic_all_value_qualifier_matrix_plus_treatment_geomean_plus_r80zonal.xlsx"

TARGET_LOCATION = "R-80"
JUNE_YEAR = 2026
JUNE_MONTH = 6

BH_DATE = pd.Timestamp("2026-05-30")
BH_LABEL = "R-80_BHfluid"
BH_SELECTOR_ANALYTE = "Chromium"
BH_SELECTOR_RESULT = 23.4
BH_SELECTOR_BEST_VALUE = "Y"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def align_columns_with_concat(left_df, right_df, fill_value_left=pd.NA, fill_value_right=pd.NA):
    left_df = left_df.copy()
    right_df = right_df.copy()

    left_cols = list(left_df.columns)
    right_cols = list(right_df.columns)

    missing_in_right = [c for c in left_cols if c not in right_cols]
    if missing_in_right:
        right_missing_df = pd.DataFrame(
            {c: fill_value_right for c in missing_in_right},
            index=right_df.index
        )
        right_df = pd.concat([right_df, right_missing_df], axis=1)

    missing_in_left = [c for c in right_df.columns if c not in left_cols]
    if missing_in_left:
        left_missing_df = pd.DataFrame(
            {c: fill_value_left for c in missing_in_left},
            index=left_df.index
        )
        left_df = pd.concat([left_df, left_missing_df], axis=1)

    final_cols = list(left_cols) + [c for c in right_df.columns if c not in left_cols]
    left_df = left_df.reindex(columns=final_cols).copy()
    right_df = right_df.reindex(columns=final_cols).copy()

    return left_df, right_df

# ------------------------------------------------------------------
# Read current synoptic outputs
# ------------------------------------------------------------------
syn_long = clean_columns(pd.read_excel(SYN_LONG_FILE, dtype=str))
syn_rotated = clean_columns(pd.read_excel(SYN_ROTATED_FILE, header=0))
syn_vq = clean_columns(pd.read_excel(SYN_VALUE_QUAL_FILE, header=0))

wellmeta = clean_columns(pd.read_excel(WELLMETA_FILE, dtype=str))
if "Location" not in wellmeta.columns:
    raise ValueError("WellMeta_Complete.xlsx must contain a Location column.")
wellmeta_cols = [c for c in wellmeta.columns if c != "Location"]

# ------------------------------------------------------------------
# Read and harmonize EIM
# ------------------------------------------------------------------
eim_raw = clean_columns(pd.read_csv(EIM_FILE, dtype=str, low_memory=False))

eim = eim_raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
    "Report Units": "Units",
    "Detected": "Detect?",
})

required_eim = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Sample Purpose",
    "Sample Usage Code",
    "Filtered",
    "Best Value",
    "Usable",
    "Method Detection Limit",
    "Report Detection Limit",
]

missing_eim = [c for c in required_eim if c not in eim.columns]
if missing_eim:
    raise ValueError(f"Missing required columns in EIM file after rename: {missing_eim}")

df = eim.copy()

normalize_cols = [
    "Location",
    "Field Sample ID",
    "Date Sampled",
    "Parameter",
    "Result",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Sample Purpose",
    "Sample Usage Code",
    "Filtered",
    "Best Value",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
]

for col in normalize_cols:
    if col not in df.columns:
        df[col] = ""
    df[col] = df[col].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")

# ------------------------------------------------------------------
# Parse result values and derive state
# ------------------------------------------------------------------
res_txt = df["Result"].fillna("").astype(str).str.strip()
qual = df["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper()
detect = df["Detect?"].fillna("").astype(str).str.strip().str.upper()
analyte = df["Parameter"].fillna("").astype(str).str.strip()
filtered = df["Filtered"].fillna("").astype(str).str.strip().str.upper()

res_core = (
    res_txt
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

res_num = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

best_value_num = pd.to_numeric(
    df["Best Value"].fillna("").astype(str).str.strip().str.replace(",", "", regex=False),
    errors="coerce"
)

nd_text = res_txt.str.contains(
    r"\bND\b|NON[- ]?DETECT|NOT DETECT|BDL|U\b",
    case=False,
    regex=True,
    na=False,
)

state = np.where(
    detect.isin(["Y", "YES", "TRUE", "T"]),
    "D",
    np.where(
        qual != "",
        qual,
        np.where(
            detect.isin(["N", "NO", "FALSE", "F"]) | nd_text,
            "N",
            "NF"
        )
    )
)

analyte_key = np.where(
    filtered == "N",
    analyte + "_NF",
    analyte
)

df["result_text"] = res_txt
df["result_num"] = res_num
df["best_value_num"] = best_value_num
df["analyte_base"] = analyte
df["analyte"] = analyte_key
df["filtered_flag"] = filtered
df["qualifier_state"] = state
df["analyte_base_norm"] = df["analyte_base"].fillna("").astype(str).str.strip().str.lower()

# ------------------------------------------------------------------
# Apply same 4b/4c screening logic
# ------------------------------------------------------------------
df_valid = df.loc[
    (df["Location"] != "") &
    (df["Date Sampled_dt"].notna()) &
    (df["analyte"] != "") &
    (df["analyte_base_norm"] != "temperature") &
    (~df["Sample Purpose"].fillna("").astype(str).str.strip().str.upper().isin(["FB", "PEB", "EQB"])) &
    (df["Sample Usage Code"].fillna("").astype(str).str.strip().str.upper() != "WST")
].copy()

# Use a stable line-level sample_event_key for BH-fluid disambiguation
df_valid["sample_event_key"] = np.where(
    df_valid["Field Sample ID"].fillna("").astype(str).str.strip() != "",
    df_valid["Location"].fillna("").astype(str).str.strip()
    + " | "
    + df_valid["Date Sampled_dt"].dt.strftime("%Y-%m-%d").fillna("")
    + " | "
    + df_valid["Field Sample ID"].fillna("").astype(str).str.strip(),
    df_valid["Location"].fillna("").astype(str).str.strip()
    + " | "
    + df_valid["Date Sampled_dt"].dt.strftime("%Y-%m-%d").fillna("")
)

info_rank_map = {
    "D": 6,
    "J": 5,
    "UJ": 4,
    "N": 3,
    "U": 3,
    "R": 2,
    "NF": 1,
}

dedup = df_valid.copy()
dedup["info_rank"] = dedup["qualifier_state"].map(info_rank_map).fillna(2).astype(int)

dedup = (
    dedup
    .sort_values(
        [
            "sample_event_key",
            "analyte",
            "info_rank",
            "result_num",
            "best_value_num",
            "Date Sampled_dt",
            "Field Sample ID",
        ],
        ascending=[True, True, False, False, False, False, True],
        na_position="last"
    )
    .drop_duplicates(["sample_event_key", "analyte"], keep="first")
    .copy()
)

kept_analytes = sorted(
    dedup.loc[dedup["result_num"].notna(), "analyte"].dropna().unique().tolist()
)
dedup = dedup[dedup["analyte"].isin(kept_analytes)].copy()

# ------------------------------------------------------------------
# Select the 7 distinct June 2026 R-80 dates
# ------------------------------------------------------------------
r80_june_dates = (
    dedup.loc[
        (dedup["Location"] == TARGET_LOCATION) &
        (dedup["Date Sampled_dt"].dt.year == JUNE_YEAR) &
        (dedup["Date Sampled_dt"].dt.month == JUNE_MONTH),
        ["Date Sampled_dt"]
    ]
    .drop_duplicates()
    .sort_values(["Date Sampled_dt"], ascending=[True], na_position="last")
    .reset_index(drop=True)
)

if len(r80_june_dates) != 7:
    raise ValueError(f"Expected 7 distinct June 2026 R-80 dates, found {len(r80_june_dates)}")

date_label_map = {}
for i, (_, row) in enumerate(r80_june_dates.iterrows(), start=1):
    dt = row["Date Sampled_dt"]
    date_label_map[pd.Timestamp(dt).normalize()] = f"R-80_z{i}"

# Pull all screened/dedup rows for those 7 dates
june_rows = dedup.loc[
    (dedup["Location"] == TARGET_LOCATION) &
    (dedup["Date Sampled_dt"].dt.normalize().isin(date_label_map.keys()))
].copy()

june_rows["Location_out"] = june_rows["Date Sampled_dt"].dt.normalize().map(date_label_map)
june_rows["Sample_Date_out"] = june_rows["Date Sampled_dt"]

# ------------------------------------------------------------------
# Select the 2026-05-30 R-80 chromium borehole-fluid event
# Then pull the full analyte row-set for that sample_event_key
# ------------------------------------------------------------------
bh_selector = dedup.loc[
    (dedup["Location"] == TARGET_LOCATION) &
    (dedup["Date Sampled_dt"].dt.normalize() == BH_DATE.normalize()) &
    (dedup["analyte_base"] == BH_SELECTOR_ANALYTE) &
    (dedup["result_num"].round(6) == BH_SELECTOR_RESULT) &
    (dedup["Best Value"].fillna("").astype(str).str.strip().str.upper() == BH_SELECTOR_BEST_VALUE),
    ["sample_event_key", "Date Sampled_dt", "Field Sample ID", "result_num", "Best Value"]
].drop_duplicates()

if len(bh_selector) != 1:
    raise ValueError(
        f"Expected exactly 1 borehole-fluid selector event on {BH_DATE.date()} with "
        f"{BH_SELECTOR_ANALYTE}={BH_SELECTOR_RESULT} and Best Value={BH_SELECTOR_BEST_VALUE}; found {len(bh_selector)}"
    )

bh_event_key = bh_selector.iloc[0]["sample_event_key"]

bh_rows = dedup.loc[
    dedup["sample_event_key"] == bh_event_key
].copy()

bh_rows["Location_out"] = BH_LABEL
bh_rows["Sample_Date_out"] = bh_rows["Date Sampled_dt"]

# ------------------------------------------------------------------
# Combine appended rows
# ------------------------------------------------------------------
selected_long = pd.concat([june_rows, bh_rows], ignore_index=True)

if selected_long.empty:
    raise ValueError("No selected zonal/borehole-fluid rows were found after event selection.")

selected_long["sample_event_key_out"] = (
    selected_long["Location_out"].fillna("").astype(str).str.strip()
    + " | "
    + selected_long["Sample_Date_out"].dt.strftime("%Y-%m-%d").fillna("")
)

# ------------------------------------------------------------------
# Retained-long append
# ------------------------------------------------------------------
append_long = selected_long[[
    "sample_event_key_out",
    "Location_out",
    "Sample_Date_out",
    "Location",
    "Date Sampled",
    "Date Sampled_dt",
    "Field Sample ID",
    "Parameter",
    "analyte",
    "Filtered",
    "Sample Purpose",
    "Sample Usage Code",
    "Result",
    "result_num",
    "Best Value",
    "best_value_num",
    "Units",
    "Lab Qualifier",
    "Validation Qualifier",
    "Validation Reason Codes",
    "Detect?",
    "Usable",
    "Lab Method",
    "Method Detection Limit",
    "Report Detection Limit",
    "qualifier_state",
]].copy()

append_long["Sample_Date_out"] = pd.to_datetime(append_long["Sample_Date_out"], errors="coerce").dt.strftime("%Y-%m-%d")
append_long["Sample_Date_out"] = append_long["Sample_Date_out"].fillna("")
append_long["Date Sampled_dt"] = pd.to_datetime(append_long["Date Sampled_dt"], errors="coerce").dt.strftime("%Y-%m-%d")
append_long["Date Sampled_dt"] = append_long["Date Sampled_dt"].fillna("")

syn_long_aligned, append_long_aligned = align_columns_with_concat(
    syn_long,
    append_long,
    fill_value_left="",
    fill_value_right=""
)

long_out = pd.concat([syn_long_aligned, append_long_aligned], ignore_index=True)
long_out.to_excel(OUT_LONG, index=False)

# ------------------------------------------------------------------
# Build working long table for rotated + qualifier append
# For June zonal rows, dedup again at output-row/analyte level because
# multiple source sample_event_keys may exist on the same date.
# ------------------------------------------------------------------
syn_long_work = pd.DataFrame({
    "sample_event_key": selected_long["sample_event_key_out"],
    "location": selected_long["Location_out"],
    "sample_date": selected_long["Sample_Date_out"],
    "field_sample_id": selected_long["Field Sample ID"],
    "analyte": selected_long["analyte"],
    "analyte_base": selected_long["analyte_base"],
    "filtered": selected_long["Filtered"].fillna("").astype(str).str.strip().str.upper(),
    "result_text": selected_long["result_text"].fillna("").astype(str).str.strip(),
    "result_num": pd.to_numeric(selected_long["result_num"], errors="coerce"),
    "best_value_text": selected_long["Best Value"].fillna("").astype(str).str.strip(),
    "best_value_num": pd.to_numeric(selected_long["best_value_num"], errors="coerce"),
    "units": selected_long["Units"].fillna("").astype(str).str.strip(),
    "lab_qualifier": selected_long["Lab Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_qualifier": selected_long["Validation Qualifier"].fillna("").astype(str).str.strip().str.upper(),
    "validation_reason_codes": selected_long["Validation Reason Codes"].fillna("").astype(str).str.strip(),
    "detect_flag": selected_long["Detect?"].fillna("").astype(str).str.strip().str.upper(),
    "sample_purpose": selected_long["Sample Purpose"].fillna("").astype(str).str.strip(),
    "sample_usage_code": selected_long["Sample Usage Code"].fillna("").astype(str).str.strip(),
    "usable": selected_long["Usable"].fillna("").astype(str).str.strip(),
    "lab_method": selected_long["Lab Method"].fillna("").astype(str).str.strip(),
    "mdl": selected_long["Method Detection Limit"].fillna("").astype(str).str.strip(),
    "rdl": selected_long["Report Detection Limit"].fillna("").astype(str).str.strip(),
    "state": selected_long["qualifier_state"].fillna("").astype(str).str.strip().str.upper(),
})

syn_long_work = syn_long_work[
    (syn_long_work["sample_event_key"] != "") &
    (syn_long_work["analyte"] != "")
].copy()

syn_long_work["info_rank"] = syn_long_work["state"].map(info_rank_map).fillna(2).astype(int)

final_rows = (
    syn_long_work
    .sort_values(
        [
            "sample_event_key",
            "analyte",
            "info_rank",
            "result_num",
            "best_value_num",
            "sample_date",
            "field_sample_id",
        ],
        ascending=[True, True, False, False, False, False, True],
        na_position="last"
    )
    .drop_duplicates(["sample_event_key", "analyte"], keep="first")
    .copy()
)

kept_analytes_final = sorted(
    final_rows.loc[final_rows["result_num"].notna(), "analyte"].dropna().unique().tolist()
)
final_rows = final_rows[final_rows["analyte"].isin(kept_analytes_final)].copy()

# Output row order: z1-z7 then BHfluid
ordered_locations = [f"R-80_z{i}" for i in range(1, 8)] + [BH_LABEL]

sample_meta = final_rows[["sample_event_key", "location", "sample_date"]].drop_duplicates().copy()
sample_meta["row_sort"] = sample_meta["location"].map({loc: i for i, loc in enumerate(ordered_locations, start=1)}).fillna(999).astype(int)
sample_meta = sample_meta.sort_values(["row_sort", "location", "sample_date"], ascending=[True, True, True], na_position="last")
sample_order = sample_meta["sample_event_key"].tolist()

# ------------------------------------------------------------------
# Rotated numeric append
# ------------------------------------------------------------------
rotated_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

rotated_meta["Sample_Date"] = pd.to_datetime(rotated_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
rotated_meta["Sample_Date"] = rotated_meta["Sample_Date"].fillna("")

for col in wellmeta_cols:
    rotated_meta[col] = ""

rotated_meta = rotated_meta[["sample_event_key", "Location", "Sample_Date"] + wellmeta_cols].copy()

rot_long = final_rows[["sample_event_key", "analyte", "result_num"]].copy()
rot_long["value_num"] = rot_long["result_num"]

rotated_matrix = rot_long.pivot(index="sample_event_key", columns="analyte", values="value_num")
rotated_matrix = rotated_matrix.reindex(index=sample_order, columns=kept_analytes_final)

append_rotated = rotated_meta.set_index("sample_event_key")
append_rotated = append_rotated.reindex(sample_order)
append_rotated = append_rotated.join(rotated_matrix, how="left")
append_rotated = append_rotated.reset_index(drop=True)

syn_rotated_aligned, append_rotated_aligned = align_columns_with_concat(
    syn_rotated,
    append_rotated,
    fill_value_left=pd.NA,
    fill_value_right=pd.NA
)

rotated_out = pd.concat([syn_rotated_aligned, append_rotated_aligned], ignore_index=True)
rotated_out.to_excel(OUT_ROTATED, index=False)

# ------------------------------------------------------------------
# Qualifier append in current flat pre-finalized structure
# ------------------------------------------------------------------
vq_long = final_rows[[
    "sample_event_key",
    "analyte",
    "result_num",
    "state",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detect_flag",
    "best_value_text",
    "best_value_num",
    "usable",
    "filtered",
]].copy()

vq_long = vq_long.rename(columns={
    "result_num": "value",
    "state": "qualifier",
    "detect_flag": "detected",
    "best_value_text": "best_value",
})

subfields = [
    "value",
    "qualifier",
    "validation_qualifier",
    "validation_reason_codes",
    "sample_purpose",
    "sample_usage_code",
    "detected",
    "best_value",
    "best_value_num",
    "usable",
    "filtered",
]

parts = []
for sub in subfields:
    part = vq_long.pivot(index="sample_event_key", columns="analyte", values=sub)
    part = part.reindex(index=sample_order, columns=kept_analytes_final)
    part.columns = [f"{a}__{sub}" for a in part.columns]
    parts.append(part)

vq_matrix = pd.concat(parts, axis=1) if parts else pd.DataFrame(index=sample_order)

vq_meta = sample_meta.rename(columns={
    "location": "Location",
    "sample_date": "Sample_Date",
}).copy()

vq_meta["Sample_Date"] = pd.to_datetime(vq_meta["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
vq_meta["Sample_Date"] = vq_meta["Sample_Date"].fillna("")
vq_meta = vq_meta.set_index("sample_event_key").reindex(sample_order)

append_vq = pd.concat([vq_meta[["Location", "Sample_Date"]], vq_matrix], axis=1).reset_index(drop=True)

syn_vq_aligned, append_vq_aligned = align_columns_with_concat(
    syn_vq,
    append_vq,
    fill_value_left="",
    fill_value_right=""
)

vq_out = pd.concat([syn_vq_aligned, append_vq_aligned], ignore_index=True)
vq_out.to_excel(OUT_VALUE_QUAL, index=False)

# ------------------------------------------------------------------
# Save messages
# ------------------------------------------------------------------
print("Saved:")
print(f" - {OUT_LONG}")
print(f" - {OUT_ROTATED}")
print(f" - {OUT_VALUE_QUAL}")
print("Appended rows:")
for x in ordered_locations:
    print(f" - {x}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_retained_long_plus_treatment_geomean_plus_r80zonal.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_value_qualifier_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
Appended rows:
 - R-80_z1
 - R-80_z2
 - R-80_z3
 - R-80_z4
 - R-80_z5
 - R-80_z6
 - R-80_z7
 - R-80_BHfluid

In [10]:
# Cell _4f.0 — Diagnostic read of WedgeWells_AllFps.csv
#
# Purpose:
# - Inspect field-parameter source structure before building 4f.1
# - Identify columns needed for:
#     * location
#     * date / datetime
#     * parameter name
#     * measured value
#     * units
# - Help accommodate filing/column changes over time
#
# Output:
# - Printed diagnostics only
#
# Notes:
# - No filtering or transformation is finalized here
# - This is just to inspect the source layout

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
FIELD_FILE = WORK_DIR / "WedgeWells_AllFps.csv"

# ------------------------------------------------------------------
# Read source
# ------------------------------------------------------------------
fps_raw = pd.read_csv(FIELD_FILE, dtype=str, low_memory=False)
fps_raw.columns = [str(c).strip() for c in fps_raw.columns]

# ------------------------------------------------------------------
# Basic diagnostics
# ------------------------------------------------------------------
print("File:")
print(FIELD_FILE)
print()

print("Shape:")
print(fps_raw.shape)
print()

print("Columns:")
for i, c in enumerate(fps_raw.columns, start=1):
    print(f"{i:>3}. {c}")
print()

print("Preview:")
display(fps_raw.head(10))

# ------------------------------------------------------------------
# Candidate column scan by name
# ------------------------------------------------------------------
name_flags = ["loc", "well", "station", "date", "time", "param", "analy", "result", "value", "unit", "measure"]

print("\nCandidate columns by keyword:")
for c in fps_raw.columns:
    cl = c.lower()
    if any(flag in cl for flag in name_flags):
        print(f" - {c}")

# ------------------------------------------------------------------
# Show sample non-null values for likely important columns
# ------------------------------------------------------------------
likely_cols = [
    c for c in fps_raw.columns
    if any(flag in c.lower() for flag in ["loc", "well", "station", "date", "time", "param", "analy", "result", "value", "unit"])
]

print("\nSample values from likely columns:")
for c in likely_cols[:20]:
    vals = fps_raw[c].dropna().astype(str).str.strip()
    vals = vals[vals != ""]
    uniq = vals.drop_duplicates().head(10).tolist()
    print(f"\n{c}:")
    for v in uniq:
        print(f"   {v}")

File:
C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\WedgeWells_AllFps.csv

Shape:
(39516, 16)

Columns:
  1. Site ID
  2. Location ID
  3. Field Parameter
  4. Measurement Date
  5. Measurement Time
  6. Field Measurement
  7. Measurement Units
  8. Field Measurement Start Depth
  9. Field Measurement End Depth
 10. Measurement Depth Units
 11. Field Sample ID
 12. Measurement Instrument
 13. Field Measurement Comments
 14. Latitude (Decimal)
 15. Longitude (Decimal)
 16. Field Filtered

Preview:

,Site ID,Location ID,Field Parameter,Measurement Date,Measurement Time,Field Measurement,Measurement Units,Field Measurement Start Depth,Field Measurement End Depth,Measurement Depth Units,Field Sample ID,Measurement Instrument,Field Measurement Comments,Latitude (Decimal),Longitude (Decimal),Field Filtered
0,N3B,CrEX-2,Dissolved Oxygen,9/20/2018,9:51,7.35,mg/L,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
1,N3B,CrEX-2,Oxidation-Reduction Potential,9/20/2018,9:51,323.9,mV,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
2,N3B,CrEX-2,pH,9/20/2018,9:51,7.58,SU,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
3,N3B,CrEX-2,Specific Conductance,9/20/2018,9:51,317.4,uS/cm,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
4,N3B,CrEX-2,Temperature,9/20/2018,9:51,19.385,deg C,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
5,N3B,CrEX-2,Turbidity,9/20/2018,9:51,0.11,NTU,NaN,NaN,NaN,CrEX2-18-159891,NaN,NaN,35.85898059,-106.2607242,NaN
6,N3B,CrEX-2,Dissolved Oxygen,10/24/2018,10:44,7.45,mg/L,NaN,NaN,NaN,CrEX2-19-163801,NaN,NaN,35.85898059,-106.2607242,NaN
7,N3B,CrEX-2,Oxidation-Reduction Potential,10/24/2018,10:44,375.7,MV,NaN,NaN,NaN,CrEX2-19-163801,NaN,NaN,35.85898059,-106.2607242,NaN
8,N3B,CrEX-2,pH,10/24/2018,10:44,7.52,SU,NaN,NaN,NaN,CrEX2-19-163801,NaN,NaN,35.85898059,-106.2607242,NaN
9,N3B,CrEX-2,Specific Conductance,10/24/2018,10:44,333.8,uS/cm,NaN,NaN,NaN,CrEX2-19-163801,NaN,NaN,35.85898059,-106.2607242,NaN

Candidate columns by keyword:
 - Location ID
 - Field Parameter
 - Measurement Date
 - Measurement Time
 - Field Measurement
 - Measurement Units
 - Field Measurement Start Depth
 - Field Measurement End Depth
 - Measurement Depth Units
 - Measurement Instrument
 - Field Measurement Comments

Sample values from likely columns:

Location ID:
   CrEX-2
   CrEX-3
   CrEX-4
   CrIN-1
   CrIN-2
   CRPZ-1
   CRPZ-2A
   CRPZ-3
   CRPZ-4
   CRPZ-5

Field Parameter:
   Dissolved Oxygen
   Oxidation-Reduction Potential
   pH
   Specific Conductance
   Temperature
   Turbidity
   Flow (in gpm)
   Casing Volume

Measurement Date:
   9/20/2018
   10/24/2018
   11/27/2018
   12/18/2018
   1/23/2019
   2/27/2019
   3/21/2019
   4/24/2019
   7/1/2019
   7/2/2019

Measurement Time:
   9:51
   10:44
   9:00
   9:24
   9:23
   9:10
   8:55
   9:15
   10:05
   15:00

Measurement Units:
   mg/L
   mV
   SU
   uS/cm
   deg C
   NTU
   MV
   GPM
   UNITLESS
   #/100ml

Measurement Depth Units:
   ft

In [11]:
# Cell 4f.1 — Build intermediate field-parameter table matched to the full current synoptic row set
#
# Purpose:
# - Read the current rotated synoptic table produced after 4e
# - Use that full table as the target row universe
# - Read WedgeWells_AllFps.csv
# - Keep only the target field parameters:
#     * Dissolved Oxygen
#     * Oxidation-Reduction Potential
#     * pH
#     * Specific Conductance
#     * Temperature
#     * Turbidity
# - Match field parameters to synoptic rows by:
#     * direct Location + Sample_Date for ordinary rows
#     * mapped source location R-80 for R-80_z1 ... R-80_z7 and R-80_BHfluid
# - For each synoptic row + parameter,
#   keep the last field measurement of the day
# - Save intermediate review tables for inspection before final merge
#
# Outputs:
# 1. field_params_intermediate_long.xlsx
# 2. field_params_intermediate_wide.xlsx
# 3. field_params_target_match_diagnostic.xlsx
#
# Notes:
# - This is a staging / review step only
# - No merge back into synoptic outputs yet
# - This version preserves the full target row set from the current synoptic file

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

# Full current synoptic row set after 4e
SYN_ROTATED_FILE = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx"

# Field-parameter source
FIELD_FILE = WORK_DIR / "WedgeWells_AllFps.csv"

# Outputs
OUT_LONG = RESULTS_DIR / "field_params_intermediate_long.xlsx"
OUT_WIDE = RESULTS_DIR / "field_params_intermediate_wide.xlsx"
OUT_COVERAGE = RESULTS_DIR / "field_params_target_match_diagnostic.xlsx"

TARGET_PARAMETERS = [
    "Dissolved Oxygen",
    "Oxidation-Reduction Potential",
    "pH",
    "Specific Conductance",
    "Temperature",
    "Turbidity",
]

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def derive_match_location(loc):
    loc = "" if pd.isna(loc) else str(loc).strip()
    if loc.startswith("R-80_z"):
        return "R-80"
    if loc == "R-80_BHfluid":
        return "R-80"
    return loc

# ------------------------------------------------------------------
# Read full synoptic target table
# ------------------------------------------------------------------
syn = clean_columns(pd.read_excel(SYN_ROTATED_FILE, header=0))

required_syn_cols = ["Location", "Sample_Date"]
missing_syn = [c for c in required_syn_cols if c not in syn.columns]
if missing_syn:
    raise ValueError(f"Synoptic file is missing required columns: {missing_syn}")

targets = syn[["Location", "Sample_Date"]].copy()
targets["Location"] = targets["Location"].fillna("").astype(str).str.strip()
targets["Sample_Date_dt"] = pd.to_datetime(targets["Sample_Date"], errors="coerce")

targets = targets.loc[
    (targets["Location"] != "") &
    (targets["Sample_Date_dt"].notna())
].drop_duplicates().copy()

targets["row_order"] = range(1, len(targets) + 1)
targets["Match_Location"] = targets["Location"].apply(derive_match_location)

# ------------------------------------------------------------------
# Read field-parameter source
# ------------------------------------------------------------------
fps = clean_columns(pd.read_csv(FIELD_FILE, dtype=str, low_memory=False))

required_fps_cols = [
    "Location ID",
    "Field Parameter",
    "Measurement Date",
    "Measurement Time",
    "Field Measurement",
    "Measurement Units",
    "Field Sample ID",
    "Field Filtered",
]

missing_fps = [c for c in required_fps_cols if c not in fps.columns]
if missing_fps:
    raise ValueError(f"Field-parameter file is missing required columns: {missing_fps}")

# ------------------------------------------------------------------
# Normalize field-parameter fields
# ------------------------------------------------------------------
fps["Location"] = fps["Location ID"].fillna("").astype(str).str.strip()
fps["Field Parameter"] = fps["Field Parameter"].fillna("").astype(str).str.strip()
fps["Measurement Date_dt"] = pd.to_datetime(fps["Measurement Date"], errors="coerce")
fps["Measurement Time_clean"] = fps["Measurement Time"].fillna("").astype(str).str.strip()

fps["Measurement Datetime"] = pd.to_datetime(
    fps["Measurement Date"].fillna("").astype(str).str.strip() + " " +
    fps["Measurement Time_clean"],
    errors="coerce"
)

fps.loc[
    fps["Measurement Datetime"].isna() & fps["Measurement Date_dt"].notna(),
    "Measurement Datetime"
] = fps.loc[
    fps["Measurement Datetime"].isna() & fps["Measurement Date_dt"].notna(),
    "Measurement Date_dt"
]

fps["Field Measurement_num"] = pd.to_numeric(
    fps["Field Measurement"].fillna("").astype(str).str.strip().str.replace(",", "", regex=False),
    errors="coerce"
)

# ------------------------------------------------------------------
# Keep only target parameters
# ------------------------------------------------------------------
fps_keep = fps.loc[
    fps["Field Parameter"].isin(TARGET_PARAMETERS)
].copy()

# ------------------------------------------------------------------
# Match field rows to full synoptic target row set
# ------------------------------------------------------------------
fps_keep = fps_keep.rename(columns={"Location": "Match_Location"})

matched = fps_keep.merge(
    targets[["Location", "Sample_Date_dt", "Match_Location", "row_order"]],
    left_on=["Match_Location", "Measurement Date_dt"],
    right_on=["Match_Location", "Sample_Date_dt"],
    how="inner"
)

# ------------------------------------------------------------------
# Keep the last measurement of the day for each target row + parameter
# ------------------------------------------------------------------
matched = matched.sort_values(
    [
        "row_order",
        "Location",
        "Field Parameter",
        "Measurement Datetime",
        "Field Sample ID",
    ],
    ascending=[True, True, True, True, True],
    na_position="last"
).copy()

matched_last = (
    matched
    .drop_duplicates(
        subset=["Location", "Sample_Date_dt", "Field Parameter"],
        keep="last"
    )
    .copy()
)

# ------------------------------------------------------------------
# Build long review table
# ------------------------------------------------------------------
field_long = matched_last[[
    "Location",
    "Sample_Date_dt",
    "Match_Location",
    "Measurement Date_dt",
    "Field Parameter",
    "Field Measurement",
    "Field Measurement_num",
    "Measurement Units",
    "Measurement Time",
    "Measurement Datetime",
    "Field Sample ID",
    "Field Filtered",
    "Measurement Instrument",
    "Field Measurement Comments",
    "Field Measurement Start Depth",
    "Field Measurement End Depth",
    "Measurement Depth Units",
    "row_order",
]].copy()

field_long = field_long.rename(columns={
    "Sample_Date_dt": "Sample_Date",
    "Measurement Date_dt": "Source_Sample_Date",
    "Field Measurement": "Value_raw",
    "Field Measurement_num": "Value_num",
    "Measurement Units": "Units",
    "Measurement Time": "Measurement_Time",
    "Field Sample ID": "Field_Sample_ID",
    "Field Filtered": "Field_Filtered",
    "Measurement Instrument": "Measurement_Instrument",
    "Field Measurement Comments": "Field_Measurement_Comments",
    "Field Measurement Start Depth": "Start_Depth",
    "Field Measurement End Depth": "End_Depth",
    "Measurement Depth Units": "Depth_Units",
})

field_long["Sample_Date"] = pd.to_datetime(field_long["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
field_long["Source_Sample_Date"] = pd.to_datetime(field_long["Source_Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")

field_long = field_long.sort_values(
    ["row_order", "Location", "Sample_Date", "Field Parameter"],
    ascending=[True, True, True, True]
).drop(columns=["row_order"])

# ------------------------------------------------------------------
# Build wide review matrix
# ------------------------------------------------------------------
field_wide = (
    matched_last.pivot(
        index=["Location", "Sample_Date_dt", "Match_Location", "Measurement Date_dt", "row_order"],
        columns="Field Parameter",
        values="Field Measurement_num"
    )
    .reset_index()
    .copy()
)

field_wide = field_wide.rename(columns={
    "Sample_Date_dt": "Sample_Date",
    "Measurement Date_dt": "Source_Sample_Date",
})

field_wide["Sample_Date"] = pd.to_datetime(field_wide["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
field_wide["Source_Sample_Date"] = pd.to_datetime(field_wide["Source_Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")

wide_cols = (
    ["Location", "Sample_Date", "Match_Location", "Source_Sample_Date", "row_order"]
    + [p for p in TARGET_PARAMETERS if p in field_wide.columns]
)
field_wide = field_wide.reindex(columns=wide_cols)
field_wide = field_wide.sort_values(["row_order", "Location", "Sample_Date"], ascending=[True, True, True]).drop(columns=["row_order"])

# ------------------------------------------------------------------
# Build full target-match diagnostic table
# ------------------------------------------------------------------
target_diag = targets[["Location", "Sample_Date_dt", "Match_Location", "row_order"]].copy()
target_diag = target_diag.rename(columns={"Sample_Date_dt": "Sample_Date"})

matched_pairs = matched_last[["Location", "Sample_Date_dt"]].drop_duplicates().copy()
matched_pairs = matched_pairs.rename(columns={"Sample_Date_dt": "Sample_Date"})
matched_pairs["matched_field_params"] = "Y"

target_diag = target_diag.merge(
    matched_pairs,
    on=["Location", "Sample_Date"],
    how="left"
)

target_diag["matched_field_params"] = target_diag["matched_field_params"].fillna("N")
target_diag["Sample_Date"] = pd.to_datetime(target_diag["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")

target_diag = target_diag.sort_values(
    ["matched_field_params", "row_order", "Location", "Sample_Date"],
    ascending=[True, True, True, True]
).drop(columns=["row_order"])

# ------------------------------------------------------------------
# Save outputs
# ------------------------------------------------------------------
field_long.to_excel(OUT_LONG, index=False)
field_wide.to_excel(OUT_WIDE, index=False)
target_diag.to_excel(OUT_COVERAGE, index=False)

# ------------------------------------------------------------------
# Coverage diagnostics
# ------------------------------------------------------------------
total_targets = len(target_diag)
matched_target_count = (target_diag["matched_field_params"] == "Y").sum()
unmatched_target_count = (target_diag["matched_field_params"] == "N").sum()

print("Saved:")
print(f" - {OUT_LONG}")
print(f" - {OUT_WIDE}")
print(f" - {OUT_COVERAGE}")
print()

print(f"Total synoptic target rows: {total_targets:,}")
print(f"Matched field-param target rows: {matched_target_count:,}")
print(f"Unmatched target rows: {unmatched_target_count:,}")
print()

if unmatched_target_count > 0:
    print("Unmatched target rows:")
    print(target_diag.loc[target_diag["matched_field_params"] == "N"].to_string(index=False))
else:
    print("All target rows matched field parameters.")

print()
print("Coverage by parameter:")
for p in TARGET_PARAMETERS:
    if p in field_wide.columns:
        n_nonnull = field_wide[p].notna().sum()
        print(f" - {p}: {n_nonnull:,}")
    else:
        print(f" - {p}: 0")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_intermediate_long.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_intermediate_wide.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_target_match_diagnostic.xlsx

Total synoptic target rows: 107
Matched field-param target rows: 100
Unmatched target rows: 7

Unmatched target rows:
             Location Sample_Date        Match_Location matched_field_params
                 R-39  2026-02-12                  R-39                    N
              R-40 S1  2026-08-08               R-40 S1                    N
            SIMR-3 S1  2026-06-05             SIMR-3 S1                    N
VS-CTUA-2-INF_GeoMean  2025-11-05 VS-CTUA-2-INF_GeoMean                    N
VS-CTUA-6-EFF_GeoMean  2025-12-18 VS-CTUA-6-EFF_GeoMean                    N
              R-80_z2  2026-06-07                  R-80                    N
              R-80_z3  2026-06-08                  R-80                    N

Coverage by parameter:
 - Dissolved Oxygen: 99
 - Oxidation-Reduction Potential: 99
 - pH: 100
 - Specific Conductance: 100
 - Temperature: 100
 - Turbidity: 100

In [12]:
# Cell 4f.1a — Diagnostic read of R80_Zonal_supplemental_Fps.xlsx
#
# Purpose:
# - Inspect the supplemental field-parameter workbook structure
# - Identify sheet names, columns, and sample values
# - Prepare to use this file to fill remaining special-case field-parameter gaps
#
# Output:
# - Printed diagnostics only
#
# Notes:
# - No transformation or merging is performed here
# - This is only to inspect workbook structure and field naming

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
SUPP_FILE = WORK_DIR / "R80_Zonal_supplemental_Fps.xlsx"

# ------------------------------------------------------------------
# Inspect workbook
# ------------------------------------------------------------------
xls = pd.ExcelFile(SUPP_FILE)

print("File:")
print(SUPP_FILE)
print()

print("Sheet names:")
for i, s in enumerate(xls.sheet_names, start=1):
    print(f"{i:>2}. {s}")
print()

# ------------------------------------------------------------------
# Read and inspect each sheet
# ------------------------------------------------------------------
for sheet in xls.sheet_names:
    print("=" * 80)
    print(f"Sheet: {sheet}")
    print("=" * 80)

    df = pd.read_excel(SUPP_FILE, sheet_name=sheet, dtype=str)
    df.columns = [str(c).strip() for c in df.columns]

    print("Shape:")
    print(df.shape)
    print()

    print("Columns:")
    for i, c in enumerate(df.columns, start=1):
        print(f"{i:>3}. {c}")
    print()

    print("Preview:")
    display(df.head(10))

    name_flags = [
        "loc", "well", "station",
        "date", "time",
        "param", "field",
        "result", "value", "measure",
        "unit"
    ]

    likely_cols = [
        c for c in df.columns
        if any(flag in c.lower() for flag in name_flags)
    ]

    print("Candidate columns by keyword:")
    for c in likely_cols:
        print(f" - {c}")
    print()

    print("Sample values from likely columns:")
    for c in likely_cols[:20]:
        vals = df[c].fillna("").astype(str).str.strip()
        vals = vals[vals != ""]
        uniq = vals.drop_duplicates().head(10).tolist()

        print(f"\n{c}:")
        for v in uniq:
            print(f"   {v}")
    print()

File:
C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\R80_Zonal_supplemental_Fps.xlsx

Sheet names:
 1. Sheet1

================================================================================
Sheet: Sheet1
================================================================================
Shape:
(2, 7)

Columns:
  1. Zone
  2. pH
  3. Temp
  4. SpC
  5. DO
  6. Turb
  7. ORP

Preview:

  Zone    pH  Temp    SpC    DO  Turb   ORP
0    2  8.02  20.9  146.3  9.99  20.9  13.4
1    3  7.89  25.1  153.7  6.77  2.58    66

Candidate columns by keyword:

Sample values from likely columns:

In [19]:
# Cell 4f.1b — Apply supplemental and fallback addenda to field-parameter intermediate tables
#
# Purpose:
# - Rebuild the three intermediate field-parameter outputs after applying
#   special-case addenda for rows not covered by the primary
#   WedgeWells_AllFps.csv match
#
# Base inputs:
# - field-parameter matches derived from WedgeWells_AllFps.csv
# - current synoptic row universe from:
#     synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
#
# Addenda rules:
# 1) R-80_z2 and R-80_z3:
#    - populate from R80_Zonal_supplemental_Fps.xlsx
#    - Zone 2 -> R-80_z2
#    - Zone 3 -> R-80_z3
#
# 2) VS-CTUA-6-EFF_GeoMean:
#    - populate using geometric mean by parameter from all available
#      VS-CTUA-6-EFF field-data dates
#
# 3) SIMR-3 S1:
#    - if unmatched, use fallback data from 2026-06-02 or 2026-06-03
#    - choose the latest available event in that fallback window
#    - then keep the last measurement of that day per parameter
#
# 4) R-40 S1:
#    - if unmatched, use fallback data from February 2024
#    - choose the latest available event in that month
#    - then keep the last measurement of that day per parameter
#
# 5) R-39:
#    - if unmatched, use fallback data from January 2025
#    - choose the latest available event in that month
#    - then keep the last measurement of that day per parameter
#
# 6) VS-CTUA-2-INF_GeoMean:
#    - leave unmatched
#
# Outputs:
# 1. field_params_intermediate_long.xlsx
# 2. field_params_intermediate_wide.xlsx
# 3. field_params_target_match_diagnostic.xlsx
#
# Notes:
# - This remains an intermediate staging step
# - No merge back into final synoptic tables yet
# - Rows populated via addenda are marked with source_flag for traceability

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

SYN_ROTATED_FILE = RESULTS_DIR / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx"
FIELD_FILE = WORK_DIR / "WedgeWells_AllFps.csv"
SUPP_FILE = WORK_DIR / "R80_Zonal_supplemental_Fps.xlsx"

OUT_LONG = RESULTS_DIR / "field_params_intermediate_long.xlsx"
OUT_WIDE = RESULTS_DIR / "field_params_intermediate_wide.xlsx"
OUT_COVERAGE = RESULTS_DIR / "field_params_target_match_diagnostic.xlsx"

TARGET_PARAMETERS = [
    "Dissolved Oxygen",
    "Oxidation-Reduction Potential",
    "pH",
    "Specific Conductance",
    "Temperature",
    "Turbidity",
]

SUPP_PARAM_MAP = {
    "pH": "pH",
    "Temp": "Temperature",
    "SpC": "Specific Conductance",
    "DO": "Dissolved Oxygen",
    "Turb": "Turbidity",
    "ORP": "Oxidation-Reduction Potential",
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def derive_match_location(loc):
    loc = "" if pd.isna(loc) else str(loc).strip()
    if loc.startswith("R-80_z"):
        return "R-80"
    if loc == "R-80_BHfluid":
        return "R-80"
    return loc

def geometric_mean(series):
    s = pd.to_numeric(series, errors="coerce")
    s = s[s.notna()]
    s = s[s > 0]
    if len(s) == 0:
        return np.nan
    return float(np.exp(np.mean(np.log(s))))

def build_last_of_day(df_in):
    if df_in.empty:
        return df_in.copy()

    df = df_in.sort_values(
        ["row_order", "Location", "Field Parameter", "Measurement Datetime", "Field Sample ID"],
        ascending=[True, True, True, True, True],
        na_position="last"
    ).copy()

    df = (
        df
        .drop_duplicates(
            subset=["Location", "Sample_Date_dt", "Field Parameter"],
            keep="last"
        )
        .copy()
    )
    return df

def pick_latest_window_event(fps_df, match_location, window_start, window_end):
    sub = fps_df.loc[
        (fps_df["Location"] == match_location) &
        (fps_df["Measurement Date_dt"] >= pd.Timestamp(window_start)) &
        (fps_df["Measurement Date_dt"] <= pd.Timestamp(window_end)) &
        (fps_df["Field Parameter"].isin(TARGET_PARAMETERS))
    ].copy()

    if sub.empty:
        return sub

    latest_date = sub["Measurement Date_dt"].max()
    sub = sub.loc[sub["Measurement Date_dt"] == latest_date].copy()
    return sub

def first_nonblank(series):
    vals = series.fillna("").astype(str).str.strip()
    vals = vals[vals != ""]
    if len(vals) == 0:
        return ""
    return vals.iloc[0]

# ------------------------------------------------------------------
# Read full synoptic target table
# ------------------------------------------------------------------
syn = clean_columns(pd.read_excel(SYN_ROTATED_FILE, header=0))

required_syn_cols = ["Location", "Sample_Date"]
missing_syn = [c for c in required_syn_cols if c not in syn.columns]
if missing_syn:
    raise ValueError(f"Synoptic file is missing required columns: {missing_syn}")

targets = syn[["Location", "Sample_Date"]].copy()
targets["Location"] = targets["Location"].fillna("").astype(str).str.strip()
targets["Sample_Date_dt"] = pd.to_datetime(targets["Sample_Date"], errors="coerce")

targets = targets.loc[
    (targets["Location"] != "") &
    (targets["Sample_Date_dt"].notna())
].drop_duplicates().copy()

targets["row_order"] = range(1, len(targets) + 1)
targets["Match_Location"] = targets["Location"].apply(derive_match_location)

# ------------------------------------------------------------------
# Read primary field-parameter source
# ------------------------------------------------------------------
fps = clean_columns(pd.read_csv(FIELD_FILE, dtype=str, low_memory=False))

required_fps_cols = [
    "Location ID",
    "Field Parameter",
    "Measurement Date",
    "Measurement Time",
    "Field Measurement",
    "Measurement Units",
    "Field Sample ID",
    "Field Filtered",
]

missing_fps = [c for c in required_fps_cols if c not in fps.columns]
if missing_fps:
    raise ValueError(f"Field-parameter file is missing required columns: {missing_fps}")

fps["Location"] = fps["Location ID"].fillna("").astype(str).str.strip()
fps["Field Parameter"] = fps["Field Parameter"].fillna("").astype(str).str.strip()
fps["Measurement Date_dt"] = pd.to_datetime(fps["Measurement Date"], errors="coerce")
fps["Measurement Time_clean"] = fps["Measurement Time"].fillna("").astype(str).str.strip()

fps["Measurement Datetime"] = pd.to_datetime(
    fps["Measurement Date"].fillna("").astype(str).str.strip() + " " +
    fps["Measurement Time_clean"],
    errors="coerce"
)

fps.loc[
    fps["Measurement Datetime"].isna() & fps["Measurement Date_dt"].notna(),
    "Measurement Datetime"
] = fps.loc[
    fps["Measurement Datetime"].isna() & fps["Measurement Date_dt"].notna(),
    "Measurement Date_dt"
]

fps["Field Measurement_num"] = pd.to_numeric(
    fps["Field Measurement"].fillna("").astype(str).str.strip().str.replace(",", "", regex=False),
    errors="coerce"
)

fps_keep = fps.loc[fps["Field Parameter"].isin(TARGET_PARAMETERS)].copy()

# ------------------------------------------------------------------
# Primary direct matching to synoptic targets
# ------------------------------------------------------------------
fps_match = fps_keep.rename(columns={"Location": "Match_Location"}).copy()

matched_primary = fps_match.merge(
    targets[["Location", "Sample_Date_dt", "Match_Location", "row_order"]],
    left_on=["Match_Location", "Measurement Date_dt"],
    right_on=["Match_Location", "Sample_Date_dt"],
    how="inner"
)

matched_primary["source_flag"] = "primary_direct"
matched_primary = build_last_of_day(matched_primary)

# ------------------------------------------------------------------
# Identify still-unmatched targets after primary matching
# ------------------------------------------------------------------
matched_primary_pairs = matched_primary[["Location", "Sample_Date_dt"]].drop_duplicates().copy()
matched_primary_pairs["matched_primary"] = "Y"

target_status = targets.merge(
    matched_primary_pairs,
    on=["Location", "Sample_Date_dt"],
    how="left"
)
target_status["matched_primary"] = target_status["matched_primary"].fillna("N")

unmatched_targets = target_status.loc[target_status["matched_primary"] == "N"].copy()

# ------------------------------------------------------------------
# Supplemental R-80 zonal exceptions from workbook
# ------------------------------------------------------------------
supp = clean_columns(pd.read_excel(SUPP_FILE, sheet_name=0, dtype=str))

required_supp_cols = ["Zone"] + list(SUPP_PARAM_MAP.keys())
missing_supp = [c for c in required_supp_cols if c not in supp.columns]
if missing_supp:
    raise ValueError(f"Supplemental FPS workbook is missing required columns: {missing_supp}")

supp_long = supp.melt(
    id_vars=["Zone"],
    value_vars=list(SUPP_PARAM_MAP.keys()),
    var_name="supp_param",
    value_name="Field Measurement"
).copy()

supp_long["Zone"] = supp_long["Zone"].fillna("").astype(str).str.strip()
supp_long["Location"] = "R-80_z" + supp_long["Zone"]
supp_long["Field Parameter"] = supp_long["supp_param"].map(SUPP_PARAM_MAP)
supp_long["Field Measurement_num"] = pd.to_numeric(
    supp_long["Field Measurement"].fillna("").astype(str).str.strip(),
    errors="coerce"
)
supp_long["Measurement Units"] = ""
supp_long["Measurement Time"] = ""
supp_long["Measurement Datetime"] = pd.NaT
supp_long["Field Sample ID"] = ""
supp_long["Field Filtered"] = ""
supp_long["Measurement Instrument"] = ""
supp_long["Field Measurement Comments"] = "Populated from R80_Zonal_supplemental_Fps.xlsx"
supp_long["Field Measurement Start Depth"] = ""
supp_long["Field Measurement End Depth"] = ""
supp_long["Measurement Depth Units"] = ""
supp_long["source_flag"] = "supplemental_r80_zonal"

supp_targets = unmatched_targets.loc[
    unmatched_targets["Location"].isin(["R-80_z2", "R-80_z3"])
].copy()

supp_matched = supp_targets.merge(
    supp_long,
    on="Location",
    how="left"
)

supp_matched["Measurement Date_dt"] = supp_matched["Sample_Date_dt"]
supp_matched["Match_Location"] = "R-80"

supp_matched = supp_matched[[
    "Location",
    "Sample_Date_dt",
    "Match_Location",
    "row_order",
    "Field Parameter",
    "Field Measurement",
    "Field Measurement_num",
    "Measurement Units",
    "Measurement Time",
    "Measurement Datetime",
    "Field Sample ID",
    "Field Filtered",
    "Measurement Instrument",
    "Field Measurement Comments",
    "Field Measurement Start Depth",
    "Field Measurement End Depth",
    "Measurement Depth Units",
    "Measurement Date_dt",
    "source_flag",
]].copy()

# ------------------------------------------------------------------
# Geometric mean for VS-CTUA-6-EFF_GeoMean from all VS-CTUA-6-EFF dates
# ------------------------------------------------------------------
geom_targets = unmatched_targets.loc[
    unmatched_targets["Location"] == "VS-CTUA-6-EFF_GeoMean"
].copy()

geom_source = fps_keep.loc[
    fps_keep["Location"] == "VS-CTUA-6-EFF"
].copy()

geom_rows = []

if not geom_targets.empty and not geom_source.empty:
    for param in TARGET_PARAMETERS:
        sp = geom_source.loc[
            geom_source["Field Parameter"] == param
        ].copy()

        if sp.empty:
            continue

        gm = geometric_mean(sp["Field Measurement_num"])
        if pd.isna(gm):
            continue

        units = first_nonblank(sp["Measurement Units"])

        source_dates = (
            sp["Measurement Date_dt"]
            .dropna()
            .drop_duplicates()
            .sort_values()
        )

        if len(source_dates) > 0:
            source_date_text = (
                f"{source_dates.min().strftime('%Y-%m-%d')} to "
                f"{source_dates.max().strftime('%Y-%m-%d')}"
            )
        else:
            source_date_text = "all available dates"

        for _, trow in geom_targets.iterrows():
            geom_rows.append({
                "Location": trow["Location"],
                "Sample_Date_dt": trow["Sample_Date_dt"],
                "Match_Location": "VS-CTUA-6-EFF",
                "row_order": trow["row_order"],
                "Field Parameter": param,
                "Field Measurement": str(gm),
                "Field Measurement_num": gm,
                "Measurement Units": units,
                "Measurement Time": "",
                "Measurement Datetime": pd.NaT,
                "Field Sample ID": "",
                "Field Filtered": "",
                "Measurement Instrument": "",
                "Field Measurement Comments": (
                    f"Geometric mean from all available VS-CTUA-6-EFF field data dates ({source_date_text})"
                ),
                "Field Measurement Start Depth": "",
                "Field Measurement End Depth": "",
                "Measurement Depth Units": "",
                "Measurement Date_dt": pd.NaT,
                "source_flag": "geomean_vs_ctua6eff",
            })

geom_matched = pd.DataFrame(geom_rows)

# ------------------------------------------------------------------
# Fallback replacements for SIMR-3 S1, R-40 S1, R-39
# ------------------------------------------------------------------
fallback_specs = [
    {
        "target_location": "SIMR-3 S1",
        "match_location": "SIMR-3 S1",
        "window_start": "2026-06-02",
        "window_end": "2026-06-03",
        "source_flag": "fallback_simr3s1_2026-06-02_to_2026-06-03",
        "comment": "Fallback using latest available field event from 2026-06-02 to 2026-06-03",
    },
    {
        "target_location": "R-40 S1",
        "match_location": "R-40 S1",
        "window_start": "2024-02-01",
        "window_end": "2024-02-29",
        "source_flag": "fallback_r40s1_2024-02",
        "comment": "Fallback using latest available field event from February 2024",
    },
    {
        "target_location": "R-39",
        "match_location": "R-39",
        "window_start": "2025-01-01",
        "window_end": "2025-01-31",
        "source_flag": "fallback_r39_2025-01",
        "comment": "Fallback using latest available field event from January 2025",
    },
]

fallback_rows = []

for spec in fallback_specs:
    tsub = unmatched_targets.loc[
        unmatched_targets["Location"] == spec["target_location"]
    ].copy()

    if tsub.empty:
        continue

    src = pick_latest_window_event(
        fps_df=fps_keep,
        match_location=spec["match_location"],
        window_start=spec["window_start"],
        window_end=spec["window_end"],
    )

    if src.empty:
        continue

    src = src.sort_values(
        ["Measurement Date_dt", "Measurement Datetime", "Field Sample ID"],
        ascending=[True, True, True],
        na_position="last"
    ).copy()

    src_last = (
        src
        .drop_duplicates(subset=["Measurement Date_dt", "Field Parameter"], keep="last")
        .copy()
    )

    for _, trow in tsub.iterrows():
        for _, srow in src_last.iterrows():
            fallback_rows.append({
                "Location": trow["Location"],
                "Sample_Date_dt": trow["Sample_Date_dt"],
                "Match_Location": spec["match_location"],
                "row_order": trow["row_order"],
                "Field Parameter": srow["Field Parameter"],
                "Field Measurement": srow["Field Measurement"],
                "Field Measurement_num": srow["Field Measurement_num"],
                "Measurement Units": srow["Measurement Units"],
                "Measurement Time": srow["Measurement Time"],
                "Measurement Datetime": srow["Measurement Datetime"],
                "Field Sample ID": srow["Field Sample ID"],
                "Field Filtered": srow["Field Filtered"],
                "Measurement Instrument": srow["Measurement Instrument"],
                "Field Measurement Comments": spec["comment"],
                "Field Measurement Start Depth": srow["Field Measurement Start Depth"],
                "Field Measurement End Depth": srow["Field Measurement End Depth"],
                "Measurement Depth Units": srow["Measurement Depth Units"],
                "Measurement Date_dt": srow["Measurement Date_dt"],
                "source_flag": spec["source_flag"],
            })

fallback_matched = pd.DataFrame(fallback_rows)

# ------------------------------------------------------------------
# Combine primary + addenda rows
# ------------------------------------------------------------------
frames = [matched_primary]

for extra in [supp_matched, geom_matched, fallback_matched]:
    if extra is not None and not extra.empty:
        frames.append(extra)

all_matched = pd.concat(frames, ignore_index=True, sort=False)

source_priority = {
    "primary_direct": 1,
    "supplemental_r80_zonal": 2,
    "geomean_vs_ctua6eff": 3,
    "fallback_simr3s1_2026-06-02_to_2026-06-03": 4,
    "fallback_r40s1_2024-02": 5,
    "fallback_r39_2025-01": 6,
}
all_matched["source_priority"] = all_matched["source_flag"].map(source_priority).fillna(999).astype(int)

all_matched = all_matched.sort_values(
    ["row_order", "Location", "Field Parameter", "source_priority", "Measurement Datetime"],
    ascending=[True, True, True, True, True],
    na_position="last"
).copy()

all_matched = (
    all_matched
    .drop_duplicates(subset=["Location", "Sample_Date_dt", "Field Parameter"], keep="first")
    .copy()
)

# ------------------------------------------------------------------
# Build final long intermediate table
# ------------------------------------------------------------------
field_long = all_matched[[
    "Location",
    "Sample_Date_dt",
    "Match_Location",
    "Measurement Date_dt",
    "Field Parameter",
    "Field Measurement",
    "Field Measurement_num",
    "Measurement Units",
    "Measurement Time",
    "Measurement Datetime",
    "Field Sample ID",
    "Field Filtered",
    "Measurement Instrument",
    "Field Measurement Comments",
    "Field Measurement Start Depth",
    "Field Measurement End Depth",
    "Measurement Depth Units",
    "source_flag",
    "row_order",
]].copy()

field_long = field_long.rename(columns={
    "Sample_Date_dt": "Sample_Date",
    "Measurement Date_dt": "Source_Sample_Date",
    "Field Measurement": "Value_raw",
    "Field Measurement_num": "Value_num",
    "Measurement Units": "Units",
    "Measurement Time": "Measurement_Time",
    "Field Sample ID": "Field_Sample_ID",
    "Field Filtered": "Field_Filtered",
    "Measurement Instrument": "Measurement_Instrument",
    "Field Measurement Comments": "Field_Measurement_Comments",
    "Field Measurement Start Depth": "Start_Depth",
    "Field Measurement End Depth": "End_Depth",
    "Measurement Depth Units": "Depth_Units",
})

field_long["Sample_Date"] = pd.to_datetime(field_long["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
field_long["Source_Sample_Date"] = pd.to_datetime(field_long["Source_Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")

field_long = (
    field_long
    .sort_values(["row_order", "Location", "Sample_Date", "Field Parameter"], ascending=[True, True, True, True])
    .drop(columns=["row_order"])
    .copy()
)

# ------------------------------------------------------------------
# Build final wide intermediate table
# ------------------------------------------------------------------
field_wide = (
    all_matched.pivot(
        index=["Location", "Sample_Date_dt", "Match_Location", "row_order"],
        columns="Field Parameter",
        values="Field Measurement_num"
    )
    .reset_index()
    .copy()
)

source_dates = (
    all_matched[["Location", "Sample_Date_dt", "Measurement Date_dt"]]
    .drop_duplicates()
    .groupby(["Location", "Sample_Date_dt"], as_index=False)["Measurement Date_dt"]
    .first()
)

field_wide = field_wide.merge(
    source_dates,
    on=["Location", "Sample_Date_dt"],
    how="left"
)

field_wide = field_wide.rename(columns={
    "Sample_Date_dt": "Sample_Date",
    "Measurement Date_dt": "Source_Sample_Date",
})

field_wide["Sample_Date"] = pd.to_datetime(field_wide["Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")
field_wide["Source_Sample_Date"] = pd.to_datetime(field_wide["Source_Sample_Date"], errors="coerce").dt.strftime("%Y-%m-%d")

wide_cols = (
    ["Location", "Sample_Date", "Match_Location", "Source_Sample_Date", "row_order"]
    + [p for p in TARGET_PARAMETERS if p in field_wide.columns]
)
field_wide = field_wide.reindex(columns=wide_cols)

field_wide = (
    field_wide
    .sort_values(["row_order", "Location", "Sample_Date"], ascending=[True, True, True])
    .drop(columns=["row_order"])
    .copy()
)

# ------------------------------------------------------------------
# Build final diagnostic table
# ------------------------------------------------------------------
matched_pairs = all_matched[["Location", "Sample_Date_dt"]].drop_duplicates().copy()
matched_pairs["matched_field_params"] = "Y"

target_diag = targets.merge(
    matched_pairs,
    on=["Location", "Sample_Date_dt"],
    how="left"
)

target_diag["matched_field_params"] = target_diag["matched_field_params"].fillna("N")
target_diag["Sample_Date"] = pd.to_datetime(target_diag["Sample_Date_dt"], errors="coerce").dt.strftime("%Y-%m-%d")

target_diag = target_diag[[
    "Location",
    "Sample_Date",
    "Match_Location",
    "matched_field_params",
    "row_order",
]].copy()

target_diag = (
    target_diag
    .sort_values(["matched_field_params", "row_order", "Location", "Sample_Date"], ascending=[True, True, True, True])
    .drop(columns=["row_order"])
    .copy()
)

# ------------------------------------------------------------------
# Save outputs
# ------------------------------------------------------------------
field_long.to_excel(OUT_LONG, index=False)
field_wide.to_excel(OUT_WIDE, index=False)
target_diag.to_excel(OUT_COVERAGE, index=False)

# ------------------------------------------------------------------
# Coverage diagnostics
# ------------------------------------------------------------------
total_targets = len(target_diag)
matched_target_count = (target_diag["matched_field_params"] == "Y").sum()
unmatched_target_count = (target_diag["matched_field_params"] == "N").sum()

print("Saved:")
print(f" - {OUT_LONG}")
print(f" - {OUT_WIDE}")
print(f" - {OUT_COVERAGE}")
print()

print(f"Total synoptic target rows: {total_targets:,}")
print(f"Matched field-param target rows: {matched_target_count:,}")
print(f"Unmatched target rows: {unmatched_target_count:,}")
print()

if unmatched_target_count > 0:
    print("Unmatched target rows:")
    print(target_diag.loc[target_diag["matched_field_params"] == "N"].to_string(index=False))
else:
    print("All target rows matched field parameters.")

print()
print("Coverage by parameter:")
for p in TARGET_PARAMETERS:
    if p in field_wide.columns:
        n_nonnull = field_wide[p].notna().sum()
        print(f" - {p}: {n_nonnull:,}")
    else:
        print(f" - {p}: 0")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_intermediate_long.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_intermediate_wide.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_target_match_diagnostic.xlsx

Total synoptic target rows: 107
Matched field-param target rows: 106
Unmatched target rows: 1

Unmatched target rows:
             Location Sample_Date        Match_Location matched_field_params
VS-CTUA-2-INF_GeoMean  2025-11-05 VS-CTUA-2-INF_GeoMean                    N

Coverage by parameter:
 - Dissolved Oxygen: 105
 - Oxidation-Reduction Potential: 105
 - pH: 106
 - Specific Conductance: 106
 - Temperature: 106
 - Turbidity: 106

In [23]:
# Cell 5 — Assemble full synoptic + field-parameter matrix, then create
# scenario-based PCA/clustering sensitivity-input slices
#
# Purpose:
# - Read the full synoptic numeric matrix, including appended treatment GeoMean
#   rows and R-80 zonal / borehole-fluid rows.
# - Read the field-parameter intermediate wide table produced in Cell 4f.1b.
# - Left-join field parameters onto the full synoptic matrix by Location + Sample_Date.
# - Preserve all primary synoptic rows, including intentionally unresolved cases
#   such as VS-CTUA-2-INF_GeoMean.
# - Preserve laboratory-derived conductivity from the primary matrix as Lab_Cond.
# - Preserve field Specific Conductance from the field-parameter matrix.
# - Calculate Field_Cond_Lab_Cond_Ratio = Specific Conductance / Lab_Cond.
# - Collapse multiple retained sample-event rows to one row per location.
# - Average duplicate numeric analyte measurements within each location.
# - Preserve singleton analytes as-is.
# - Preserve location metadata and the earliest retained Sample_Date for each location.
# - Apply named, reproducible scenario rules before creating PCA-ready matrices.
# - Fold down sparse analyte columns after scenario-specific column slicing.
# - Apply a light final row-completeness screen after scenario-specific column slicing.
# - Export scenario-specific matrices plus analyte and row accounting.
#
# Possible scenario rule functions / user controllables:
# - name:
#     Required scenario label used in output filenames; e.g., "SetOne".
#
# - description:
#     Free-text explanation of the sensitivity/stability scenario.
#
# - column_drop:
#     List of analyte columns to remove before sparse-column and row-completeness rules.
#     Aliases are accepted:
#         "ORP"  -> "Oxidation-Reduction Potential"
#         "DO"   -> "Dissolved Oxygen"
#         "Temp" -> "Temperature"
#         "SpC"  -> "Specific Conductance"
#         "Turb" -> "Turbidity"
#
# - column_keep:
#     Optional list of analytes to retain as the only eligible analytes.
#     Leave as [] to allow all non-dropped analytes.
#
# - row_keep_locations / row_drop_locations:
#     Optional lists of Location_ID values to include or exclude before collapse.
#
# - row_keep_categories / row_drop_categories:
#     Optional lists of Cat values to include or exclude before collapse.
#
# - row_keep_location_types / row_drop_location_types:
#     Optional lists of Location_Type values to include or exclude before collapse.
#
# - required_nonmissing_columns:
#     Optional list of analytes that must be populated for a collapsed location
#     to remain in the PCA input for that scenario.
#
# - min_row_present_count:
#     Scenario-specific override for the minimum number of retained analytes
#     required for a location to remain in PCA input.
#     Use None to inherit MIN_ROW_PRESENT_COUNT_FINAL.
#
# - min_col_present_count / min_col_present_frac:
#     Scenario-specific overrides for sparse-column support thresholds.
#     Use None to inherit the global defaults below.
#
# Current scenario:
# - SetOne:
#     Drop Dissolved Oxygen and Oxidation-Reduction Potential / ORP.
#
# To add a second scenario later, add another dictionary to SCENARIOS:
#
#     {
#         "name": "SetTwo",
#         "description": "Drop Dissolved Oxygen only.",
#         "column_drop": ["Dissolved Oxygen"],
#     },
#
# Important logic note:
# - A scenario column drop does NOT globally delete that analyte from source files.
# - It removes that analyte only from that scenario's matrix.
# - After scenario column slicing, locations are retained only when they pass:
#     (1) any explicit required_nonmissing_columns rule, and
#     (2) the final retained-analyte completeness rule.
# - Thus, if a future scenario drops Dissolved Oxygen while R-80_BHfluid has
#   insufficient remaining analytes because ORP is also missing, it can be
#   removed by the final row-completeness rule rather than forcing removal of
#   ORP from every other location.
#
# Inputs:
# 1. synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
# 2. field_params_intermediate_wide.xlsx
#
# Outputs, for each scenario:
# 1. synoptic_location_collapsed_full_matrix_<Scenario>.xlsx
# 2. pca_input_matrix_<Scenario>.xlsx
# 3. synoptic_analyte_keep_drop_<Scenario>.csv
# 4. pca_row_accounting_<Scenario>.csv
#
# Notes:
# - This cell prepares deterministic scenario-based sensitivity/stability inputs.
# - It does not itself run PCA, clustering, bootstrapping, or resampling.

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

# Primary input: full synoptic analyte matrix and complete row universe.
PRIMARY_INPUT_FILE = (
    RESULTS_DIR
    / "synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx"
)

# Additive field-parameter staging output from Cell 4f.1b.
FIELD_PARAMS_INPUT_FILE = RESULTS_DIR / "field_params_intermediate_wide.xlsx"

# Default sparse-column retention settings.
MIN_COL_PRESENT_COUNT = 3
MIN_COL_PRESENT_FRAC = 0.05

# Default final row screen after scenario-specific column slicing.
MIN_ROW_PRESENT_COUNT_FINAL = 2

# ------------------------------------------------------------------
# Scenario configuration
# ------------------------------------------------------------------
SCENARIOS = [
    {
        "name": "SetOne",
        "description": (
            "Drop Dissolved Oxygen and Oxidation-Reduction Potential before "
            "analyte-support and row-completeness screening."
        ),

        # Explicit analyte exclusion for this scenario.
        "column_drop": [
            "Dissolved Oxygen",
            "ORP",  # Alias resolves to Oxidation-Reduction Potential.
        ],

        # Optional analyte whitelist. [] means all non-dropped analytes are eligible.
        "column_keep": [],

        # Optional source-row filters applied before location-level collapse.
        "row_keep_locations": [],
        "row_drop_locations": [],
        "row_keep_categories": [],
        "row_drop_categories": [],
        "row_keep_location_types": [],
        "row_drop_location_types": [],

        # Optional requirements after collapse and scenario column slicing.
        "required_nonmissing_columns": [],

        # Scenario-specific threshold overrides.
        # None means inherit the global defaults defined above.
        "min_row_present_count": None,
        "min_col_present_count": None,
        "min_col_present_frac": None,
    },

    # Example future scenario:
    #
    # {
    #     "name": "SetTwo",
    #     "description": (
    #         "Drop Dissolved Oxygen only. Rows with too few remaining "
    #         "analytes will be removed by the final row-completeness screen."
    #     ),
    #     "column_drop": ["Dissolved Oxygen"],
    #     "column_keep": [],
    #     "row_keep_locations": [],
    #     "row_drop_locations": [],
    #     "row_keep_categories": [],
    #     "row_drop_categories": [],
    #     "row_keep_location_types": [],
    #     "row_drop_location_types": [],
    #     "required_nonmissing_columns": [],
    #     "min_row_present_count": None,
    #     "min_col_present_count": None,
    #     "min_col_present_frac": None,
    # },
]

# ------------------------------------------------------------------
# Column aliases allowed in scenario controls
# ------------------------------------------------------------------
COLUMN_ALIASES = {
    "orp": "Oxidation-Reduction Potential",
    "oxidation reduction potential": "Oxidation-Reduction Potential",
    "do": "Dissolved Oxygen",
    "dissolved oxygen": "Dissolved Oxygen",
    "temp": "Temperature",
    "temperature": "Temperature",
    "spc": "Specific Conductance",
    "specific conductance": "Specific Conductance",
    "lab cond": "Lab_Cond",
    "lab_cond": "Lab_Cond",
    "field cond lab cond ratio": "Field_Cond_Lab_Cond_Ratio",
    "field_cond_lab_cond_ratio": "Field_Cond_Lab_Cond_Ratio",
    "turb": "Turbidity",
    "turbidity": "Turbidity",
    "ph": "pH",
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    """Return a copy with surrounding whitespace removed from column names."""
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df


def normalize_text(value):
    """Normalize text values for exact-match filters and join-key preparation."""
    if pd.isna(value):
        return ""
    return str(value).strip()


def first_nonblank(series):
    """Return the first nonblank value in a Series, or blank text if none exists."""
    values = series.fillna("").astype(str).str.strip()
    values = values.loc[values != ""]
    return values.iloc[0] if len(values) else ""


def resolve_analyte_names(requested_names, available_analytes):
    """
    Resolve requested scenario analyte names against available analyte columns.

    Resolution order:
    1. Exact column-name match.
    2. Case-insensitive column-name match.
    3. Alias lookup, then case-insensitive column-name match.

    Returns:
    - resolved: valid, de-duplicated analyte names
    - unresolved: requested names that could not be resolved
    """
    available_lookup = {
        str(col).strip().lower(): col
        for col in available_analytes
    }

    resolved = []
    unresolved = []

    for raw_name in requested_names or []:
        requested = str(raw_name).strip()

        if requested in available_analytes:
            resolved_name = requested
        else:
            requested_key = requested.lower()
            canonical_name = COLUMN_ALIASES.get(requested_key, requested)
            canonical_key = str(canonical_name).strip().lower()

            if canonical_key in available_lookup:
                resolved_name = available_lookup[canonical_key]
            else:
                unresolved.append(requested)
                continue

        if resolved_name not in resolved:
            resolved.append(resolved_name)

    return resolved, unresolved


def apply_source_row_filters(source_df, scenario):
    """
    Apply optional row filters before location-level collapse.

    Returns:
    - filtered dataframe
    - source-row accounting dictionary
    """
    df_out = source_df.copy()

    counts = {
        "input_rows": len(df_out),
        "after_row_keep_locations": None,
        "after_row_drop_locations": None,
        "after_row_keep_categories": None,
        "after_row_drop_categories": None,
        "after_row_keep_location_types": None,
        "after_row_drop_location_types": None,
    }

    if scenario.get("row_keep_locations"):
        keep_values = {
            normalize_text(v)
            for v in scenario["row_keep_locations"]
        }
        df_out = df_out.loc[
            df_out["Location_ID"].isin(keep_values)
        ].copy()
    counts["after_row_keep_locations"] = len(df_out)

    if scenario.get("row_drop_locations"):
        drop_values = {
            normalize_text(v)
            for v in scenario["row_drop_locations"]
        }
        df_out = df_out.loc[
            ~df_out["Location_ID"].isin(drop_values)
        ].copy()
    counts["after_row_drop_locations"] = len(df_out)

    if scenario.get("row_keep_categories"):
        keep_values = {
            normalize_text(v)
            for v in scenario["row_keep_categories"]
        }
        df_out = df_out.loc[
            df_out["Cat"].isin(keep_values)
        ].copy()
    counts["after_row_keep_categories"] = len(df_out)

    if scenario.get("row_drop_categories"):
        drop_values = {
            normalize_text(v)
            for v in scenario["row_drop_categories"]
        }
        df_out = df_out.loc[
            ~df_out["Cat"].isin(drop_values)
        ].copy()
    counts["after_row_drop_categories"] = len(df_out)

    if scenario.get("row_keep_location_types"):
        keep_values = {
            normalize_text(v)
            for v in scenario["row_keep_location_types"]
        }
        df_out = df_out.loc[
            df_out["Location_Type"].isin(keep_values)
        ].copy()
    counts["after_row_keep_location_types"] = len(df_out)

    if scenario.get("row_drop_location_types"):
        drop_values = {
            normalize_text(v)
            for v in scenario["row_drop_location_types"]
        }
        df_out = df_out.loc[
            ~df_out["Location_Type"].isin(drop_values)
        ].copy()
    counts["after_row_drop_location_types"] = len(df_out)

    return df_out, counts


def collapse_to_location_rows(source_df, analyte_columns, metadata_columns):
    """
    Collapse sample-event rows to one row per Location_ID.

    Rules:
    - Sample_Date: earliest retained sample date for that location.
    - Other metadata: first nonblank retained value.
    - Analytes: arithmetic mean across retained sample-event rows.
    """
    work = source_df.copy()

    work["Sample_Date"] = pd.to_datetime(
        work["Sample_Date"],
        errors="coerce",
    )

    for col in analyte_columns:
        work[col] = pd.to_numeric(work[col], errors="coerce")

    metadata_agg = {"Sample_Date": "min"}

    for col in metadata_columns:
        if col not in ["Location_ID", "Sample_Date"]:
            metadata_agg[col] = first_nonblank

    meta_base = (
        work
        .replace("", np.nan)
        .groupby("Location_ID", dropna=False)
        .agg(metadata_agg)
        .reset_index()
    )

    collapsed_numeric = (
        work
        .groupby("Location_ID", dropna=False)[analyte_columns]
        .mean(numeric_only=True)
        .reset_index()
    )

    collapsed = meta_base.merge(
        collapsed_numeric,
        on="Location_ID",
        how="outer",
    )

    desired_order = (
        ["Location_ID"]
        + [c for c in metadata_columns if c != "Location_ID"]
        + analyte_columns
    )

    collapsed = collapsed[desired_order].copy()

    collapsed["Sample_Date"] = (
        pd.to_datetime(collapsed["Sample_Date"], errors="coerce")
        .dt.strftime("%Y-%m-%d")
        .fillna("")
    )

    return collapsed


# ------------------------------------------------------------------
# Read primary synoptic matrix and field-parameter staging matrix
# ------------------------------------------------------------------
primary = clean_columns(
    pd.read_excel(PRIMARY_INPUT_FILE, dtype=object)
)

field_params = clean_columns(
    pd.read_excel(FIELD_PARAMS_INPUT_FILE, dtype=object)
)

# Normalize location-name conventions for join compatibility.
if "Location" not in primary.columns and "Location_ID" in primary.columns:
    primary = primary.rename(columns={"Location_ID": "Location"})

if "Location" not in field_params.columns and "Location_ID" in field_params.columns:
    field_params = field_params.rename(columns={"Location_ID": "Location"})

required_primary_cols = ["Location", "Sample_Date"]
required_field_cols = ["Location", "Sample_Date"]

missing_primary = [
    col for col in required_primary_cols
    if col not in primary.columns
]

missing_field = [
    col for col in required_field_cols
    if col not in field_params.columns
]

if missing_primary:
    raise ValueError(
        "Primary synoptic matrix is missing required join columns: "
        f"{missing_primary}"
    )

if missing_field:
    raise ValueError(
        "Field-parameter matrix is missing required join columns: "
        f"{missing_field}"
    )

# ------------------------------------------------------------------
# Distinguish laboratory conductivity from field specific conductance
# ------------------------------------------------------------------
# Specific Conductance in the primary synoptic matrix is laboratory-derived.
# Rename it before joining the field table, where Specific Conductance is the
# field measurement.
if "Specific Conductance" in primary.columns:
    if "Lab_Cond" in primary.columns:
        raise ValueError(
            "Primary synoptic matrix contains both 'Specific Conductance' and "
            "'Lab_Cond'. Confirm the intended laboratory conductivity column "
            "before proceeding."
        )

    primary = primary.rename(
        columns={"Specific Conductance": "Lab_Cond"}
    )
else:
    raise ValueError(
        "Expected laboratory conductivity column 'Specific Conductance' was "
        "not found in the primary synoptic matrix."
    )

# ------------------------------------------------------------------
# Normalize join keys
# ------------------------------------------------------------------
primary["_join_location"] = (
    primary["Location"]
    .fillna("")
    .astype(str)
    .str.strip()
)

field_params["_join_location"] = (
    field_params["Location"]
    .fillna("")
    .astype(str)
    .str.strip()
)

primary["_join_sample_date"] = pd.to_datetime(
    primary["Sample_Date"],
    errors="coerce",
).dt.strftime("%Y-%m-%d")

field_params["_join_sample_date"] = pd.to_datetime(
    field_params["Sample_Date"],
    errors="coerce",
).dt.strftime("%Y-%m-%d")

bad_primary_keys = primary.loc[
    (primary["_join_location"] == "")
    | (primary["_join_sample_date"].isna()),
    ["Location", "Sample_Date"],
].copy()

if not bad_primary_keys.empty:
    raise ValueError(
        "Primary synoptic matrix contains blank or unparseable Location/Sample_Date "
        "join keys:\n"
        f"{bad_primary_keys.to_string(index=False)}"
    )

# ------------------------------------------------------------------
# Validate field staging keys: exactly one row per Location + Sample_Date
# ------------------------------------------------------------------
field_key_counts = (
    field_params
    .groupby(
        ["_join_location", "_join_sample_date"],
        dropna=False,
    )
    .size()
    .reset_index(name="n_rows")
)

duplicate_field_keys = field_key_counts.loc[
    field_key_counts["n_rows"] > 1
].copy()

if not duplicate_field_keys.empty:
    raise ValueError(
        "field_params_intermediate_wide.xlsx has duplicate Location + Sample_Date "
        "keys. Resolve them before joining so primary synoptic rows are not duplicated:\n"
        f"{duplicate_field_keys.to_string(index=False)}"
    )

# ------------------------------------------------------------------
# Identify field-parameter analytes and provenance columns
# ------------------------------------------------------------------
FIELD_PROVENANCE_COLS = [
    "Match_Location",
    "Source_Sample_Date",
]

field_non_analyte_cols = {
    "Location",
    "Sample_Date",
    "_join_location",
    "_join_sample_date",
    *FIELD_PROVENANCE_COLS,
}

field_candidate_cols = [
    col for col in field_params.columns
    if col not in field_non_analyte_cols
    and str(col).strip() != ""
    and not str(col).strip().lower().startswith("unnamed:")
]

field_numeric_probe = field_params.copy()

for col in field_candidate_cols:
    field_numeric_probe[col] = pd.to_numeric(
        field_numeric_probe[col],
        errors="coerce",
    )

field_analyte_cols = [
    col for col in field_candidate_cols
    if field_numeric_probe[col].notna().any()
]

if not field_analyte_cols:
    raise ValueError(
        "No numeric field-parameter analyte columns were found in "
        "field_params_intermediate_wide.xlsx."
    )

# Other than conductivity, any remaining exact name collision needs an explicit
# decision instead of a silent _x/_y merge.
remaining_collisions = [
    col for col in field_analyte_cols
    if col in primary.columns
]

if remaining_collisions:
    raise ValueError(
        "Primary synoptic matrix and field-parameter staging matrix still share "
        "these analyte names after conductivity handling:\n"
        f"{remaining_collisions}\n"
        "Decide whether each should be renamed, retained from one source, or "
        "merged by filling only missing values."
    )

field_provenance_to_keep = [
    col for col in FIELD_PROVENANCE_COLS
    if col in field_params.columns
]

field_for_join = field_params[
    [
        "_join_location",
        "_join_sample_date",
        *field_provenance_to_keep,
        *field_analyte_cols,
    ]
].copy()

# ------------------------------------------------------------------
# Audit field rows that will not join to a primary synoptic row
# ------------------------------------------------------------------
primary_key_set = set(
    zip(
        primary["_join_location"],
        primary["_join_sample_date"],
    )
)

unmatched_field_rows = field_for_join.loc[
    ~field_for_join.apply(
        lambda row: (
            row["_join_location"],
            row["_join_sample_date"],
        ) in primary_key_set,
        axis=1,
    )
].copy()

# ------------------------------------------------------------------
# Left-join field parameters onto primary full matrix
# ------------------------------------------------------------------
# The primary synoptic matrix defines the row universe.
df = primary.merge(
    field_for_join,
    on=["_join_location", "_join_sample_date"],
    how="left",
    validate="many_to_one",
)

# Use the standardized metadata label expected by all Cell 5 logic.
df = df.rename(columns={"Location": "Location_ID"})

# ------------------------------------------------------------------
# Create field-to-laboratory conductivity ratio
# ------------------------------------------------------------------
df["Lab_Cond"] = pd.to_numeric(
    df["Lab_Cond"],
    errors="coerce",
)

df["Specific Conductance"] = pd.to_numeric(
    df["Specific Conductance"],
    errors="coerce",
)

df["Field_Cond_Lab_Cond_Ratio"] = np.where(
    (
        df["Specific Conductance"].notna()
        & df["Lab_Cond"].notna()
        & (df["Lab_Cond"] != 0)
    ),
    df["Specific Conductance"] / df["Lab_Cond"],
    np.nan,
)

# ------------------------------------------------------------------
# Build metadata columns
# ------------------------------------------------------------------
# Cat and Location_Type may not exist in the current full matrix. Create blank
# columns so scenario filters remain available without requiring them.
for col in ["Cat", "Location_Type"]:
    if col not in df.columns:
        df[col] = ""

OPTIONAL_METADATA_COLS = [
    "Match_Location",
    "Source_Sample_Date",
]

metadata_cols = [
    "Location_ID",
    "Sample_Date",
    "Cat",
    "Location_Type",
] + [
    col for col in OPTIONAL_METADATA_COLS
    if col in df.columns
]

for col in metadata_cols:
    if col != "Sample_Date":
        df[col] = df[col].map(normalize_text)

# Remove internal-only join keys so they cannot become candidate analytes.
df = df.drop(columns=["_join_location", "_join_sample_date"])

# ------------------------------------------------------------------
# Detect numeric analyte columns in the combined matrix
# ------------------------------------------------------------------
candidate_cols = [
    col for col in df.columns
    if col not in metadata_cols
    and str(col).strip() != ""
    and not str(col).strip().lower().startswith("unnamed:")
]

if not candidate_cols:
    raise ValueError(
        "No candidate analyte columns found after metadata/header cleanup."
    )

numeric_probe = df.copy()

for col in candidate_cols:
    numeric_probe[col] = pd.to_numeric(
        numeric_probe[col],
        errors="coerce",
    )

analyte_cols = [
    col for col in candidate_cols
    if numeric_probe[col].notna().any()
]

if not analyte_cols:
    raise ValueError(
        "No analyte columns with numeric data were found in the combined matrix."
    )

# ------------------------------------------------------------------
# Put field-parameter / conductivity-comparison analytes at the front
# ------------------------------------------------------------------
FRONT_ANALYTE_ORDER = [
    "Dissolved Oxygen",
    "Oxidation-Reduction Potential",
    "pH",
    "Specific Conductance",
    "Lab_Cond",
    "Field_Cond_Lab_Cond_Ratio",
    "Temperature",
    "Turbidity",
]

front_analytes_present = [
    col for col in FRONT_ANALYTE_ORDER
    if col in analyte_cols
]

remaining_analytes = [
    col for col in analyte_cols
    if col not in front_analytes_present
]

analyte_cols = front_analytes_present + remaining_analytes

# ------------------------------------------------------------------
# Combined-input audit
# ------------------------------------------------------------------
matched_field_param_rows = int(
    df[field_analyte_cols].notna().any(axis=1).sum()
)

print(f"Primary synoptic input: {PRIMARY_INPUT_FILE}")
print(f"Field-parameter input: {FIELD_PARAMS_INPUT_FILE}")
print(f"Primary rows preserved: {len(primary):,}")
print(f"Field-parameter staging rows: {len(field_params):,}")
print(f"Primary rows receiving at least one field parameter: {matched_field_param_rows:,}")
print(f"Field staging rows not added because no primary match exists: {len(unmatched_field_rows):,}")
print(f"Metadata columns retained: {metadata_cols}")
print(f"Field-parameter analytes added: {field_analyte_cols}")
print(f"Combined numeric analyte columns: {len(analyte_cols):,}")
print(f"Front analyte block: {front_analytes_present}")

if not unmatched_field_rows.empty:
    print()
    print("Field staging rows without a primary-matrix match:")
    print(
        unmatched_field_rows[
            ["_join_location", "_join_sample_date"]
        ].to_string(index=False)
    )

print()

# ------------------------------------------------------------------
# Run each configured scenario
# ------------------------------------------------------------------
for scenario in SCENARIOS:
    scenario_name = str(scenario.get("name", "")).strip()

    if not scenario_name:
        raise ValueError(
            "Each scenario requires a nonblank 'name'."
        )

    scenario_description = str(
        scenario.get("description", "")
    ).strip()

    min_col_present_count = scenario.get("min_col_present_count")
    if min_col_present_count is None:
        min_col_present_count = MIN_COL_PRESENT_COUNT

    min_col_present_frac = scenario.get("min_col_present_frac")
    if min_col_present_frac is None:
        min_col_present_frac = MIN_COL_PRESENT_FRAC

    min_row_present_count = scenario.get("min_row_present_count")
    if min_row_present_count is None:
        min_row_present_count = MIN_ROW_PRESENT_COUNT_FINAL

    # ------------------------------------------------------------------
    # Scenario output paths
    # ------------------------------------------------------------------
    OUT_COLLAPSED_FULL = (
        RESULTS_DIR
        / f"synoptic_location_collapsed_full_matrix_{scenario_name}.xlsx"
    )

    OUT_COLLAPSED_FOLDED = (
        RESULTS_DIR
        / f"pca_input_matrix_{scenario_name}.xlsx"
    )

    OUT_KEEP_DROP = (
        RESULTS_DIR
        / f"synoptic_analyte_keep_drop_{scenario_name}.csv"
    )

    OUT_ROW_ACCOUNTING = (
        RESULTS_DIR
        / f"pca_row_accounting_{scenario_name}.csv"
    )

    print("=" * 80)
    print(f"Scenario: {scenario_name}")

    if scenario_description:
        print(f"Description: {scenario_description}")

    print("=" * 80)

    # ------------------------------------------------------------------
    # Apply optional source-row filters before location collapse
    # ------------------------------------------------------------------
    scenario_source, source_filter_counts = apply_source_row_filters(
        df,
        scenario,
    )

    if scenario_source.empty:
        raise ValueError(
            f"Scenario '{scenario_name}' removed every source row before "
            "location-level collapse."
        )

    # ------------------------------------------------------------------
    # Resolve scenario-specific analyte rules
    # ------------------------------------------------------------------
    resolved_drop, unresolved_drop = resolve_analyte_names(
        scenario.get("column_drop", []),
        analyte_cols,
    )

    resolved_keep, unresolved_keep = resolve_analyte_names(
        scenario.get("column_keep", []),
        analyte_cols,
    )

    if unresolved_drop:
        print(
            "Warning — requested column_drop analytes not found: "
            f"{unresolved_drop}"
        )

    if unresolved_keep:
        print(
            "Warning — requested column_keep analytes not found: "
            f"{unresolved_keep}"
        )

    # Start with all numeric analytes. If column_keep is supplied, use only
    # that whitelist. Then remove explicit column_drop analytes.
    scenario_analytes = analyte_cols.copy()

    if resolved_keep:
        scenario_analytes = [
            col for col in scenario_analytes
            if col in resolved_keep
        ]

    scenario_analytes = [
        col for col in scenario_analytes
        if col not in resolved_drop
    ]

    if not scenario_analytes:
        raise ValueError(
            f"Scenario '{scenario_name}' has no analytes after "
            "column_keep/column_drop rules."
        )

    print(
        f"Source rows after explicit row filters: {len(scenario_source):,}"
    )

    print(
        "Scenario analytes before sparse-column thinning: "
        f"{len(scenario_analytes):,}"
    )

    if resolved_drop:
        print(f"Scenario column_drop applied: {resolved_drop}")

    if resolved_keep:
        print(f"Scenario column_keep applied: {resolved_keep}")

    # ------------------------------------------------------------------
    # Collapse event rows to one representative row per location
    # ------------------------------------------------------------------
    collapsed_full = collapse_to_location_rows(
        source_df=scenario_source,
        analyte_columns=scenario_analytes,
        metadata_columns=metadata_cols,
    )

    collapsed_full = collapsed_full.sort_values(
        ["Location_ID"],
        ascending=[True],
        na_position="last",
    ).copy()

    # Save collapsed matrix after explicit scenario column rules but before
    # sparse-column thinning and final row cleanup.
    collapsed_full.to_excel(
        OUT_COLLAPSED_FULL,
        index=False,
    )

    # ------------------------------------------------------------------
    # Sparse-column retention after scenario-specific column slicing
    # ------------------------------------------------------------------
    n_rows_collapsed = len(collapsed_full)

    col_present_count = collapsed_full[
        scenario_analytes
    ].notna().sum(axis=0)

    col_present_frac = (
        col_present_count / n_rows_collapsed
        if n_rows_collapsed > 0
        else pd.Series(
            0.0,
            index=scenario_analytes,
        )
    )

    active_col_summary = pd.DataFrame({
        "scenario": scenario_name,
        "analyte": scenario_analytes,
        "present_count": [
            int(col_present_count.get(col, 0))
            for col in scenario_analytes
        ],
        "present_frac": [
            float(col_present_frac.get(col, 0))
            for col in scenario_analytes
        ],
        "dropped_by_scenario_column_rule": False,
        "kept_after_support_rule": [
            (
                col_present_count.get(col, 0) >= min_col_present_count
                or col_present_frac.get(col, 0) >= min_col_present_frac
            )
            for col in scenario_analytes
        ],
    })

    kept_analytes = active_col_summary.loc[
        active_col_summary["kept_after_support_rule"],
        "analyte",
    ].tolist()

    dropped_sparse_analytes = [
        col for col in scenario_analytes
        if col not in kept_analytes
    ]

    # Add explicit scenario exclusions to the analyte accounting report.
    dropped_col_summary = pd.DataFrame({
        "scenario": scenario_name,
        "analyte": resolved_drop,
        "present_count": [
            int(
                pd.to_numeric(
                    df[col],
                    errors="coerce",
                ).notna().sum()
            )
            if col in df.columns else 0
            for col in resolved_drop
        ],
        "present_frac": [
            float(
                pd.to_numeric(
                    df[col],
                    errors="coerce",
                ).notna().mean()
            )
            if col in df.columns else 0.0
            for col in resolved_drop
        ],
        "dropped_by_scenario_column_rule": True,
        "kept_after_support_rule": False,
    })

    col_summary = pd.concat(
        [active_col_summary, dropped_col_summary],
        ignore_index=True,
        sort=False,
    )

    if not kept_analytes:
        raise ValueError(
            f"Scenario '{scenario_name}' retained no analytes after sparse-column "
            "support thresholds. Lower the thresholds or revise scenario rules."
        )

    # Preserve field parameter / conductivity front ordering where applicable.
    kept_order = [
        col for col in analyte_cols
        if col in kept_analytes
    ]

    # ------------------------------------------------------------------
    # Resolve optional scenario required-analyte rule
    # ------------------------------------------------------------------
    resolved_required, unresolved_required = resolve_analyte_names(
        scenario.get("required_nonmissing_columns", []),
        kept_order,
    )

    if unresolved_required:
        print(
            "Warning — required_nonmissing_columns not found among retained "
            f"scenario analytes: {unresolved_required}"
        )

    # ------------------------------------------------------------------
    # Final row screen after column slicing and sparse-column thinning
    # ------------------------------------------------------------------
    row_accounting = collapsed_full[metadata_cols].copy()

    row_accounting["scenario"] = scenario_name

    row_accounting["present_kept_analyte_count"] = (
        collapsed_full[kept_order].notna().sum(axis=1)
    )

    row_accounting["passes_min_present_count"] = (
        row_accounting["present_kept_analyte_count"]
        >= min_row_present_count
    )

    if resolved_required:
        required_complete = collapsed_full[
            resolved_required
        ].notna().all(axis=1)
    else:
        required_complete = pd.Series(
            True,
            index=collapsed_full.index,
        )

    row_accounting["passes_required_nonmissing_columns"] = required_complete

    row_accounting["kept_for_pca"] = (
        row_accounting["passes_min_present_count"]
        & row_accounting["passes_required_nonmissing_columns"]
    )

    def assign_row_reason(row):
        reasons = []

        if not row["passes_min_present_count"]:
            reasons.append(
                f"fewer_than_{min_row_present_count}_retained_analytes"
            )

        if not row["passes_required_nonmissing_columns"]:
            reasons.append(
                "missing_required_scenario_analyte"
            )

        return "; ".join(reasons) if reasons else "kept"

    row_accounting["row_decision_reason"] = row_accounting.apply(
        assign_row_reason,
        axis=1,
    )

    folded = collapsed_full.loc[
        row_accounting["kept_for_pca"].to_numpy(),
        metadata_cols + kept_order,
    ].copy()

    if folded.empty:
        raise ValueError(
            f"Scenario '{scenario_name}' retained no rows after final "
            f"row-completeness cleanup. Current minimum is "
            f"{min_row_present_count} retained analytes."
        )

    # ------------------------------------------------------------------
    # Final analyte accounting
    # ------------------------------------------------------------------
    col_summary["support_threshold_count"] = min_col_present_count
    col_summary["support_threshold_frac"] = min_col_present_frac

    col_summary["decision"] = np.where(
        col_summary["dropped_by_scenario_column_rule"],
        "dropped_by_scenario_column_rule",
        np.where(
            col_summary["analyte"].isin(kept_order),
            "kept_for_pca",
            "dropped_by_sparse_support_rule",
        ),
    )

    col_summary = col_summary.sort_values(
        ["decision", "present_count", "present_frac", "analyte"],
        ascending=[True, False, False, True],
    ).reset_index(drop=True)

    # ------------------------------------------------------------------
    # Save scenario products
    # ------------------------------------------------------------------
    folded.to_excel(
        OUT_COLLAPSED_FOLDED,
        index=False,
    )

    col_summary.to_csv(
        OUT_KEEP_DROP,
        index=False,
    )

    row_accounting.to_csv(
        OUT_ROW_ACCOUNTING,
        index=False,
    )

    # ------------------------------------------------------------------
    # Print scenario summary
    # ------------------------------------------------------------------
    dropped_location_count = int(
        (~row_accounting["kept_for_pca"]).sum()
    )

    print("Saved:")
    print(f" - {OUT_COLLAPSED_FULL}")
    print(f" - {OUT_COLLAPSED_FOLDED}")
    print(f" - {OUT_KEEP_DROP}")
    print(f" - {OUT_ROW_ACCOUNTING}")
    print()

    print(f"Collapsed location rows: {len(collapsed_full):,}")
    print(
        "Scenario analytes before sparse support thinning: "
        f"{len(scenario_analytes):,}"
    )
    print(f"Kept analytes for PCA: {len(kept_order):,}")
    print(
        "Dropped analytes by explicit scenario rule: "
        f"{len(resolved_drop):,}"
    )
    print(
        "Dropped analytes by sparse support rule: "
        f"{len(dropped_sparse_analytes):,}"
    )
    print(f"Rows retained for PCA: {len(folded):,}")
    print(
        "Rows dropped after scenario column slicing and completeness screening: "
        f"{dropped_location_count:,}"
    )
    print(
        f"Column keep thresholds: count >= {min_col_present_count} "
        f"OR fraction >= {min_col_present_frac:.0%}"
    )
    print(
        "Final row minimum present retained analytes: "
        f"{min_row_present_count}"
    )

    if resolved_required:
        print(
            "Required nonmissing analytes for this scenario: "
            f"{resolved_required}"
        )

    if dropped_location_count > 0:
        print()
        print("Rows dropped from PCA input:")
        print(
            row_accounting.loc[
                ~row_accounting["kept_for_pca"],
                [
                    "Location_ID",
                    "Sample_Date",
                    "present_kept_analyte_count",
                    "row_decision_reason",
                ],
            ].to_string(index=False)
        )

    print()

Primary synoptic input: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_all_rotated_numeric_matrix_plus_treatment_geomean_plus_r80zonal.xlsx
Field-parameter input: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\field_params_intermediate_wide.xlsx
Primary rows preserved: 107
Field-parameter staging rows: 106
Primary rows receiving at least one field parameter: 106
Field staging rows not added because no primary match exists: 0
Metadata columns retained: ['Location_ID', 'Sample_Date', 'Cat', 'Location_Type', 'Match_Location', 'Source_Sample_Date']
Field-parameter analytes added: ['Dissolved Oxygen', 'Oxidation-Reduction Potential', 'pH', 'Specific Conductance', 'Temperature', 'Turbidity']
Combined numeric analyte columns: 477
Front analyte block: ['Dissolved Oxygen', 'Oxidation-Reduction Potential', 'pH', 'Specific Conductance', 'Lab_Cond', 'Field_Cond_Lab_Cond_Ratio', 'Temperature', 'Turbidity']

================================================================================
Scenario: SetOne
Description: Drop Dissolved Oxygen and Oxidation-Reduction Potential before analyte-support and row-completeness screening.
================================================================================
Source rows after explicit row filters: 107
Scenario analytes before sparse-column thinning: 475
Scenario column_drop applied: ['Dissolved Oxygen', 'Oxidation-Reduction Potential']

C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\3346989076.py:397: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_location_collapsed_full_matrix_SetOne.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_input_matrix_SetOne.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\synoptic_analyte_keep_drop_SetOne.csv
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_row_accounting_SetOne.csv

Collapsed location rows: 85
Scenario analytes before sparse support thinning: 475
Kept analytes for PCA: 419
Dropped analytes by explicit scenario rule: 2
Dropped analytes by sparse support rule: 56
Rows retained for PCA: 85
Rows dropped after scenario column slicing and completeness screening: 0
Column keep thresholds: count >= 3 OR fraction >= 5%
Final row minimum present retained analytes: 2

In [24]:
# Cell 5_b Dense — Create a complete-case PCA matrix from pca_input_matrix_SetOne
#
# Purpose:
# - Read the manually reviewed SetOne PCA-input matrix.
# - Require complete coverage for the retained core field-parameter block.
# - Drop rows missing one or more required core field parameters.
# - From the surviving rows, retain only analyte columns that are complete
#   across every remaining location.
# - Preserve metadata and output an explicitly dense PCA matrix.
# - Export row and column accounting so all exclusions are reviewable.
#
# Dense-matrix logic:
# 1. Core field parameters define the required row-completeness block.
# 2. A location missing any core field parameter is dropped.
# 3. Among retained locations, keep every analyte with 100% non-null coverage.
# 4. This allows the matrix to become progressively more selective as additional
#    analytes are considered further out in parameter space.
#
# Input:
# - pca_input_matrix_SetOne.xlsx
#
# Outputs:
# 1. pca_input_matrix_SetOne_Dense.xlsx
# 2. pca_dense_row_accounting_SetOne.csv
# 3. pca_dense_column_accounting_SetOne.csv

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results_v2"

INPUT_FILE = RESULTS_DIR / "pca_input_matrix_SetOne.xlsx"

OUT_DENSE = RESULTS_DIR / "pca_input_matrix_SetOne_Dense.xlsx"
OUT_ROW_ACCOUNTING = RESULTS_DIR / "pca_dense_row_accounting_SetOne.csv"
OUT_COLUMN_ACCOUNTING = RESULTS_DIR / "pca_dense_column_accounting_SetOne.csv"

# For SetOne, Dissolved Oxygen and ORP were deliberately dropped.
# These four remaining field parameters are the required core block.
CORE_FIELD_PARAMETERS = [
    "pH",
    "Specific Conductance",
    "Temperature",
    "Turbidity",
]

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = [str(col).strip() for col in df.columns]
    return df


def normalize_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


# ------------------------------------------------------------------
# Read reviewed SetOne PCA matrix
# ------------------------------------------------------------------
df = clean_columns(pd.read_excel(INPUT_FILE, dtype=object))

# Accept either Location_ID or Location, but standardize internally.
if "Location_ID" not in df.columns and "Location" in df.columns:
    df = df.rename(columns={"Location": "Location_ID"})

required_metadata = ["Location_ID", "Sample_Date"]
missing_metadata = [
    col for col in required_metadata
    if col not in df.columns
]

if missing_metadata:
    raise ValueError(
        f"Input file is missing required metadata columns: {missing_metadata}"
    )

# These columns are metadata / provenance, not PCA analytes.
POSSIBLE_METADATA_COLS = [
    "Location_ID",
    "Sample_Date",
    "Cat",
    "Location_Type",
    "Match_Location",
    "Source_Sample_Date",
]

metadata_cols = [
    col for col in POSSIBLE_METADATA_COLS
    if col in df.columns
]

# Preserve any optional standard metadata fields as blanks if absent.
for col in ["Cat", "Location_Type"]:
    if col not in df.columns:
        df[col] = ""
        metadata_cols.append(col)

# Keep metadata in a stable order.
metadata_cols = [
    col for col in POSSIBLE_METADATA_COLS
    if col in df.columns
]

for col in metadata_cols:
    if col != "Sample_Date":
        df[col] = df[col].map(normalize_text)

# ------------------------------------------------------------------
# Detect numeric analyte columns
# ------------------------------------------------------------------
candidate_cols = [
    col for col in df.columns
    if col not in metadata_cols
    and str(col).strip() != ""
    and not str(col).strip().lower().startswith("unnamed:")
]

if not candidate_cols:
    raise ValueError(
        "No candidate analyte columns found after metadata cleanup."
    )

numeric_df = df.copy()

for col in candidate_cols:
    numeric_df[col] = pd.to_numeric(
        numeric_df[col],
        errors="coerce",
    )

analyte_cols = [
    col for col in candidate_cols
    if numeric_df[col].notna().any()
]

if not analyte_cols:
    raise ValueError(
        "No numeric analyte columns were found in the SetOne PCA matrix."
    )

# ------------------------------------------------------------------
# Validate required core field-parameter block
# ------------------------------------------------------------------
missing_core_fields = [
    col for col in CORE_FIELD_PARAMETERS
    if col not in analyte_cols
]

if missing_core_fields:
    raise ValueError(
        "The Dense step requires these core field-parameter columns, but they "
        f"are missing from the SetOne PCA matrix: {missing_core_fields}"
    )

# Use numeric versions for all analyte completeness checks.
work = df[metadata_cols].copy()

for col in analyte_cols:
    work[col] = numeric_df[col]

# ------------------------------------------------------------------
# Row filter: require complete core field parameters
# ------------------------------------------------------------------
row_accounting = work[metadata_cols].copy()

row_accounting["core_field_parameters_required"] = ", ".join(
    CORE_FIELD_PARAMETERS
)

row_accounting["n_core_field_parameters_present"] = (
    work[CORE_FIELD_PARAMETERS]
    .notna()
    .sum(axis=1)
)

row_accounting["n_core_field_parameters_missing"] = (
    len(CORE_FIELD_PARAMETERS)
    - row_accounting["n_core_field_parameters_present"]
)

row_accounting["kept_for_dense_matrix"] = (
    row_accounting["n_core_field_parameters_missing"] == 0
)

row_accounting["row_decision_reason"] = np.where(
    row_accounting["kept_for_dense_matrix"],
    "kept_complete_core_field_parameters",
    "dropped_missing_core_field_parameter",
)

core_missing_columns = (
    work[CORE_FIELD_PARAMETERS]
    .isna()
    .apply(
        lambda row: "; ".join(
            [
                col
                for col, is_missing in row.items()
                if is_missing
            ]
        ),
        axis=1,
    )
)

row_accounting["missing_core_field_parameters"] = core_missing_columns

dense_rows = work.loc[
    row_accounting["kept_for_dense_matrix"].to_numpy()
].copy()

if dense_rows.empty:
    raise ValueError(
        "No rows have complete required core field parameters. "
        "Review CORE_FIELD_PARAMETERS or the SetOne source matrix."
    )

# ------------------------------------------------------------------
# Column filter: retain only analytes complete across retained rows
# ------------------------------------------------------------------
column_present_count = dense_rows[analyte_cols].notna().sum(axis=0)
n_dense_rows = len(dense_rows)

column_accounting = pd.DataFrame({
    "analyte": analyte_cols,
    "present_count_after_core_row_filter": [
        int(column_present_count[col])
        for col in analyte_cols
    ],
    "total_rows_after_core_row_filter": n_dense_rows,
    "present_frac_after_core_row_filter": [
        float(column_present_count[col] / n_dense_rows)
        for col in analyte_cols
    ],
})

column_accounting["is_core_field_parameter"] = (
    column_accounting["analyte"].isin(CORE_FIELD_PARAMETERS)
)

column_accounting["kept_for_dense_matrix"] = (
    column_accounting["present_count_after_core_row_filter"]
    == n_dense_rows
)

column_accounting["column_decision_reason"] = np.where(
    column_accounting["kept_for_dense_matrix"],
    "kept_complete_across_retained_rows",
    "dropped_incomplete_across_retained_rows",
)

dense_analytes = column_accounting.loc[
    column_accounting["kept_for_dense_matrix"],
    "analyte",
].tolist()

if not dense_analytes:
    raise ValueError(
        "No analyte columns are complete across retained rows after the "
        "core-field-parameter row filter."
    )

# Preserve the core field block first, followed by all other complete analytes
# in their existing SetOne order.
dense_analyte_order = (
    [col for col in CORE_FIELD_PARAMETERS if col in dense_analytes]
    + [
        col for col in analyte_cols
        if col in dense_analytes
        and col not in CORE_FIELD_PARAMETERS
    ]
)

# ------------------------------------------------------------------
# Build dense PCA matrix
# ------------------------------------------------------------------
dense_matrix = dense_rows[
    metadata_cols + dense_analyte_order
].copy()

dense_matrix = dense_matrix.sort_values(
    ["Location_ID", "Sample_Date"],
    ascending=[True, True],
    na_position="last",
).reset_index(drop=True)

# ------------------------------------------------------------------
# Sort / save audit products
# ------------------------------------------------------------------
row_accounting = row_accounting.sort_values(
    ["kept_for_dense_matrix", "Location_ID", "Sample_Date"],
    ascending=[False, True, True],
    na_position="last",
).reset_index(drop=True)

column_accounting = column_accounting.sort_values(
    [
        "kept_for_dense_matrix",
        "is_core_field_parameter",
        "present_count_after_core_row_filter",
        "analyte",
    ],
    ascending=[False, False, False, True],
).reset_index(drop=True)

dense_matrix.to_excel(OUT_DENSE, index=False)
row_accounting.to_csv(OUT_ROW_ACCOUNTING, index=False)
column_accounting.to_csv(OUT_COLUMN_ACCOUNTING, index=False)

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------
rows_dropped = int((~row_accounting["kept_for_dense_matrix"]).sum())
columns_dropped = int(
    (~column_accounting["kept_for_dense_matrix"]).sum()
)

print("Saved:")
print(f" - {OUT_DENSE}")
print(f" - {OUT_ROW_ACCOUNTING}")
print(f" - {OUT_COLUMN_ACCOUNTING}")
print()

print(f"Input SetOne PCA rows: {len(work):,}")
print(f"Rows with complete core field parameters: {len(dense_matrix):,}")
print(f"Rows dropped for missing core field parameters: {rows_dropped:,}")
print()

print(f"Input SetOne analyte columns: {len(analyte_cols):,}")
print(f"Complete analytes retained in dense matrix: {len(dense_analyte_order):,}")
print(f"Incomplete analytes dropped from dense matrix: {columns_dropped:,}")
print()

print("Required core field parameters:")
for col in CORE_FIELD_PARAMETERS:
    print(f" - {col}")

if rows_dropped > 0:
    print()
    print("Rows dropped for missing core field parameters:")
    print(
        row_accounting.loc[
            ~row_accounting["kept_for_dense_matrix"],
            [
                "Location_ID",
                "Sample_Date",
                "missing_core_field_parameters",
                "row_decision_reason",
            ],
        ].to_string(index=False)
    )

print()
print("Dense matrix analytes:")
for col in dense_analyte_order:
    print(f" - {col}")

C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  work[col] = numeric_df[col]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_17300\403228458.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_input_matrix_SetOne_Dense.xlsx
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_dense_row_accounting_SetOne.csv
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_dense_column_accounting_SetOne.csv

Input SetOne PCA rows: 85
Rows with complete core field parameters: 84
Rows dropped for missing core field parameters: 1

Input SetOne analyte columns: 419
Complete analytes retained in dense matrix: 4
Incomplete analytes dropped from dense matrix: 415

Required core field parameters:
 - pH
 - Specific Conductance
 - Temperature
 - Turbidity

Rows dropped for missing core field parameters:
          Location_ID Sample_Date                    missing_core_field_parameters                  row_decision_reason
VS-CTUA-2-INF_GeoMean  2025-11-05 pH; Specific Conductance; Temperature; Turbidity dropped_missing_core_field_parameter

Dense matrix analytes:
 - pH
 - Specific Conductance
 - Temperature
 - Turbidity

In [16]:
### Relict as of 10/21/2026
### Cat refreshers are now mostly satisfactory, with some manual adds due to 
### 1)Timing of geo data input
### 2)Marginal Categories 

# Cell ___ — Refresh Cat in folded synoptic matrix from AllWells_withCat.csv
#
# Purpose:
# - Read synoptic_location_collapsed_folded_matrix.xlsx
# - Read AllWells_withCat.csv from the outer MapRebuildItems directory
# - Use that file as the preferred Cat source
# - Match Location_ID in the folded matrix to location in column A of AllWells_withCat.csv
# - Replace Cat where a better match is found
# - Keep existing Cat as fallback when no match is found
#
# Inputs:
# - C:\Users\kylian.robinson\MapRebuildItems\AllWells_withCat.csv
# - synoptic_location_collapsed_folded_matrix.xlsx
#
# Output:
# - synoptic_location_collapsed_folded_matrix_catrefreshed.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
OUTER_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems")
WORK_DIR = OUTER_DIR / "R80_ZonalRun"
RESULTS_DIR = WORK_DIR / "Results_v2"

INPUT_MATRIX = RESULTS_DIR / "pca_input_matrix.xlsx"
CAT_FILE = OUTER_DIR / "AllWells_withCat.csv"

OUT_UPDATED = RESULTS_DIR / "pca_input_matrix_catrefreshed.xlsx"

# ------------------------------------------------------------------
# Read inputs
# ------------------------------------------------------------------
mat = pd.read_excel(INPUT_MATRIX, dtype=object)
catref = pd.read_csv(CAT_FILE, dtype=str)

mat.columns = [str(c).strip() for c in mat.columns]
catref.columns = [str(c).strip() for c in catref.columns]

required_mat = ["Location_ID", "Cat"]
missing_mat = [c for c in required_mat if c not in mat.columns]
if missing_mat:
    raise ValueError(f"Missing required columns in folded matrix: {missing_mat}")

if catref.shape[1] < 2:
    raise ValueError("AllWells_withCat.csv must have at least two columns: location and Cat.")

# ------------------------------------------------------------------
# Standardize reference columns from first two columns
# ------------------------------------------------------------------
catref = catref.iloc[:, :2].copy()
catref.columns = ["Location_ID_ref", "Cat_ref"]

catref["Location_ID_ref"] = catref["Location_ID_ref"].fillna("").astype(str).str.strip()
catref["Cat_ref"] = catref["Cat_ref"].fillna("").astype(str).str.strip()

mat["Location_ID"] = mat["Location_ID"].fillna("").astype(str).str.strip()
mat["Cat"] = mat["Cat"].fillna("").astype(str).str.strip()

# ------------------------------------------------------------------
# Drop blank and duplicate reference locations
# Keep first nonblank Cat encountered for each location
# ------------------------------------------------------------------
catref = catref.loc[catref["Location_ID_ref"] != ""].copy()

catref = (
    catref.assign(cat_blank=catref["Cat_ref"].eq(""))
    .sort_values(["Location_ID_ref", "cat_blank"], ascending=[True, True])
    .drop_duplicates(["Location_ID_ref"], keep="first")
    .drop(columns=["cat_blank"])
)

# ------------------------------------------------------------------
# Merge and refresh Cat
# ------------------------------------------------------------------
out = mat.merge(
    catref,
    left_on="Location_ID",
    right_on="Location_ID_ref",
    how="left"
)

out["Cat_old"] = out["Cat"]
out["Cat"] = np.where(
    out["Cat_ref"].fillna("").astype(str).str.strip() != "",
    out["Cat_ref"].fillna("").astype(str).str.strip(),
    out["Cat_old"]
)

# Optional QA flags
out["Cat_Source"] = np.where(
    out["Cat_ref"].fillna("").astype(str).str.strip() != "",
    "AllWells_withCat",
    "original_folded_matrix"
)

# Clean up
out = out.drop(columns=["Location_ID_ref", "Cat_ref"])
out = out[[c for c in out.columns if c != "Cat_old"] + ["Cat_old"]]

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out.to_excel(OUT_UPDATED, index=False)

n_total = len(out)
n_ref_match = (out["Cat_Source"] == "AllWells_withCat").sum()
n_changed = (out["Cat"] != out["Cat_old"]).sum()

print("Saved:")
print(f" - {OUT_UPDATED}")
print(f"Rows in matrix: {n_total:,}")
print(f"Rows matched to AllWells_withCat: {n_ref_match:,}")
print(f"Rows where Cat changed: {n_changed:,}")

C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_9552\999162159.py:86: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["Cat_old"] = out["Cat"]
C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_9552\999162159.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["Cat_Source"] = np.where(

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results_v2\pca_input_matrix_catrefreshed.xlsx
Rows in matrix: 100
Rows matched to AllWells_withCat: 72
Rows where Cat changed: 40

In [16]:
# Cell 6 — Load reviewed synoptic matrix and expose row/column names for planning

from pathlib import Path
import pandas as pd

WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"
INPUT_FILE = RESULTS_DIR / "synoptic_location_reviewed.xlsx"

KNOWN_METADATA_COLS = ["Location_ID", "Sample_Date", "Cat", "Location_Type"]

df = pd.read_excel(INPUT_FILE, dtype=object)
df.columns = [str(c).strip() for c in df.columns]

metadata_cols = [c for c in KNOWN_METADATA_COLS if c in df.columns]
analyte_cols = [c for c in df.columns if c not in metadata_cols]

location_ids = []
if "Location_ID" in df.columns:
    location_ids = (
        df["Location_ID"]
        .fillna("")
        .astype(str)
        .str.strip()
        .loc[lambda s: s != ""]
        .drop_duplicates()
        .tolist()
    )

cats = []
if "Cat" in df.columns:
    cats = (
        df["Cat"]
        .fillna("")
        .astype(str)
        .str.strip()
        .loc[lambda s: s != ""]
        .drop_duplicates()
        .tolist()
    )

print("Loaded:", INPUT_FILE)
print(f"Shape: {df.shape}")
print()
print("metadata_cols =")
print(repr(metadata_cols))
print()
print("analyte_cols =")
print(repr(analyte_cols))
print()
print("location_ids =")
print(repr(location_ids))
print()
print("cats =")
print(repr(cats))

Loaded: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed.xlsx
Shape: (93, 50)

metadata_cols =
['Location_ID', 'Sample_Date', 'Cat', 'Location_Type']

analyte_cols =
['Bromide', 'Chloride', 'Fluoride', 'Mercury', 'Sulfate', 'Acidity or Alkalinity of a solution', 'Alkalinity-CO3+HCO3', 'Chromium', 'Total Phosphate as Phosphorus', 'Aluminum', 'Antimony', 'Arsenic', 'Barium', 'Beryllium', 'Boron', 'Cadmium', 'Calcium', 'Cobalt', 'Copper', 'Iron', 'Lead', 'Magnesium', 'Manganese', 'Molybdenum', 'Nickel', 'Perchlorate', 'Potassium', 'Selenium', 'Silver', 'Sodium', 'Strontium', 'Thallium', 'Tin', 'Total Dissolved Solids', 'Uranium', 'Vanadium', 'Zinc', 'Alkalinity-CO3', 'Ammonia as Nitrogen', 'Nitrate-Nitrite as Nitrogen', 'Specific Conductance', 'Hardness', 'Silicon Dioxide', 'Total Kjeldahl Nitrogen', 'Total Organic Carbon', 'Tritium']

location_ids =
['CRPZ-1', 'CRPZ-2A', 'CRPZ-2B', 'CRPZ-3', 'CRPZ-4', 'CRPZ-5', 'CrEX-1', 'CrEX-2', 'CrEX-3', 'CrEX-4', 'CrIN-1', 'CrIN-2', 'CrIN-3', 'CrIN-4', 'CrIN-5', 'CrIN-6', 'PM-1', 'PM-2', 'PM-3', 'PM-4', 'PM-5', 'R-1', 'R-10a', 'R-11', 'R-12 S1', 'R-12 S2', 'R-13', 'R-14 S1', 'R-15', 'R-17 S1', 'R-17 S2', 'R-20 S1', 'R-20 S2', 'R-21', 'R-22', 'R-23', 'R-28', 'R-32', 'R-32 S1', 'R-33 S1', 'R-33 S2', 'R-34', 'R-35a', 'R-35b', 'R-36', 'R-37 S2', 'R-38', 'R-39', 'R-40 S1', 'R-40 S2', 'R-41 S2', 'R-42', 'R-43 S1', 'R-43 S2', 'R-44 S1', 'R-44 S2', 'R-45 S1', 'R-45 S2', 'R-46', 'R-49 S1', 'R-49 S2', 'R-50 S2', 'R-51 S1', 'R-51 S2', 'R-52 S1', 'R-52 S2', 'R-53 S1', 'R-53 S2', 'R-54 S1', 'R-54 S2', 'R-55 S1', 'R-55 S2', 'R-56 S1', 'R-56 S2', 'R-57 S1', 'R-57 S2', 'R-61', 'R-61 S1', 'R-62', 'R-67', 'R-70 S1', 'R-70 S2', 'R-71 S1', 'R-71 S2', 'R-72 S1', 'R-72 S2', 'R-73', 'R-76', 'R-80', 'SIMR-2', 'SIMR-3 S1', 'SIMR-3 S2', 'Test Well 8']

cats =
['Pumicious', 'Puye', 'Extraction', 'Injection', 'Supply', 'Tcar_Down']

In [20]:
# Cell — Aggregate full analytical timeline files for wedge wells

###!!Relict as of 9/24/2026?

#
# Purpose:
# - Join the existing full timeline file with the new 2026-09-15 EIM export
# - Fail fast if the column schemas do not match exactly
# - Save the combined output as WedgeWells_FullTimeline.csv
#
# Inputs:
# - Results/combined_eim_full_timeline.csv
# - Results/EIM_EXPORT_09_15_2026.csv
#
# Output:
# - Results/WedgeWells_FullTimeline.csv

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

FILE_1 = RESULTS_DIR / "combined_eim_full_timeline_raw.csv"
FILE_2 = RESULTS_DIR / "EIM_EXPORT_09_15_2026.csv"

OUT_FILE = RESULTS_DIR / "WedgeWells_FullTimeline.csv"

# ------------------------------------------------------------------
# Read inputs
# ------------------------------------------------------------------
df1 = pd.read_csv(FILE_1, dtype=str, low_memory=False)
df2 = pd.read_csv(FILE_2, dtype=str, low_memory=False)

df1.columns = [str(c).strip() for c in df1.columns]
df2.columns = [str(c).strip() for c in df2.columns]

cols1 = list(df1.columns)
cols2 = list(df2.columns)

# ------------------------------------------------------------------
# Schema checks
# ------------------------------------------------------------------
if cols1 != cols2:
    only_in_file1 = [c for c in cols1 if c not in cols2]
    only_in_file2 = [c for c in cols2 if c not in cols1]

    order_mismatches = []
    for i, (c1, c2) in enumerate(zip(cols1, cols2)):
        if c1 != c2:
            order_mismatches.append((i, c1, c2))

    msg_parts = ["Column mismatch between input files."]

    if only_in_file1:
        msg_parts.append(f"Columns only in {FILE_1.name}: {only_in_file1}")
    if only_in_file2:
        msg_parts.append(f"Columns only in {FILE_2.name}: {only_in_file2}")

    if not only_in_file1 and not only_in_file2 and order_mismatches:
        preview = order_mismatches[:10]
        msg_parts.append(
            "Same column names detected but different column order. "
            f"First order mismatches (index, file1, file2): {preview}"
        )

    if len(cols1) != len(cols2):
        msg_parts.append(
            f"Different column counts: {FILE_1.name} has {len(cols1)}, "
            f"{FILE_2.name} has {len(cols2)}."
        )

    raise ValueError("\n".join(msg_parts))

# ------------------------------------------------------------------
# Concatenate
# ------------------------------------------------------------------
combined = pd.concat([df1, df2], axis=0, ignore_index=True)

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
combined.to_csv(OUT_FILE, index=False)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Rows from {FILE_1.name}: {len(df1):,}")
print(f"Rows from {FILE_2.name}: {len(df2):,}")
print(f"Combined rows: {len(combined):,}")
print(f"Column count verified: {len(cols1):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\WedgeWells_FullTimeline.csv
Rows from combined_eim_full_timeline_raw.csv: 1,924,782
Rows from EIM_EXPORT_09_15_2026.csv: 42,621
Combined rows: 1,967,403
Column count verified: 31

In [4]:
# Cell 8 — Wide backfill candidate table for selected wells
#
# Purpose:
# - For selected wells, scan the full long-form analytical dataset
# - For every analyte column in the reviewed matrix:
#     return the most recent available site/analyte result and its date
# - Ignore whether the reviewed matrix currently has a filled value
# - Resolve same-date duplicates by keeping the highest numeric result
#   (first row wins ties)
#
# Output format:
# - two rows per site
#   row 1 = values
#   row 2 = dates (or NF if no site/analyte row exists)
#
# Inputs:
# - Results/synoptic_location_reviewed.xlsx
# - Results/WedgeWells_FullTimeline.csv   # preferred
#   or fallback to Results/combined_eim_full_timeline_raw.csv if needed
#
# Output:
# - Results/synoptic_wide_backfill_candidates.csv

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

REVIEWED_FILE = RESULTS_DIR / "synoptic_location_reviewed.xlsx"
LONG_FILE = RESULTS_DIR / "WedgeWells_FullTimeline.csv"

OUT_FILE = RESULTS_DIR / "synoptic_wide_backfill_candidates.csv"

TARGET_SITES = [
    "R-12 S1",
    "R-14 S1",
    "R-17 S1",
    "R-17 S2",
    "R-49 S2",
    "R-46",
    "R-53 S1",
    "R-54 S1",
    "R-54 S2",
    "R-56 S1",
    "R-56 S2",
    "R-10 S1",
    "R-10 S2",
    "R-22",
    "R-23",
    "R-41 S2",
    "R-55 S2",
    "PM-4",
    "R-61 S1",
    "R-28",
    "R-32"
]
KNOWN_METADATA_COLS = ["Location_ID", "Sample_Date", "Cat", "Location_Type"]

# ------------------------------------------------------------------
# Read reviewed matrix for analyte column list only
# ------------------------------------------------------------------
reviewed = pd.read_excel(REVIEWED_FILE, dtype=object)
reviewed.columns = [str(c).strip() for c in reviewed.columns]

metadata_cols = [c for c in KNOWN_METADATA_COLS if c in reviewed.columns]
analyte_cols = [c for c in reviewed.columns if c not in metadata_cols]

# ------------------------------------------------------------------
# Read full long-form analytical data
# ------------------------------------------------------------------
raw = pd.read_csv(LONG_FILE, dtype=str, low_memory=False)
raw.columns = [str(c).strip() for c in raw.columns]

df = raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
    "Report Units": "Units",
})

required_cols = ["Location", "Date Sampled", "Parameter", "Result"]
missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing required columns in long-form source: {missing}")

for col in ["Location", "Date Sampled", "Parameter", "Result"]:
    df[col] = df[col].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")

res_txt = df["Result"].fillna("").astype(str).str.strip()
res_core = (
    res_txt
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

df["result_num"] = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

df["Location"] = df["Location"].astype(str).str.strip()
df["Parameter"] = df["Parameter"].astype(str).str.strip()

# Keep only relevant sites/analytes with valid dates
site_data = df.loc[
    df["Location"].isin(TARGET_SITES) &
    df["Parameter"].isin(analyte_cols) &
    df["Date Sampled_dt"].notna()
].copy()

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def fmt_value(x):
    if pd.isna(x):
        return ""
    try:
        x = float(x)
        if x.is_integer():
            return str(int(x))
        return f"{x:g}"
    except Exception:
        return str(x)

def fmt_date(dt):
    if pd.isna(dt):
        return ""
    dt = pd.to_datetime(dt)
    return f"{dt.month}/{dt.day}/{dt.year}"
# ------------------------------------------------------------------
# Build two-row-per-site output
# ------------------------------------------------------------------
out_rows = []

for site in TARGET_SITES:
    value_row = {"Site": site}
    date_row = {"Site": ""}

    site_subset = site_data.loc[site_data["Location"] == site].copy()

    for analyte in analyte_cols:
        cand = site_subset.loc[site_subset["Parameter"] == analyte].copy()

        if cand.empty:
            value_row[analyte] = ""
            date_row[analyte] = "NF"
            continue

        newest_date = cand["Date Sampled_dt"].max()
        newest_rows = cand.loc[cand["Date Sampled_dt"] == newest_date].copy()

        # Explicit duplicate resolution:
        # numeric rows first via descending result_num,
        # then first row wins any remaining tie
        newest_rows = newest_rows.sort_values(
            ["result_num"],
            ascending=[False],
            na_position="last"
        )

        if newest_rows["result_num"].notna().any():
            best = newest_rows.loc[newest_rows["result_num"].notna()].iloc[0]
            value_row[analyte] = fmt_value(best["result_num"])
            date_row[analyte] = fmt_date(newest_date)
        else:
            value_row[analyte] = ""
            date_row[analyte] = fmt_date(newest_date)

    out_rows.append(value_row)
    out_rows.append(date_row)

out_df = pd.DataFrame(out_rows)

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out_df.to_csv(OUT_FILE, index=False)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Target sites: {len(TARGET_SITES):,}")
print(f"Analytes scanned: {len(analyte_cols):,}")
print(f"Output rows written: {len(out_df):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_wide_backfill_candidates.csv
Target sites: 21
Analytes scanned: 46
Output rows written: 42

In [6]:
# Cell 9 — Apply accepted wide backfill values to synoptic_location_reviewed
# and rewrite Sample_Date using majority applied backfill date (ISO format)
#
# Purpose:
# - Read synoptic_location_reviewed.xlsx
# - Read synoptic_wide_backfill_candidates.csv
# - Apply numeric candidate values into matching site/analyte cells
# - Rewrite Sample_Date for touched wells using:
#     YYYY-MM-DD        if one applied date
#     YYYY-MM-DD *      if multiple applied dates, majority date chosen
# - Ensure reruns replace prior backfill-derived Sample_Date values cleanly
#
# Inputs:
# - Results/synoptic_location_reviewed.xlsx
# - Results/synoptic_wide_backfill_candidates.csv
#
# Output:
# - Results/synoptic_location_reviewed_backfilled.xlsx

from pathlib import Path
import pandas as pd
import numpy as np
from collections import Counter

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

REVIEWED_FILE = RESULTS_DIR / "synoptic_location_reviewed.xlsx"
BACKFILL_FILE = RESULTS_DIR / "synoptic_wide_backfill_candidates.csv"

OUT_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled.xlsx"

KNOWN_METADATA_COLS = ["Location_ID", "Sample_Date", "Cat", "Location_Type"]

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def fmt_iso_date_string(x):
    if pd.isna(x):
        return ""
    s = str(x).strip()
    if s == "" or s.upper() == "NF":
        return ""
    dt = pd.to_datetime(s, errors="coerce")
    if pd.isna(dt):
        return ""
    return dt.strftime("%Y-%m-%d")

def to_num_or_nan(x):
    return pd.to_numeric(pd.Series([x]), errors="coerce").iloc[0]

# ------------------------------------------------------------------
# Read reviewed matrix
# ------------------------------------------------------------------
reviewed = pd.read_excel(REVIEWED_FILE, dtype=object)
reviewed.columns = [str(c).strip() for c in reviewed.columns]

required_reviewed = ["Location_ID", "Sample_Date"]
missing_reviewed = [c for c in required_reviewed if c not in reviewed.columns]
if missing_reviewed:
    raise ValueError(f"Reviewed matrix must contain columns: {missing_reviewed}")

reviewed["Location_ID"] = reviewed["Location_ID"].fillna("").astype(str).str.strip()
reviewed["Sample_Date"] = reviewed["Sample_Date"].fillna("").astype(str).str.strip()

metadata_cols = [c for c in KNOWN_METADATA_COLS if c in reviewed.columns]
analyte_cols = [c for c in reviewed.columns if c not in metadata_cols]

# ------------------------------------------------------------------
# Read backfill table
# ------------------------------------------------------------------
bf = pd.read_csv(BACKFILL_FILE, dtype=object)
bf.columns = [str(c).strip() for c in bf.columns]

if "Site" not in bf.columns:
    raise ValueError("Backfill CSV must contain a 'Site' column.")

missing_analytes = [c for c in analyte_cols if c not in bf.columns]
if missing_analytes:
    raise ValueError(f"Backfill CSV is missing analyte columns: {missing_analytes}")

if len(bf) % 2 != 0:
    raise ValueError("Backfill CSV must have an even number of rows (two rows per site).")

# ------------------------------------------------------------------
# Parse two-row-per-site backfill structure
# row 1 = values
# row 2 = dates / NF
# ------------------------------------------------------------------
apply_map = {}

for i in range(0, len(bf), 2):
    value_row = bf.iloc[i]
    date_row = bf.iloc[i + 1]

    site = "" if pd.isna(value_row["Site"]) else str(value_row["Site"]).strip()
    if site == "":
        raise ValueError(f"Expected site name in backfill row {i + 1}.")

    apply_map[site] = {}

    for analyte in analyte_cols:
        raw_val = value_row.get(analyte, "")
        raw_date = date_row.get(analyte, "")

        val_str = "" if pd.isna(raw_val) else str(raw_val).strip()
        date_iso = fmt_iso_date_string(raw_date)

        if val_str == "":
            continue

        num_val = to_num_or_nan(val_str)
        if pd.isna(num_val):
            continue

        apply_map[site][analyte] = {
            "value": float(num_val),
            "date": date_iso,
        }

# ------------------------------------------------------------------
# Apply fills and track dates actually written
# IMPORTANT:
# - Sample_Date is rewritten for touched wells on every rerun
# - Prior stale backfill-derived dates do not persist
# ------------------------------------------------------------------
out = reviewed.copy()
fills_applied = 0
sites_touched = set()
applied_dates_by_site = {}

for row_idx, row in out.iterrows():
    site = row["Location_ID"]
    if site not in apply_map:
        continue

    payloads = apply_map[site]
    if len(payloads) == 0:
        continue

    applied_dates_by_site[site] = []
    sites_touched.add(site)

    for analyte, payload in payloads.items():
        if analyte not in out.columns:
            continue

        out.at[row_idx, analyte] = payload["value"]
        fills_applied += 1

        if payload["date"] != "":
            applied_dates_by_site[site].append(payload["date"])

# ------------------------------------------------------------------
# Rewrite Sample_Date for touched wells
# - one unique applied date  -> YYYY-MM-DD
# - multiple applied dates   -> majority YYYY-MM-DD + " *"
# - no valid applied dates   -> blank
#
# This deliberately overwrites the prior Sample_Date for touched wells
# so reruns reflect the current backfill file rather than stale output.
# ------------------------------------------------------------------
for row_idx, row in out.iterrows():
    site = row["Location_ID"]
    if site not in sites_touched:
        continue

    site_dates = [d for d in applied_dates_by_site.get(site, []) if d != ""]
    if not site_dates:
        out.at[row_idx, "Sample_Date"] = ""
        continue

    counts = Counter(site_dates)
    majority_date, _ = counts.most_common(1)[0]

    if len(counts) == 1:
        out.at[row_idx, "Sample_Date"] = majority_date
    else:
        out.at[row_idx, "Sample_Date"] = f"{majority_date} *"

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out.to_excel(OUT_FILE, index=False)

mixed_sites = sum(
    1 for s in sites_touched
    if len(set([d for d in applied_dates_by_site.get(s, []) if d != ""])) > 1
)

blank_date_sites = sum(
    1 for s in sites_touched
    if len([d for d in applied_dates_by_site.get(s, []) if d != ""]) == 0
)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Sites touched: {len(sites_touched):,}")
print(f"Analyte values written: {fills_applied:,}")
print(f"Sites with mixed-date backfill marked by '*': {mixed_sites:,}")
print(f"Sites touched but with no valid applied dates written: {blank_date_sites:,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed_backfilled.xlsx
Sites touched: 20
Analyte values written: 917
Sites with mixed-date backfill marked by '*': 9
Sites touched but with no valid applied dates written: 0

In [7]:
# Cell 10 — Build tritium review table for current reviewed/backfilled locations
#
# Purpose:
# - Read the current site list from synoptic_location_reviewed_backfilled.xlsx
# - For each site, report whether Tritium is already present in the current document
# - Pull the last five Tritium measurements from the full long-form dataset
# - Write a two-row-per-site review table:
#     row 1 = current-status + values
#     row 2 = dates for those values
#
# Inputs:
# - Results/synoptic_location_reviewed_backfilled.xlsx
# - Results/WedgeWells_FullTimeline.csv
#
# Output:
# - Results/tritium_last5_review.csv

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

REVIEWED_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled.xlsx"
LONG_FILE = RESULTS_DIR / "WedgeWells_FullTimeline.csv"

OUT_FILE = RESULTS_DIR / "tritium_last5_review.csv"

TRITIUM_NAME = "Tritium"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def fmt_value(x):
    if pd.isna(x):
        return ""
    try:
        x = float(x)
        if x.is_integer():
            return str(int(x))
        return f"{x:g}"
    except Exception:
        return str(x)

def fmt_iso_date(dt):
    if pd.isna(dt):
        return ""
    dt = pd.to_datetime(dt)
    return dt.strftime("%Y-%m-%d")

def has_value(x):
    if pd.isna(x):
        return False
    s = str(x).strip()
    if s == "":
        return False
    return pd.notna(pd.to_numeric(pd.Series([s]), errors="coerce").iloc[0])

# ------------------------------------------------------------------
# Read current reviewed/backfilled matrix
# ------------------------------------------------------------------
reviewed = pd.read_excel(REVIEWED_FILE, dtype=object)
reviewed.columns = [str(c).strip() for c in reviewed.columns]

required_reviewed = ["Location_ID", TRITIUM_NAME]
missing_reviewed = [c for c in required_reviewed if c not in reviewed.columns]
if missing_reviewed:
    raise ValueError(f"Reviewed/backfilled file missing required columns: {missing_reviewed}")

reviewed["Location_ID"] = reviewed["Location_ID"].fillna("").astype(str).str.strip()

site_list = (
    reviewed["Location_ID"]
    .loc[lambda s: s != ""]
    .drop_duplicates()
    .tolist()
)

# ------------------------------------------------------------------
# Read long-form analytical data
# ------------------------------------------------------------------
raw = pd.read_csv(LONG_FILE, dtype=str, low_memory=False)
raw.columns = [str(c).strip() for c in raw.columns]

df = raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
})

required_long = ["Location", "Date Sampled", "Parameter", "Result"]
missing_long = [c for c in required_long if c not in df.columns]
if missing_long:
    raise ValueError(f"Long-form source missing required columns: {missing_long}")

for col in ["Location", "Date Sampled", "Parameter", "Result"]:
    df[col] = df[col].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")

res_core = (
    df["Result"]
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)

df["result_num"] = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

df["Location"] = df["Location"].astype(str).str.strip()
df["Parameter"] = df["Parameter"].astype(str).str.strip()

tri = df.loc[
    df["Location"].isin(site_list) &
    (df["Parameter"] == TRITIUM_NAME) &
    df["Date Sampled_dt"].notna()
].copy()

# ------------------------------------------------------------------
# Resolve duplicates within same site/date:
# - prefer numeric rows
# - higher numeric value wins
# - first row wins ties
# Then keep one record per site/date
# ------------------------------------------------------------------
tri = tri.sort_values(
    ["Location", "Date Sampled_dt", "result_num"],
    ascending=[True, False, False],
    na_position="last"
)

tri = tri.drop_duplicates(["Location", "Date Sampled_dt"], keep="first").copy()

# ------------------------------------------------------------------
# Build two-row-per-site output
# ------------------------------------------------------------------
out_rows = []

for site in site_list:
    current_row = reviewed.loc[reviewed["Location_ID"] == site].iloc[0]
    current_has_tritium = "Yes" if has_value(current_row[TRITIUM_NAME]) else "No"

    value_row = {
        "Site": site,
        "In_Current_Document": current_has_tritium,
    }
    date_row = {
        "Site": "",
        "In_Current_Document": "",
    }

    site_tri = tri.loc[tri["Location"] == site].sort_values(
        ["Date Sampled_dt"],
        ascending=[False],
        na_position="last"
    ).head(5)

    site_tri = site_tri.reset_index(drop=True)

    for i in range(5):
        val_col = f"Tritium_{i+1}"
        if i < len(site_tri):
            value_row[val_col] = fmt_value(site_tri.loc[i, "result_num"])
            date_row[val_col] = fmt_iso_date(site_tri.loc[i, "Date Sampled_dt"])
        else:
            value_row[val_col] = ""
            date_row[val_col] = ""

    out_rows.append(value_row)
    out_rows.append(date_row)

out_df = pd.DataFrame(out_rows)

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out_df.to_csv(OUT_FILE, index=False)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Sites reviewed: {len(site_list):,}")
print(f"Rows written: {len(out_df):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\tritium_last5_review.csv
Sites reviewed: 91
Rows written: 182

In [9]:
from pathlib import Path
import pandas as pd

WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"
LONG_FILE = RESULTS_DIR / "WedgeWells_FullTimeline.csv"

raw = pd.read_csv(LONG_FILE, dtype=str, low_memory=False, encoding="utf-8", encoding_errors="replace")
raw.columns = [str(c).strip() for c in raw.columns]

df = raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
})

for c in ["Location", "Date Sampled", "Parameter", "Result"]:
    if c not in df.columns:
        raise ValueError(f"Missing required column: {c}")
    df[c] = df[c].fillna("").astype(str).str.strip()

dbg = df.loc[
    (df["Location"] == "SIMR-3 S1") &
    (df["Parameter"] == "Tritium")
].copy()

dbg["Date Sampled_dt"] = pd.to_datetime(dbg["Date Sampled"], errors="coerce")

dbg = dbg.sort_values(
    ["Date Sampled_dt", "Result"],
    ascending=[False, False],
    na_position="last"
).reset_index(drop=True)

display(dbg[["Location", "Date Sampled", "Parameter", "Result"]])
print(f"Rows found: {len(dbg)}")

    Location Date Sampled Parameter  Result
0  SIMR-3 S1   06-05-2026   Tritium    -100
1  SIMR-3 S1   06-05-2026   Tritium    -100
2  SIMR-3 S1   03-18-2026   Tritium    4.00
3  SIMR-3 S1   03-18-2026   Tritium    4.00
4  SIMR-3 S1   03-18-2026   Tritium  39.531
5  SIMR-3 S1   03-18-2026   Tritium  39.531
6  SIMR-3 S1   03-18-2026   Tritium  25.684
7  SIMR-3 S1   03-18-2026   Tritium  25.684
8  SIMR-3 S1   03-18-2026   Tritium    21.7
9  SIMR-3 S1   03-18-2026   Tritium    21.7

Rows found: 10

In [10]:
# Cell 11 — Apply tritium replacements from tritium review table
#
# Rules:
# - Use Tritium_1 for all sites
# - Use Tritium_2 for SIMR-3 S1 only
# - Update Tritium in the reviewed/backfilled matrix
# - Update Sample_Date additively by appending " **"
# - Preserve existing Sample_Date text, including any existing " *"
# - Do not remove the separating space before stars
#
# Inputs:
# - Results/synoptic_location_reviewed_backfilled.xlsx
# - Results/tritium_last5_review.csv
#
# Output:
# - Results/synoptic_location_reviewed_backfilled_tritium.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

MATRIX_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled.xlsx"
TRITIUM_REVIEW_FILE = RESULTS_DIR / "tritium_last5_review.csv"

OUT_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium.xlsx"

TARGET_ANALYTE = "Tritium"
SPECIAL_SITE = "SIMR-3 S1"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def to_num_or_nan(x):
    return pd.to_numeric(pd.Series([x]), errors="coerce").iloc[0]

def normalize_site(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def append_double_star(sample_date_value):
    s = "" if pd.isna(sample_date_value) else str(sample_date_value).strip()
    if s == "":
        return " **"
    if s.endswith(" **"):
        return s
    return s + " **"

# ------------------------------------------------------------------
# Read matrix
# ------------------------------------------------------------------
mat = pd.read_excel(MATRIX_FILE, dtype=object)
mat.columns = [str(c).strip() for c in mat.columns]

required_matrix_cols = ["Location_ID", "Sample_Date", TARGET_ANALYTE]
missing_matrix = [c for c in required_matrix_cols if c not in mat.columns]
if missing_matrix:
    raise ValueError(f"Matrix file missing required columns: {missing_matrix}")

mat["Location_ID"] = mat["Location_ID"].fillna("").astype(str).str.strip()

# ------------------------------------------------------------------
# Read tritium review table
# Two-row-per-site structure:
# - row 1 = values
# - row 2 = dates
# ------------------------------------------------------------------
tri = pd.read_csv(TRITIUM_REVIEW_FILE, dtype=object)
tri.columns = [str(c).strip() for c in tri.columns]

required_tri_cols = ["Site", "Tritium_1", "Tritium_2"]
missing_tri = [c for c in required_tri_cols if c not in tri.columns]
if missing_tri:
    raise ValueError(f"Tritium review file missing required columns: {missing_tri}")

if len(tri) % 2 != 0:
    raise ValueError("Tritium review CSV must have an even number of rows (two rows per site).")

# ------------------------------------------------------------------
# Parse chosen replacement values/dates
# - default site choice: Tritium_1
# - special site choice: Tritium_2
# ------------------------------------------------------------------
choice_map = {}

for i in range(0, len(tri), 2):
    value_row = tri.iloc[i]
    date_row = tri.iloc[i + 1]

    site = normalize_site(value_row["Site"])
    if site == "":
        raise ValueError(f"Expected site name in tritium review row {i + 1}.")

    chosen_col = "Tritium_2" if site == SPECIAL_SITE else "Tritium_1"

    raw_val = value_row.get(chosen_col, "")
    raw_date = date_row.get(chosen_col, "")

    val_str = "" if pd.isna(raw_val) else str(raw_val).strip()
    date_str = "" if pd.isna(raw_date) else str(raw_date).strip()

    num_val = to_num_or_nan(val_str)
    if pd.isna(num_val):
        continue

    choice_map[site] = {
        "value": float(num_val),
        "date": date_str,
        "source_col": chosen_col,
    }

# ------------------------------------------------------------------
# Apply replacements
# ------------------------------------------------------------------
out = mat.copy()
sites_touched = []
dates_used = []

for row_idx, row in out.iterrows():
    site = row["Location_ID"]
    if site not in choice_map:
        continue

    payload = choice_map[site]

    out.at[row_idx, TARGET_ANALYTE] = payload["value"]
    out.at[row_idx, "Sample_Date"] = append_double_star(out.at[row_idx, "Sample_Date"])

    sites_touched.append(site)
    dates_used.append({
        "Site": site,
        "Chosen_Column": payload["source_col"],
        "Chosen_Date": payload["date"],
        "Chosen_Value": payload["value"],
    })

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out.to_excel(OUT_FILE, index=False)

audit_df = pd.DataFrame(dates_used)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Tritium replacements applied: {len(sites_touched):,}")

if not audit_df.empty:
    print("\nApplied replacement summary:")
    display(audit_df)
else:
    print("No tritium replacements were applied.")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed_backfilled_tritium.xlsx
Tritium replacements applied: 91

Applied replacement summary:

         Site Chosen_Column Chosen_Date  Chosen_Value
0      CRPZ-1     Tritium_1  2026-05-08        51.900
1     CRPZ-2A     Tritium_1  2026-05-14        62.720
2     CRPZ-2B     Tritium_1  2018-12-12       113.479
3      CRPZ-3     Tritium_1  2026-05-08        22.276
4      CRPZ-4     Tritium_1  2026-05-06         3.348
..        ...           ...         ...           ...
86       R-76     Tritium_1  2026-05-21        22.607
87       R-80     Tritium_1  2026-06-13         0.798
88     SIMR-2     Tritium_1  2025-11-06         0.415
89  SIMR-3 S1     Tritium_2  2026-03-18        39.531
90  SIMR-3 S2     Tritium_1  2026-05-12         9.857

[91 rows x 4 columns]

In [11]:
# Cell 11 — Apply tritium replacements from tritium review table
#
# Corrected rules:
# - Only fill rows where Tritium is currently blank/missing
# - Keep existing Tritium values unchanged
# - Use Tritium_1 for all sites
# - Use Tritium_2 for SIMR-3 S1 only
# - Only rows that actually receive a new Tritium fill get " **" appended to Sample_Date
# - Preserve existing Sample_Date text, including any existing " *"
#
# Inputs:
# - Results/synoptic_location_reviewed_backfilled.xlsx
# - Results/tritium_last5_review.csv
#
# Output:
# - Results/synoptic_location_reviewed_backfilled_tritium.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

MATRIX_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled.xlsx"
TRITIUM_REVIEW_FILE = RESULTS_DIR / "tritium_last5_review.csv"

OUT_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium.xlsx"

TARGET_ANALYTE = "Tritium"
SPECIAL_SITE = "SIMR-3 S1"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def to_num_or_nan(x):
    return pd.to_numeric(pd.Series([x]), errors="coerce").iloc[0]

def normalize_site(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def is_blank_cell(x):
    if pd.isna(x):
        return True
    s = str(x).strip()
    return s == ""

def append_double_star(sample_date_value):
    s = "" if pd.isna(sample_date_value) else str(sample_date_value).strip()
    if s == "":
        return " **"
    if s.endswith(" **"):
        return s
    return s + " **"

# ------------------------------------------------------------------
# Read matrix
# ------------------------------------------------------------------
mat = pd.read_excel(MATRIX_FILE, dtype=object)
mat.columns = [str(c).strip() for c in mat.columns]

required_matrix_cols = ["Location_ID", "Sample_Date", TARGET_ANALYTE]
missing_matrix = [c for c in required_matrix_cols if c not in mat.columns]
if missing_matrix:
    raise ValueError(f"Matrix file missing required columns: {missing_matrix}")

mat["Location_ID"] = mat["Location_ID"].fillna("").astype(str).str.strip()

# ------------------------------------------------------------------
# Read tritium review table
# Two-row-per-site structure:
# - row 1 = values
# - row 2 = dates
# ------------------------------------------------------------------
tri = pd.read_csv(TRITIUM_REVIEW_FILE, dtype=object)
tri.columns = [str(c).strip() for c in tri.columns]

required_tri_cols = ["Site", "Tritium_1", "Tritium_2"]
missing_tri = [c for c in required_tri_cols if c not in tri.columns]
if missing_tri:
    raise ValueError(f"Tritium review file missing required columns: {missing_tri}")

if len(tri) % 2 != 0:
    raise ValueError("Tritium review CSV must have an even number of rows (two rows per site).")

# ------------------------------------------------------------------
# Parse chosen replacement values/dates
# - default site choice: Tritium_1
# - special site choice: Tritium_2
# ------------------------------------------------------------------
choice_map = {}

for i in range(0, len(tri), 2):
    value_row = tri.iloc[i]
    date_row = tri.iloc[i + 1]

    site = normalize_site(value_row["Site"])
    if site == "":
        raise ValueError(f"Expected site name in tritium review row {i + 1}.")

    chosen_col = "Tritium_2" if site == SPECIAL_SITE else "Tritium_1"

    raw_val = value_row.get(chosen_col, "")
    raw_date = date_row.get(chosen_col, "")

    val_str = "" if pd.isna(raw_val) else str(raw_val).strip()
    date_str = "" if pd.isna(raw_date) else str(raw_date).strip()

    num_val = to_num_or_nan(val_str)
    if pd.isna(num_val):
        continue

    choice_map[site] = {
        "value": float(num_val),
        "date": date_str,
        "source_col": chosen_col,
    }

# ------------------------------------------------------------------
# Apply replacements only where Tritium is currently blank
# ------------------------------------------------------------------
out = mat.copy()
sites_touched = []
dates_used = []

for row_idx, row in out.iterrows():
    site = row["Location_ID"]
    if site not in choice_map:
        continue

    current_val = out.at[row_idx, TARGET_ANALYTE]
    if not is_blank_cell(current_val):
        continue

    payload = choice_map[site]

    out.at[row_idx, TARGET_ANALYTE] = payload["value"]
    out.at[row_idx, "Sample_Date"] = append_double_star(out.at[row_idx, "Sample_Date"])

    sites_touched.append(site)
    dates_used.append({
        "Site": site,
        "Chosen_Column": payload["source_col"],
        "Chosen_Date": payload["date"],
        "Chosen_Value": payload["value"],
    })

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out.to_excel(OUT_FILE, index=False)

audit_df = pd.DataFrame(dates_used)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Tritium fills applied to previously blank cells: {len(sites_touched):,}")

if not audit_df.empty:
    print("\nApplied replacement summary:")
    display(audit_df)
else:
    print("No tritium replacements were applied.")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed_backfilled_tritium.xlsx
Tritium fills applied to previously blank cells: 21

Applied replacement summary:

       Site Chosen_Column Chosen_Date  Chosen_Value
0   CRPZ-2A     Tritium_1  2026-05-14        62.720
1    CRPZ-4     Tritium_1  2026-05-06         3.348
2    CRPZ-5     Tritium_1  2026-05-14        23.214
3      PM-3     Tritium_1  2021-12-14         4.012
4       R-1     Tritium_1  2025-11-13         0.252
5     R-10a     Tritium_1  2025-11-18         1.233
6      R-11     Tritium_1  2026-05-20         0.090
7   R-12 S2     Tritium_1  2025-07-16        21.015
8      R-13     Tritium_1  2025-11-07         1.603
9      R-15     Tritium_1  2025-11-21        48.000
10  R-33 S2     Tritium_1  2025-11-12         0.512
11     R-36     Tritium_1  2026-05-06         5.268
12  R-43 S1     Tritium_1  2026-05-05         0.538
13  R-43 S2     Tritium_1  2026-05-04         0.168
14  R-50 S2     Tritium_1  2026-05-15         1.820
15     R-62     Tritium_1  2026-05-06        16.882
16  R-70 S1     Tritium_1  2026-05-13         0.488
17  R-70 S2     Tritium_1  2025-11-24        14.353
18  R-71 S2     Tritium_1  2025-11-14         1.557
19     R-76     Tritium_1  2026-05-21        22.607
20   SIMR-2     Tritium_1  2025-11-06         0.415

In [12]:
# Cell 12 — Build qualified synoptic workbook with companion qualifier columns
#
# Purpose:
# - Read synoptic_location_reviewed_backfilled_tritium.xlsx
# - Add a companion *_Qualifier column for every analyte column
# - Look up Validation Qualifier from WedgeWells_FullTimeline.csv
# - Use best available provenance from:
#     1. tritium_last5_review.csv
#     2. synoptic_wide_backfill_candidates.csv
#     3. row Sample_Date when it is a clean ISO date
#     4. fallback exact value match without date
#
# Inputs:
# - Results/synoptic_location_reviewed_backfilled_tritium.xlsx
# - Results/WedgeWells_FullTimeline.csv
# - Results/synoptic_wide_backfill_candidates.csv
# - Results/tritium_last5_review.csv
#
# Output:
# - Results/synoptic_location_reviewed_backfilled_tritium_qualified.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

FINAL_MATRIX_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium.xlsx"
LONG_FILE = RESULTS_DIR / "WedgeWells_FullTimeline.csv"
WIDE_BACKFILL_FILE = RESULTS_DIR / "synoptic_wide_backfill_candidates.csv"
TRITIUM_REVIEW_FILE = RESULTS_DIR / "tritium_last5_review.csv"

OUT_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium_qualified.xlsx"

KNOWN_METADATA_COLS = ["Location_ID", "Sample_Date", "Cat", "Location_Type"]
TRITIUM_NAME = "Tritium"
SPECIAL_SITE = "SIMR-3 S1"
QUAL_COL_LONG = "Validation Qualifier"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def is_blank(x):
    if pd.isna(x):
        return True
    return str(x).strip() == ""

def normalize_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def to_num_or_nan(x):
    return pd.to_numeric(pd.Series([x]), errors="coerce").iloc[0]

def parse_isoish_date_from_sample_date(x):
    """
    Accept clean dates like:
      2025-08-14
      2025-08-14 *
      2025-08-14 * **
      2025-08-14 **
    Return YYYY-MM-DD or "" if no clean parse.
    """
    s = normalize_text(x)
    if s == "":
        return ""
    base = s.split()[0]
    dt = pd.to_datetime(base, errors="coerce")
    if pd.isna(dt):
        return ""
    return dt.strftime("%Y-%m-%d")

def qualifier_rank(q):
    return 0 if normalize_text(q) != "" else 1

# ------------------------------------------------------------------
# Read final matrix
# ------------------------------------------------------------------
mat = pd.read_excel(FINAL_MATRIX_FILE, dtype=object)
mat.columns = [str(c).strip() for c in mat.columns]

required_mat = ["Location_ID", "Sample_Date"]
missing_mat = [c for c in required_mat if c not in mat.columns]
if missing_mat:
    raise ValueError(f"Final matrix missing required columns: {missing_mat}")

mat["Location_ID"] = mat["Location_ID"].fillna("").astype(str).str.strip()
mat["Sample_Date"] = mat["Sample_Date"].fillna("").astype(str).str.strip()

metadata_cols = [c for c in KNOWN_METADATA_COLS if c in mat.columns]
analyte_cols = [c for c in mat.columns if c not in metadata_cols]

# ------------------------------------------------------------------
# Read long-form source
# ------------------------------------------------------------------
raw = pd.read_csv(LONG_FILE, dtype=str, low_memory=False, encoding="utf-8", encoding_errors="replace")
raw.columns = [str(c).strip() for c in raw.columns]

df = raw.rename(columns={
    "Location ID": "Location",
    "Sample Date": "Date Sampled",
    "Parameter Name": "Parameter",
    "Report Result": "Result",
    QUAL_COL_LONG: "Qualifier",
})

required_long = ["Location", "Date Sampled", "Parameter", "Result", "Qualifier"]
missing_long = [c for c in required_long if c not in df.columns]
if missing_long:
    raise ValueError(f"Long-form source missing required columns: {missing_long}")

for c in ["Location", "Date Sampled", "Parameter", "Result", "Qualifier"]:
    df[c] = df[c].fillna("").astype(str).str.strip()

df["Date Sampled_dt"] = pd.to_datetime(df["Date Sampled"], errors="coerce")
df["Date_ISO"] = df["Date Sampled_dt"].dt.strftime("%Y-%m-%d")

res_core = (
    df["Result"]
    .str.replace(r"^[<>~=]+\s*", "", regex=True)
    .str.replace(",", "", regex=False)
)
df["result_num"] = pd.to_numeric(
    res_core.str.extract(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)")[0],
    errors="coerce"
)

df["Location"] = df["Location"].astype(str).str.strip()
df["Parameter"] = df["Parameter"].astype(str).str.strip()

# ------------------------------------------------------------------
# Read wide backfill provenance
# two-row-per-site structure: values row, dates row
# ------------------------------------------------------------------
wide_prov = {}  # wide_prov[site][analyte] = {"value": float, "date": "YYYY-MM-DD"}

bf = pd.read_csv(WIDE_BACKFILL_FILE, dtype=object)
bf.columns = [str(c).strip() for c in bf.columns]

if "Site" not in bf.columns:
    raise ValueError("Wide backfill file must contain 'Site' column.")

if len(bf) % 2 != 0:
    raise ValueError("Wide backfill file must have an even number of rows (two rows per site).")

for i in range(0, len(bf), 2):
    value_row = bf.iloc[i]
    date_row = bf.iloc[i + 1]

    site = normalize_text(value_row["Site"])
    if site == "":
        raise ValueError(f"Expected site name in wide backfill row {i + 1}.")

    wide_prov[site] = {}

    for analyte in analyte_cols:
        if analyte not in bf.columns:
            continue

        val = normalize_text(value_row.get(analyte, ""))
        dt = normalize_text(date_row.get(analyte, ""))

        num = to_num_or_nan(val)
        if pd.isna(num):
            continue

        dt_iso = ""
        if dt != "" and dt.upper() != "NF":
            dt_parsed = pd.to_datetime(dt, errors="coerce")
            if pd.notna(dt_parsed):
                dt_iso = dt_parsed.strftime("%Y-%m-%d")

        wide_prov[site][analyte] = {
            "value": float(num),
            "date": dt_iso,
        }

# ------------------------------------------------------------------
# Read tritium special provenance
# two-row-per-site structure: values row, dates row
# final chosen rule:
# - all sites use Tritium_1
# - SIMR-3 S1 uses Tritium_2
# ------------------------------------------------------------------
tritium_prov = {}  # tritium_prov[site] = {"value": float, "date": "YYYY-MM-DD"}

tri = pd.read_csv(TRITIUM_REVIEW_FILE, dtype=object)
tri.columns = [str(c).strip() for c in tri.columns]

required_tri = ["Site", "Tritium_1", "Tritium_2"]
missing_tri = [c for c in required_tri if c not in tri.columns]
if missing_tri:
    raise ValueError(f"Tritium review file missing required columns: {missing_tri}")

if len(tri) % 2 != 0:
    raise ValueError("Tritium review file must have an even number of rows (two rows per site).")

for i in range(0, len(tri), 2):
    value_row = tri.iloc[i]
    date_row = tri.iloc[i + 1]

    site = normalize_text(value_row["Site"])
    if site == "":
        raise ValueError(f"Expected site name in tritium review row {i + 1}.")

    chosen_col = "Tritium_2" if site == SPECIAL_SITE else "Tritium_1"

    val = normalize_text(value_row.get(chosen_col, ""))
    dt = normalize_text(date_row.get(chosen_col, ""))

    num = to_num_or_nan(val)
    if pd.isna(num):
        continue

    dt_iso = ""
    dt_parsed = pd.to_datetime(dt, errors="coerce")
    if pd.notna(dt_parsed):
        dt_iso = dt_parsed.strftime("%Y-%m-%d")

    tritium_prov[site] = {
        "value": float(num),
        "date": dt_iso,
    }

# ------------------------------------------------------------------
# Qualifier lookup
# ------------------------------------------------------------------
def find_best_qualifier(site, analyte, final_value, preferred_date_iso=""):
    """
    Match order:
    1. exact site + analyte + preferred date + numeric value
    2. exact site + analyte + preferred date
    3. exact site + analyte + numeric value
    4. exact site + analyte
    In all cases prefer nonblank qualifier, then first row.
    """
    if site == "" or analyte == "":
        return ""

    final_num = to_num_or_nan(final_value)

    base = df.loc[
        (df["Location"] == site) &
        (df["Parameter"] == analyte)
    ].copy()

    if base.empty:
        return ""

    # 1
    if preferred_date_iso != "" and pd.notna(final_num):
        q1 = base.loc[
            (base["Date_ISO"] == preferred_date_iso) &
            (base["result_num"] == float(final_num))
        ].copy()
        if not q1.empty:
            q1["qrank"] = q1["Qualifier"].map(qualifier_rank)
            q1 = q1.sort_values(["qrank", "Date Sampled_dt"], ascending=[True, False], na_position="last")
            return normalize_text(q1.iloc[0]["Qualifier"])

    # 2
    if preferred_date_iso != "":
        q2 = base.loc[(base["Date_ISO"] == preferred_date_iso)].copy()
        if not q2.empty:
            if pd.notna(final_num):
                q2["valdiff"] = (q2["result_num"] - float(final_num)).abs()
            else:
                q2["valdiff"] = np.nan
            q2["qrank"] = q2["Qualifier"].map(qualifier_rank)
            q2 = q2.sort_values(["qrank", "valdiff", "Date Sampled_dt"], ascending=[True, True, False], na_position="last")
            return normalize_text(q2.iloc[0]["Qualifier"])

    # 3
    if pd.notna(final_num):
        q3 = base.loc[(base["result_num"] == float(final_num))].copy()
        if not q3.empty:
            q3["qrank"] = q3["Qualifier"].map(qualifier_rank)
            q3 = q3.sort_values(["qrank", "Date Sampled_dt"], ascending=[True, False], na_position="last")
            return normalize_text(q3.iloc[0]["Qualifier"])

    # 4
    q4 = base.copy()
    q4["qrank"] = q4["Qualifier"].map(qualifier_rank)
    if pd.notna(final_num):
        q4["valdiff"] = (q4["result_num"] - float(final_num)).abs()
        sort_cols = ["qrank", "valdiff", "Date Sampled_dt"]
        ascending = [True, True, False]
    else:
        sort_cols = ["qrank", "Date Sampled_dt"]
        ascending = [True, False]
    q4 = q4.sort_values(sort_cols, ascending=ascending, na_position="last")
    return normalize_text(q4.iloc[0]["Qualifier"])

# ------------------------------------------------------------------
# Build output with companion qualifier columns
# ------------------------------------------------------------------
out = pd.DataFrame()
for col in metadata_cols:
    out[col] = mat[col]

qualifier_hits = 0
qualifier_blanks = 0

for analyte in analyte_cols:
    out[analyte] = mat[analyte]
    qual_col = f"{analyte}_Qualifier"
    quals = []

    for _, row in mat.iterrows():
        site = normalize_text(row["Location_ID"])
        final_value = row[analyte]

        if is_blank(final_value):
            quals.append("")
            continue

        preferred_date_iso = ""

        # Tritium special provenance takes priority
        if analyte == TRITIUM_NAME and site in tritium_prov:
            prov = tritium_prov[site]
            final_num = to_num_or_nan(final_value)
            if pd.notna(final_num) and float(final_num) == prov["value"]:
                preferred_date_iso = prov["date"]

        # Wide backfill provenance
        if preferred_date_iso == "" and site in wide_prov and analyte in wide_prov[site]:
            prov = wide_prov[site][analyte]
            final_num = to_num_or_nan(final_value)
            if pd.notna(final_num) and float(final_num) == prov["value"]:
                preferred_date_iso = prov["date"]

        # Fall back to row Sample_Date if it is a clean ISO date
        if preferred_date_iso == "":
            preferred_date_iso = parse_isoish_date_from_sample_date(row["Sample_Date"])

        q = find_best_qualifier(
            site=site,
            analyte=analyte,
            final_value=final_value,
            preferred_date_iso=preferred_date_iso
        )
        quals.append(q)

        if normalize_text(q) == "":
            qualifier_blanks += 1
        else:
            qualifier_hits += 1

    out[qual_col] = quals

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
out.to_excel(OUT_FILE, index=False)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Rows written: {len(out):,}")
print(f"Analyte columns qualified: {len(analyte_cols):,}")
print(f"Nonblank qualifiers assigned: {qualifier_hits:,}")
print(f"Blank/unresolved qualifiers: {qualifier_blanks:,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed_backfilled_tritium_qualified.xlsx
Rows written: 91
Analyte columns qualified: 46
Nonblank qualifiers assigned: 4,181
Blank/unresolved qualifiers: 2

In [14]:
# Cell 13 — Insert U/n summary row into each qualifier column
#
# Purpose:
# - Read the qualified workbook
# - Compute U/n for each analyte:
#     U = count where qualifier == "U"
#     n = count where analyte value is nonblank
# - Insert a new top row
# - Write "U/n=<ratio>" into each *_Qualifier column in that top row
# - Save to a new workbook
#
# Input:
# - Results/synoptic_location_reviewed_backfilled_tritium_qualified.xlsx
#
# Output:
# - Results/synoptic_location_reviewed_backfilled_tritium_qualified_with_U_over_n.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

IN_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium_qualified.xlsx"
OUT_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium_qualified_with_U_over_n.xlsx"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def is_nonblank(x):
    if pd.isna(x):
        return False
    return str(x).strip() != ""

# ------------------------------------------------------------------
# Read file
# ------------------------------------------------------------------
df = pd.read_excel(IN_FILE, dtype=object)
df.columns = [str(c).strip() for c in df.columns]

qualifier_cols = [c for c in df.columns if c.endswith("_Qualifier")]
analyte_cols = [c[:-10] for c in qualifier_cols if c[:-10] in df.columns]

# ------------------------------------------------------------------
# Build top summary row
# ------------------------------------------------------------------
summary_row = {col: "" for col in df.columns}
summary_row["Location_ID"] = "U/n summary"

for analyte in analyte_cols:
    qual_col = f"{analyte}_Qualifier"

    value_mask = df[analyte].apply(is_nonblank)
    n = int(value_mask.sum())

    u_mask = df[qual_col].fillna("").astype(str).str.strip().str.upper() == "U"
    U = int((value_mask & u_mask).sum())

    if n == 0:
        summary_row[qual_col] = "U/n=NA"
    else:
        ratio = U / n
        summary_row[qual_col] = f"U/n={ratio:.3f}"

# ------------------------------------------------------------------
# Insert row at top and save
# ------------------------------------------------------------------
out = pd.concat([pd.DataFrame([summary_row]), df], ignore_index=True)
out.to_excel(OUT_FILE, index=False)

print("Saved:")
print(f" - {OUT_FILE}")
print(f"Qualifier columns annotated: {len(qualifier_cols):,}")

Saved:
 - C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\Results\synoptic_location_reviewed_backfilled_tritium_qualified_with_U_over_n.xlsx
Qualifier columns annotated: 46

In [13]:
# Cell 13 — U / n ratio for each analyte column in the qualified workbook
#
# Definition:
# - U = count of rows where {Analyte}_Qualifier == "U"
# - n = count of rows where {Analyte} has a nonblank value
# - U_over_n = U / n
#
# Input:
# - Results/synoptic_location_reviewed_backfilled_tritium_qualified.xlsx

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------
WORK_DIR = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
RESULTS_DIR = WORK_DIR / "Results"

QUALIFIED_FILE = RESULTS_DIR / "synoptic_location_reviewed_backfilled_tritium_qualified.xlsx"

KNOWN_METADATA_COLS = ["Location_ID", "Sample_Date", "Cat", "Location_Type"]

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def is_nonblank(x):
    if pd.isna(x):
        return False
    return str(x).strip() != ""

# ------------------------------------------------------------------
# Read file
# ------------------------------------------------------------------
df = pd.read_excel(QUALIFIED_FILE, dtype=object)
df.columns = [str(c).strip() for c in df.columns]

qualifier_cols = [c for c in df.columns if c.endswith("_Qualifier")]
analyte_cols = [c[:-10] for c in qualifier_cols if c[:-10] in df.columns]

results = []

for analyte in analyte_cols:
    qual_col = f"{analyte}_Qualifier"

    value_mask = df[analyte].apply(is_nonblank)
    n = int(value_mask.sum())

    u_mask = df[qual_col].fillna("").astype(str).str.strip().str.upper() == "U"
    U = int((value_mask & u_mask).sum())

    ratio = np.nan if n == 0 else U / n

    results.append({
        "Analyte": analyte,
        "U_count": U,
        "n_nonblank": n,
        "U_over_n": ratio
    })

ratio_df = pd.DataFrame(results).sort_values(
    ["U_over_n", "Analyte"],
    ascending=[False, True],
    na_position="last"
).reset_index(drop=True)

display(ratio_df)

                                Analyte  U_count  n_nonblank  U_over_n
0                                   Tin       91          91  1.000000
1                             Beryllium       90          91  0.989011
2                               Cadmium       90          91  0.989011
3                                Silver       89          91  0.978022
4                              Thallium       88          91  0.967033
5                                Cobalt       87          91  0.956044
6                               Mercury       87          91  0.956044
7                              Antimony       86          91  0.945055
8                                  Lead       84          91  0.923077
9                              Selenium       84          91  0.923077
10                             Aluminum       81          91  0.890110
11                                 Iron       76          91  0.835165
12                              Arsenic       74          91  0.813187
13                            Manganese       72          91  0.791209
14                  Ammonia as Nitrogen       71          91  0.780220
15                       Alkalinity-CO3       70          91  0.769231
16        Total Phosphate as Phosphorus       67          91  0.736264
17                               Copper       63          91  0.692308
18                              Bromide       56          91  0.615385
19                                 Zinc       51          91  0.560440
20                                Boron       40          91  0.439560
21                               Nickel       39          91  0.428571
22                 Total Organic Carbon       38          90  0.422222
23                              Tritium       36          91  0.395604
24              Total Kjeldahl Nitrogen       22          90  0.244444
25                             Chromium       21          91  0.230769
26                           Molybdenum        4          91  0.043956
27                              Uranium        2          91  0.021978
28          Nitrate-Nitrite as Nitrogen        1          91  0.010989
29                          Perchlorate        1          91  0.010989
30                             Vanadium        1          91  0.010989
31  Acidity or Alkalinity of a solution        0          91  0.000000
32                  Alkalinity-CO3+HCO3        0          91  0.000000
33                               Barium        0          91  0.000000
34                              Calcium        0          91  0.000000
35                             Chloride        0          91  0.000000
36                             Fluoride        0          91  0.000000
37                             Hardness        0          91  0.000000
38                            Magnesium        0          91  0.000000
39                            Potassium        0          91  0.000000
40                      Silicon Dioxide        0          90  0.000000
41                               Sodium        0          91  0.000000
42                 Specific Conductance        0          91  0.000000
43                            Strontium        0          91  0.000000
44                              Sulfate        0          91  0.000000
45               Total Dissolved Solids        0          91  0.000000

In [9]:
import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------
base = Path(r"C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun")
infile = base / "ClosestToSynoptic_R80Zonal.csv"
outfile = base / "R-80 data rotated.csv"

# ------------------------------------------------------------------
# Load synoptic long file
# Expected columns: location, date, analyte, value, detect, unit
# ------------------------------------------------------------------
df = pd.read_csv(infile)

# ------------------------------------------------------------------
# Clean basics
# ------------------------------------------------------------------
df["location"] = df["location"].astype(str).str.strip()
df["analyte"] = df["analyte"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["value"] = pd.to_numeric(df["value"], errors="coerce")
df["unit"] = df["unit"].astype(str).str.strip()

# ------------------------------------------------------------------
# Normalize units text
# ------------------------------------------------------------------
def norm_unit(u):
    s = str(u).strip().lower()
    s = s.replace("µ", "u").replace("μ", "u")
    s = s.replace(" ", "")
    return s

df["_unit_norm"] = df["unit"].apply(norm_unit)

# ------------------------------------------------------------------
# Convert only selected analytes where units are dissimilar
# Ca, K, Mg, Na: ug/L -> mg/L ; mg/L unchanged
# ------------------------------------------------------------------
convert_analytes = {"Ca", "K", "Mg", "Na", "Calcium", "Potassium", "Magnesium", "Sodium"}

is_convert_analyte = df["analyte"].isin(convert_analytes)
is_ugL = df["_unit_norm"].isin({"ug/l", "ugl", "ug/l.", "µg/l", "μg/l"})
is_mgL = df["_unit_norm"].isin({"mg/l", "mgl", "mg/l."})

df.loc[is_convert_analyte & is_ugL, "value"] = df.loc[is_convert_analyte & is_ugL, "value"] / 1000.0
df.loc[is_convert_analyte & (is_ugL | is_mgL), "unit"] = "mg/L"

# ------------------------------------------------------------------
# Rotate long -> wide
# Use median if duplicate location/date/analyte rows exist
# ------------------------------------------------------------------
wide = (
    df.pivot_table(
        index=["location", "date"],
        columns="analyte",
        values="value",
        aggfunc="median"
    )
    .reset_index()
)

# flatten column index if needed
wide.columns.name = None

# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------
wide.to_csv(outfile, index=False)

# ------------------------------------------------------------------
# Report
# ------------------------------------------------------------------
n_conv = int((is_convert_analyte & is_ugL).sum())

print(f"Loaded: {infile}")
print(f"Saved:  {outfile}")
print(f"Rows in long file: {len(df):,}")
print(f"Rows converted ug/L -> mg/L for Ca/K/Mg/Na: {n_conv:,}")
print(f"Rotated rows: {len(wide):,}")
print(f"Rotated columns: {len(wide.columns):,}")

print("\nPreview:")
display(wide.head(20))

Loaded: C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\ClosestToSynoptic_R80Zonal.csv
Saved:  C:\Users\kylian.robinson\MapRebuildItems\R80_ZonalRun\R-80 data rotated.csv
Rows in long file: 25,441
Rows converted ug/L -> mg/L for Ca/K/Mg/Na: 28
Rotated rows: 132
Rotated columns: 416

Preview:

,location,date,"1,3,5-Naphthalene trisulfonic acid","1,3,6-Naphthalene trisulfonic acid","1,5-Naphthalenedisulfonic acid","1,6-Naphthalene disulfonic acid",1-Naphthalene sulfonic acid,11-Chloroeicosafluoro-3-oxaundecane-1-sulfonic acid,"1H, 1H, 2H, 2H-Perfluorohexanesulfonic acid","1H, 1H, 2H, 2H-perfluorodecane sulfonic acid",...,Uranium-235/236,Uranium-238,Vanadium,Vinyl Chloride,Vinyl acetate,Xylene (Total),"Xylene[1,2-]","Xylene[1,3-]+Xylene[1,4-]",Zinc,n-Heptane
0,CRPZ-1,2026-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.950,NaN,NaN,NaN,NaN,NaN,3.300,NaN
1,CRPZ-2A,2026-05-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.280,NaN,NaN,NaN,NaN,NaN,6.270,NaN
2,CRPZ-3,2026-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.520,NaN,NaN,NaN,NaN,NaN,3.300,NaN
3,CRPZ-4,2026-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.120,NaN,NaN,NaN,NaN,NaN,3.300,NaN
4,CRPZ-5,2026-05-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.200,NaN,NaN,NaN,NaN,NaN,3.300,NaN
5,CrEX-1,2026-05-27,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.855,NaN,NaN,NaN,NaN,NaN,7.695,NaN
6,CrEX-2,2026-05-27,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,5.120,NaN,NaN,NaN,NaN,NaN,268.000,NaN
7,CrEX-3,2026-05-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CrEX-4,2026-05-27,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,6.040,NaN,NaN,NaN,NaN,NaN,8.250,NaN
9,CrIN-1,2025-04-24,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.315,NaN,NaN,NaN,NaN,NaN,24.600,NaN
10,CrIN-2,2025-04-24,0.0314,0.01980,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.450,NaN,NaN,NaN,NaN,NaN,21.100,NaN
11,CrIN-3,2024-08-15,0.0020,0.00949,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.215,NaN,NaN,NaN,NaN,NaN,14.900,NaN
12,CrIN-4,2024-08-15,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.970,NaN,NaN,NaN,NaN,NaN,18.000,NaN
13,CrIN-5,2024-08-15,0.0020,0.00200,0.002,0.002,0.002,NaN,NaN,NaN,...,NaN,NaN,4.635,NaN,NaN,NaN,NaN,NaN,12.050,NaN
14,MDA-L SVE-1 WEST,2026-05-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.500,NaN,NaN,16.000,16.0,NaN,23.0
15,MDA-L SVE-2 EAST,2026-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.500,NaN,NaN,21.000,16.0,NaN,23.0
16,PM-1,2025-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11.200,NaN,NaN,NaN,NaN,NaN,6.970,NaN
17,PM-2,2025-06-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0229,0.106,6.740,0.333,1.67,NaN,0.333,0.5,5.920,NaN
18,PM-4,2025-10-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PM-5,2026-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
##6/29 tweak version
#!/usr/bin/env python3
r"""
Pivot EDD long table to n×p matrix, then minimal housekeeping:
 - normalize concentration units in the LONG table using unit metadata,
 - ensure HCO3(-1) and CO3(-2) exist; compute Alkalinity-CO3+HCO3, then drop HCO3(-1) and CO3(-2),
 - rename columns using EDDtoIntellusNames.xlsx (EDD -> Intellus), ensuring NA -> Sodium,
 - drop ALK and TEMP columns from the pivot output,
 - drop NO3+NO2 and TOC if they have numeric values for only two samples.
"""

from pathlib import Path
import numpy as np
import pandas as pd

# --------- PATHS (edit these) ---------
ROOT_DIR = Path("C:/Users/kylian.robinson/MapRebuildItems")
INPUT_EDD_CSV = ROOT_DIR / "compile_odd_GC_forPCA.csv"
MAPPING_XLSX = ROOT_DIR / "EDDtoIntellusNames.xlsx"
OUTPUT_DIR = ROOT_DIR / "V 2.1 items"
OUTPUT_NAME = INPUT_EDD_CSV.stem + "_matrix_repV2.1.csv"
# --------------------------------------

def harmonic_mean(values: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce")
    v = v[np.isfinite(v) & (v > 0)]
    if v.empty:
        return np.nan
    return float(len(v) / np.sum(1.0 / v))

def resolve_col(df: pd.DataFrame, candidates):
    low = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        key = cand.lower().strip()
        if key in low:
            return low[key]
    raise KeyError(f"Could not resolve any of {candidates} in columns: {list(df.columns)}")

def find_ci(cols, name):
    for c in cols:
        if c.strip().lower() == name.strip().lower():
            return c
    return None

def normalize_unit_text(x):
    if x is None:
        return ""
    s = str(x).strip().lower()
    s = s.replace("µ", "u").replace("μ", "u")
    s = s.replace(" ", "")
    return s

def convert_value_by_unit(value, unit_text):
    """
    Convert concentration to mg/L only when unit metadata shows a dissimilar unit.
    Leaves mg/L unchanged.
    """
    if pd.isna(value):
        return np.nan

    u = normalize_unit_text(unit_text)

    mgL_units = {"mg/l", "mgl", "mg/l."}
    ugL_units = {"ug/l", "ugl", "ug/l.", "µg/l", "μg/l"}

    if u in mgL_units:
        return value
    if u in ugL_units:
        return value / 1000.0

    # leave unchanged for unknown units; user can inspect later
    return value

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1) Load EDD (preserve literal strings like 'NA' in Parameter Code)
    df = pd.read_csv(INPUT_EDD_CSV, dtype=str, keep_default_na=False)

    field_col = resolve_col(df, ["field_sample_id", "sampleid", "sample_id"])
    param_col = resolve_col(df, ["parameter_code", "parameter", "parm_code"])
    result_col = resolve_col(df, ["lab_result", "result", "value"])
    unit_col = resolve_col(df, ["lab_units", "units", "unit", "result_unit"])

    # Clean parameter codes
    df[param_col] = df[param_col].astype(str).str.strip()
    blank_mask = (df[param_col] == "") | df[param_col].str.lower().isin({"nan", "none", "null"})
    if blank_mask.any():
        df = df.loc[~blank_mask].copy()

    # Coerce results
    df[result_col] = pd.to_numeric(df[result_col], errors="coerce")

    # 2) Normalize units in LONG table before aggregation/pivot
    df["value_mgL"] = [
        convert_value_by_unit(v, u)
        for v, u in zip(df[result_col], df[unit_col])
    ]

    # Optional reporting
    df["_unit_norm"] = df[unit_col].map(normalize_unit_text)
    print("Unit counts:")
    print(df["_unit_norm"].value_counts(dropna=False).sort_index())

    unknown_units = sorted(set(df["_unit_norm"]) - {"mg/l", "mgl", "mg/l.", "ug/l", "ugl", "ug/l.", ""})
    if unknown_units:
        print("\nUnits left unchanged because they were not recognized:")
        print(unknown_units)

    # 3) Aggregate duplicates per (sample, parameter) using harmonic mean
    agg = (
        df.groupby([field_col, param_col], dropna=False, sort=False)["value_mgL"]
          .apply(harmonic_mean)
          .reset_index()
    )

    # 4) Pivot to n×p matrix
    wide = (
        agg.pivot(index=field_col, columns=param_col, values="value_mgL")
           .sort_index(axis=0)
           .sort_index(axis=1)
    )

    # 5) Drop ALK and TEMP columns
    for drop_name in ["ALK", "TEMP"]:
        col = find_ci(wide.columns, drop_name)
        if col is not None:
            wide = wide.drop(columns=[col])

    # 6) Ensure HCO3(-1) and CO3(-2) exist, compute alkalinity surrogate
    if find_ci(wide.columns, "HCO3(-1)") is None:
        wide["HCO3(-1)"] = 0.0
    if find_ci(wide.columns, "CO3(-2)") is None:
        wide["CO3(-2)"] = 0.0

    hco3_col = find_ci(wide.columns, "HCO3(-1)")
    co3_col = find_ci(wide.columns, "CO3(-2)")

    wide[hco3_col] = pd.to_numeric(wide[hco3_col], errors="coerce").fillna(0.0)
    wide[co3_col] = pd.to_numeric(wide[co3_col], errors="coerce").fillna(0.0)
    wide["Alkalinity-CO3+HCO3"] = wide[hco3_col] + wide[co3_col]

    # 7) Drop bicarbonate/carbonate source columns
    wide = wide.drop(columns=[hco3_col, co3_col], errors="ignore")

    # 8) Rename columns using mapping file
    if MAPPING_XLSX.exists():
        map_df = pd.read_excel(MAPPING_XLSX, dtype=str)
        src = resolve_col(map_df, ["edd", "source", "from"])
        tgt = resolve_col(map_df, ["intellus", "intellus name", "name", "target", "to"])

        mapping = {}
        for _, row in map_df[[src, tgt]].dropna(subset=[src]).iterrows():
            k = str(row[src]).strip()
            v = str(row[tgt]).strip() if not pd.isna(row[tgt]) else k
            if k:
                mapping[k] = v or k

        if "NA" not in mapping:
            mapping["NA"] = "Sodium"

        wide = wide.rename(columns={c: mapping.get(c, c) for c in wide.columns})
        print("Applied EDD->Intellus renames (including NA->Sodium).")
    else:
        na_col = find_ci(wide.columns, "NA")
        if na_col is not None:
            wide = wide.rename(columns={na_col: "Sodium"})
        print(f"Mapping file not found: {MAPPING_XLSX}. Applied NA->Sodium fallback if needed.")

    # 9) Drop sparse NO3+NO2 and TOC
    for candidate in ["NO3+NO2", "TOC"]:
        col = find_ci(wide.columns, candidate)
        if col is not None:
            vals = pd.to_numeric(wide[col], errors="coerce")
            if int(vals.notna().sum()) == 2:
                wide = wide.drop(columns=[col])

    # 10) Save
    out_path = OUTPUT_DIR / OUTPUT_NAME
    wide.to_csv(out_path, na_rep="")
    print(f"Saved n×p matrix to: {out_path}")
    print(f"Rows (samples): {wide.shape[0]} | Columns (parameters): {wide.shape[1]}")

if __name__ == "__main__":
    main()

Unit counts:
_unit_norm
degc      9
mg/l     60
ug/l    268
Name: count, dtype: int64

Units left unchanged because they were not recognized:
['degc']
Applied EDD->Intellus renames (including NA->Sodium).
Saved n×p matrix to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\compile_odd_GC_forPCA_matrix_repV2.1.csv
Rows (samples): 7 | Columns (parameters): 34

In [7]:
#!/usr/bin/env python3
r"""
Pivot EDD long table to n×p matrix, then minimal housekeeping:
 - divide CA, K, MG, NA by 1000 (to mg/L),
 - ensure HCO3(-1) and CO3(-2) exist; compute Alkalinity-CO3+HCO3, then drop HCO3(-1) and CO3(-2),
 - rename columns using EDDtoIntellusNames.xlsx (EDD -> Intellus), ensuring NA -> Sodium,
 - drop ALK and TEMP columns from the pivot output,
 - drop NO3+NO2 and TOC if they have numeric values for only two samples.

Edit file paths here:
 - ROOT_DIR: base folder with inputs
 - INPUT_EDD_CSV: long EDD CSV (must have Field Sample ID, Parameter Code, Lab Result)
 - MAPPING_XLSX: Excel with two columns (EDD, Intellus)
 - OUTPUT_DIR: folder to write the n×p CSV into (V 2.1 items/)
"""

from pathlib import Path
import numpy as np
import pandas as pd

# --------- PATHS (edit these) ---------
ROOT_DIR = Path("C:/Users/kylian.robinson/MapRebuildItems")
INPUT_EDD_CSV = ROOT_DIR / "compile_odd_GC_forPCA.csv"          # long EDD-style table
MAPPING_XLSX = ROOT_DIR / "EDDtoIntellusNames.xlsx"              # two columns: EDD, Intellus
OUTPUT_DIR = ROOT_DIR / "V 2.1 items"                            # write n×p CSV here
OUTPUT_NAME = INPUT_EDD_CSV.stem + "_matrix_repV2.1.csv"                 # output file name
# --------------------------------------

# harmonic mean of positive finite values; NaN if none
def harmonic_mean(values: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce")
    v = v[np.isfinite(v) & (v > 0)]
    if v.empty:
        return np.nan
    return float(len(v) / np.sum(1.0 / v))

def resolve_col(df: pd.DataFrame, candidates):
    low = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        key = cand.lower().strip()
        if key in low:
            return low[key]
    raise KeyError(f"Could not resolve any of {candidates} in columns: {list(df.columns)}")

def find_ci(cols, name):
    """Find actual column by case-insensitive exact match; return None if not found."""
    for c in cols:
        if c.strip().lower() == name.strip().lower():
            return c
    return None

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1) Load EDD (preserve literal strings like 'NA' in Parameter Code)
    df = pd.read_csv(INPUT_EDD_CSV, dtype=str, keep_default_na=False)
    field_col = resolve_col(df, ["field_sample_id", "sampleid", "sample_id"])
    param_col = resolve_col(df, ["parameter_code", "parameter", "parm_code"])
    result_col = resolve_col(df, ["lab_result", "result", "value"])

    # Clean parameter codes: strip; keep literal 'NA'; drop truly blank
    df[param_col] = df[param_col].astype(str).str.strip()
    blank_mask = (df[param_col] == "") | df[param_col].str.lower().isin({"nan", "none", "null"})
    if blank_mask.any():
        df = df.loc[~blank_mask].copy()

    # Coerce results to numeric for aggregation
    df[result_col] = pd.to_numeric(df[result_col], errors="coerce")

    # 2) Aggregate duplicates per (sample, parameter) using harmonic mean
    agg = (
        df.groupby([field_col, param_col], dropna=False, sort=False)[result_col]
          .apply(harmonic_mean)
          .reset_index()
    )

    # 3) Pivot to n×p matrix (rows=Field Sample ID, cols=Parameter Code)
    wide = (
        agg.pivot(index=field_col, columns=param_col, values=result_col)
           .sort_index(axis=0)
           .sort_index(axis=1)
    )

    # 4) Drop ALK and TEMP columns from pivot output (if present)
    for drop_name in ["ALK", "TEMP"]:
        col = find_ci(wide.columns, drop_name)
        if col is not None:
            wide = wide.drop(columns=[col])

    # 5) Unit conversion: divide CA, K, MG, NA by 1000 -> mg/L (if columns present)
    for ion in ["CA", "K", "MG", "NA"]:
        col = find_ci(wide.columns, ion)
        if col is not None:
            wide[col] = pd.to_numeric(wide[col], errors="coerce") / 1000.0

    # 6) Ensure HCO3(-1) and CO3(-2) exist (zeros if missing), then compute Alkalinity-CO3+HCO3
    if find_ci(wide.columns, "HCO3(-1)") is None:
        wide["HCO3(-1)"] = 0.0
    if find_ci(wide.columns, "CO3(-2)") is None:
        wide["CO3(-2)"] = 0.0
    # Use the exact actual names again (case-insensitive)
    hco3_col = find_ci(wide.columns, "HCO3(-1)")
    co3_col = find_ci(wide.columns, "CO3(-2)")
    wide[hco3_col] = pd.to_numeric(wide[hco3_col], errors="coerce").fillna(0.0)
    wide[co3_col]  = pd.to_numeric(wide[co3_col],  errors="coerce").fillna(0.0)
    wide["Alkalinity-CO3+HCO3"] = wide[hco3_col] + wide[co3_col]

    # 7) Drop HCO3(-1) and CO3(-2) after calculation
    wide = wide.drop(columns=[hco3_col, co3_col], errors="ignore")

    # 8) Rename columns using EDDtoIntellusNames.xlsx (EDD -> Intellus), ensuring NA -> Sodium
    if MAPPING_XLSX.exists():
        map_df = pd.read_excel(MAPPING_XLSX, dtype=str)
        src = resolve_col(map_df, ["edd", "source", "from"])
        tgt = resolve_col(map_df, ["intellus", "intellus name", "name", "target", "to"])
        mapping = {}
        for _, row in map_df[[src, tgt]].dropna(subset=[src]).iterrows():
            k = str(row[src]).strip()
            v = str(row[tgt]).strip() if not pd.isna(row[tgt]) else k
            if k:
                mapping[k] = v or k
        # Enforce NA -> Sodium even if mapping lacks it
        if "NA" not in mapping:
            mapping["NA"] = "Sodium"
        # Apply mapping to current columns (only exact matches)
        wide = wide.rename(columns={c: mapping.get(c, c) for c in wide.columns})
        print("Applied EDD->Intellus renames (including NA->Sodium).")
    else:
        # If no mapping, still enforce NA -> Sodium
        na_col = find_ci(wide.columns, "NA")
        if na_col is not None:
            wide = wide.rename(columns={na_col: "Sodium"})
        print(f"Mapping file not found: {MAPPING_XLSX}. Applied NA->Sodium fallback if needed.")

    # 9) Drop NO3+NO2 and TOC if they have numeric values for only two samples
    for candidate in ["NO3+NO2", "TOC"]:
        col = find_ci(wide.columns, candidate)
        if col is not None:
            vals = pd.to_numeric(wide[col], errors="coerce")
            non_null_count = int(vals.notna().sum())
            if non_null_count == 2:
                wide = wide.drop(columns=[col])

    # 10) Save n×p CSV (blank for missing)
    out_path = OUTPUT_DIR / OUTPUT_NAME
    wide.to_csv(out_path, na_rep="")
    print(f"Saved n×p matrix to: {out_path}")
    print(f"Rows (samples): {wide.shape[0]} | Columns (parameters): {wide.shape[1]}")

if __name__ == "__main__":
    main()

Applied EDD->Intellus renames (including NA->Sodium).
Saved n×p matrix to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\compile_odd_GC_forPCA_matrix_repV2.1.csv
Rows (samples): 7 | Columns (parameters): 34

In [12]:
#!/usr/bin/env python3
r"""
Build a treatment-plant parameter vector for location VS-CTUA-6-EFF using only
parameters that appear in the previously built matrix (compile_odd_GC_forPCA_matrix_repV2.1.csv).

Update:
 - The vector CSV now contains TWO rows:
     1) VS-CTUA-6-EFF | harmonic_mean | <parameters...>
     2) VS-CTUA-6-EFF | median        | <parameters...>
   where median is computed per-parameter over positive, finite values (consistent with the harmonic filter).
 - The first column is the Location ID ("VS-CTUA-6-EFF") and the second column is "Average Type".

Other outputs preserved:
 - watertreatment_VS-CTUA-6-EFF_vector_counts.csv (n positive obs per parameter for the harmonic mean)
 - watertreatment_VS-CTUA-6-EFF_records_by_date.csv (lossless pivot by sample date)
 - watertreatment_VS-CTUA-6-EFF_unmatched_parameters.csv (matrix params not observed in treatment EDD)
 - watertreatment_VS-CTUA-6-EFF_summary.json (small summary)

Paths (edit if needed):
  ROOT_DIR            = C:/Users/kylian.robinson/MapRebuildItems
  MATRIX_FILE         = compile_odd_GC_forPCA_matrix_repV2.1.csv  (under ROOT_DIR or V 2.1 items)
  TREATMENT_EDD_FILE  = Chemistry/watertreatment_9_1_24_ToDate.csv
  OUTPUT_DIR          = V 2.1 items

Harmonic mean: HM = n / Σ(1/x_i) over positive finite x_i; if none → NaN.
Median: per-parameter median over positive finite values; if none → NaN.
"""

from pathlib import Path
import pandas as pd
import numpy as np
import json

# -------------------- EDITABLE PATHS --------------------
ROOT_DIR = Path(r"C:/Users/kylian.robinson/MapRebuildItems")
MATRIX_FILE = ROOT_DIR / "compile_odd_GC_forPCA_matrix_repV2.1.csv"
ALT_MATRIX_FILE = ROOT_DIR / "V 2.1 items" / "compile_odd_GC_forPCA_matrix_repV2.1.csv"
TREATMENT_EDD_FILE = ROOT_DIR / "Chemistry" / "watertreatment_9_1_24_ToDate.csv"
OUTPUT_DIR = ROOT_DIR / "V 2.1 items"

OUTPUT_FILE_NAME = "watertreatment_VS-CTUA-6-EFF_vector.csv"
OUTPUT_COUNTS_NAME = "watertreatment_VS-CTUA-6-EFF_vector_counts.csv"
OUTPUT_RECORDS_BY_DATE_NAME = "watertreatment_VS-CTUA-6-EFF_records_by_date.csv"
OUTPUT_UNMATCHED_NAME = "watertreatment_VS-CTUA-6-EFF_unmatched_parameters.csv"
OUTPUT_SUMMARY_JSON = "watertreatment_VS-CTUA-6-EFF_summary.json"

LOCATION_TARGET = "VS-CTUA-6-EFF"
AVERAGE_TYPE_COL = "Average Type"
# --------------------------------------------------------


def harmonic_mean(values: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce")
    v = v[np.isfinite(v) & (v > 0)]
    if v.empty:
        return np.nan
    return float(len(v) / np.sum(1.0 / v))


def median_positive(values: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce")
    v = v[np.isfinite(v) & (v > 0)]
    if v.empty:
        return np.nan
    return float(np.median(v))


def count_positive(values: pd.Series) -> int:
    v = pd.to_numeric(values, errors="coerce")
    v = v[np.isfinite(v) & (v > 0)]
    return int(v.size)


def resolve_column(df: pd.DataFrame, candidates):
    low_map = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        key = cand.lower().strip()
        if key in low_map:
            return low_map[key]
    raise KeyError(f"Could not resolve any of {candidates} in columns: {list(df.columns)}")


def main():
    # --- Locate matrix file ---
    if not MATRIX_FILE.exists():
        if ALT_MATRIX_FILE.exists():
            matrix_path = ALT_MATRIX_FILE
        else:
            raise FileNotFoundError(
                f"Matrix file not found at {MATRIX_FILE} or {ALT_MATRIX_FILE}. "
                f"Build compile_odd_GC_forPCA_matrix_repV2.1.csv first."
            )
    else:
        matrix_path = MATRIX_FILE

    print(f"Using matrix file: {matrix_path}")
    matrix_df = pd.read_csv(matrix_path, dtype=str, keep_default_na=False)
    if matrix_df.shape[1] < 2:
        raise ValueError("Matrix file must have at least an ID column plus parameter columns.")
    # Parameter columns (exclude first assumed ID/sample column)
    matrix_parameters = set(matrix_df.columns[1:])
    print(f"Matrix parameter count: {len(matrix_parameters)}")

    # --- Load treatment plant EDD CSV ---
    if not TREATMENT_EDD_FILE.exists():
        raise FileNotFoundError(f"Treatment EDD file not found: {TREATMENT_EDD_FILE}")
    print(f"Loading treatment EDD: {TREATMENT_EDD_FILE}")
    edd_df = pd.read_csv(TREATMENT_EDD_FILE, dtype=str, keep_default_na=False)

    # Resolve needed columns
    loc_col = resolve_column(edd_df, ["location id", "location_id", "location", "loc id"])
    param_col = resolve_column(edd_df, ["parameter name", "parameter", "parameter_name"])
    result_col = resolve_column(edd_df, ["report result", "lab result", "result", "value"])
    date_col = resolve_column(edd_df, ["sample date", "date of sample", "collection date", "sampled date", "date"])

    # Clean
    edd_df[loc_col] = edd_df[loc_col].astype(str).str.strip()
    edd_df[param_col] = edd_df[param_col].astype(str).str.strip()
    edd_df[result_col] = pd.to_numeric(edd_df[result_col], errors="coerce")
    edd_df[date_col] = pd.to_datetime(edd_df[date_col], errors="coerce").dt.date

    # Filter for location and matrix parameters
    df_loc = edd_df[edd_df[loc_col].str.lower() == LOCATION_TARGET.lower()].copy()
    if df_loc.empty:
        raise ValueError(f"No rows for Location ID '{LOCATION_TARGET}'.")
    df_loc = df_loc[df_loc[param_col].isin(matrix_parameters)].copy()
    if df_loc.empty:
        raise ValueError("After filtering by matrix parameters, no data remain. Check naming alignment.")

    # Determine unmatched matrix parameters (matrix columns not present in this EDD selection)
    present_params = set(df_loc[param_col].unique())
    unmatched_params = sorted(matrix_parameters - present_params)
    print(f"Unmatched matrix parameters for {LOCATION_TARGET}: {len(unmatched_params)}")

    # Aggregate harmonic means, medians, and counts
    grouped = df_loc.groupby([loc_col, param_col], dropna=False, sort=False)[result_col]
    agg_h = grouped.apply(harmonic_mean).reset_index(name="harmonic_mean")
    agg_m = grouped.apply(median_positive).reset_index(name="median")
    agg_n = grouped.apply(count_positive).reset_index(name="n_obs")

    # Pivot to single-row (location as index), columns=parameters
    wide_h = agg_h.pivot(index=loc_col, columns=param_col, values="harmonic_mean").sort_index(axis=1)
    wide_m = agg_m.pivot(index=loc_col, columns=param_col, values="median").sort_index(axis=1)
    wide_n = agg_n.pivot(index=loc_col, columns=param_col, values="n_obs").sort_index(axis=1)

    # Ensure same columns/order
    all_params = sorted(set(wide_h.columns) | set(wide_m.columns))
    wide_h = wide_h.reindex(columns=all_params)
    wide_m = wide_m.reindex(columns=all_params)
    wide_n = wide_n.reindex(columns=all_params)

    # Build the two-row output with first column = Location ID, second = Average Type
    id_header = loc_col  # use the resolved location column name for clarity
    # Row for harmonic
    row_h = pd.DataFrame(
        [[LOCATION_TARGET, "harmonic_mean"] + [wide_h.loc[LOCATION_TARGET, c] for c in all_params]],
        columns=[id_header, AVERAGE_TYPE_COL] + all_params
    )
    # Row for median
    row_m = pd.DataFrame(
        [[LOCATION_TARGET, "median"] + [wide_m.loc[LOCATION_TARGET, c] for c in all_params]],
        columns=[id_header, AVERAGE_TYPE_COL] + all_params
    )
    vector_with_two_rows = pd.concat([row_h, row_m], ignore_index=True)

    # Full records by date (lossless): replicate columns if same date+parameter
    df_full = df_loc.dropna(subset=[date_col]).copy()
    df_full["_rep"] = df_full.groupby([date_col, param_col]).cumcount() + 1
    df_full["_colname"] = df_full.apply(
        lambda r: r[param_col] if r["_rep"] == 1 else f"{r[param_col]} (rep{r['_rep']})", axis=1
    )
    records_by_date = (
        df_full.pivot(index=date_col, columns="_colname", values=result_col)
               .sort_index(axis=0)
               .sort_index(axis=1)
    )
    records_by_date.index.name = "Sample Date"

    # Outputs
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_means = OUTPUT_DIR / OUTPUT_FILE_NAME
    out_counts = OUTPUT_DIR / OUTPUT_COUNTS_NAME
    out_records = OUTPUT_DIR / OUTPUT_RECORDS_BY_DATE_NAME
    out_unmatched = OUTPUT_DIR / OUTPUT_UNMATCHED_NAME
    out_summary = OUTPUT_DIR / OUTPUT_SUMMARY_JSON

    # vector with two rows (harmonic + median)
    vector_with_two_rows.to_csv(out_means, index=False, na_rep="")
    # counts remain single-row (n for the harmonic-mean filter set)
    wide_n.to_csv(out_counts, na_rep="")
    records_by_date.to_csv(out_records, na_rep="")
    pd.Series(unmatched_params, name="Unmatched_Parameters").to_csv(out_unmatched, index=False)

    summary = {
        "location": LOCATION_TARGET,
        "matrix_file": str(matrix_path),
        "treatment_file": str(TREATMENT_EDD_FILE),
        "vector_file": str(out_means),
        "counts_file": str(out_counts),
        "records_by_date_file": str(out_records),
        "unmatched_parameters_file": str(out_unmatched),
        "total_matrix_parameters": len(matrix_parameters),
        "retained_parameters": len(all_params),
        "unmatched_parameters_count": len(unmatched_params),
        "rows_in_vector_file": int(vector_with_two_rows.shape[0]),  # should be 2
        "average_types": vector_with_two_rows[AVERAGE_TYPE_COL].tolist(),
    }
    out_summary.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"\n✅ Vector (harmonic + median rows): {out_means}")
    print(f"✅ Counts (n): {out_counts}")
    print(f"✅ Records by date (lossless): {out_records}")
    print(f"✅ Unmatched parameter list: {out_unmatched}")
    print(f"✅ Summary JSON: {out_summary}")
    print(f"Vector rows: {vector_with_two_rows.shape[0]} (expected 2) | Parameters: {len(all_params)}")

if __name__ == "__main__":
    main()

Using matrix file: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\compile_odd_GC_forPCA_matrix_repV2.1.csv
Matrix parameter count: 33
Loading treatment EDD: C:\Users\kylian.robinson\MapRebuildItems\Chemistry\watertreatment_9_1_24_ToDate.csv
Unmatched matrix parameters for VS-CTUA-6-EFF: 1

✅ Vector (harmonic + median rows): C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\watertreatment_VS-CTUA-6-EFF_vector.csv
✅ Counts (n): C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\watertreatment_VS-CTUA-6-EFF_vector_counts.csv
✅ Records by date (lossless): C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\watertreatment_VS-CTUA-6-EFF_records_by_date.csv
✅ Unmatched parameter list: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\watertreatment_VS-CTUA-6-EFF_unmatched_parameters.csv
✅ Summary JSON: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\watertreatment_VS-CTUA-6-EFF_summary.json
Vector rows: 2 (expected 2) | Parameters: 32

In [13]:
#!/usr/bin/env python3
"""
Combine Drillsite_SelectedParams with the treatment plant vector (two-row: harmonic_mean + median)
and preserve a two-column identifier format:
  - Column 1: ID (same as the first column in the drill site file)
  - Column 2: Average Type
      * "Drillsite" for all drill rows
      * "harmonic_mean" and "median" for the two treatment rows

Behavior:
 1) Load (both in V 2.1 items):
      - Drillsite_SelectedParams.csv
      - watertreatment_VS-CTUA-6-EFF_vector.csv  (two rows: harmonic_mean + median)
 2) Sort drill parameter columns alphabetically (excluding ID and Average Type).
 3) Ensure treatment vector has first two columns: ID and 'Average Type' (rename if necessary).
 4) Force treatment ID label to 'VS-CTUA-6-EFF' (so it’s consistent).
 5) Align treatment columns to drill parameter set:
      - Add missing drill parameters to treatment rows as blank ("")
      - Drop treatment-only parameters not present in the drill set
 6) Insert 'Average Type' = 'Drillsite' for drill rows and place it as the second column.
 7) Append the two treatment rows to the drill rows.
 8) Save anthropogenic_data.csv in the same folder.

Run in Jupyter:
    %run build_anthropogenic_data.py

Editables:
 - BASE_DIR, filenames
 - ID_COL (force ID column name, or None to auto-use the first drill column)
 - AVERAGE_TYPE_COL name (defaults to 'Average Type')
 - TREATMENT_ID label ('VS-CTUA-6-EFF' by default)
"""

from pathlib import Path
import pandas as pd

# -------- Configuration --------
BASE_DIR = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items")
DRILL_FILE = BASE_DIR / "Drillsite_SelectedParams.csv"
TREATMENT_FILE = BASE_DIR / "watertreatment_VS-CTUA-6-EFF_vector.csv"
OUT_FILE = BASE_DIR / "anthropogenic_data.csv"

ID_COL = None                 # e.g., "Location ID"; None -> use first column of drill file
AVERAGE_TYPE_COL = "Average Type"
TREATMENT_ID = "VS-CTUA-6-EFF"  # enforced label for both treatment rows

def main():
    if not DRILL_FILE.exists():
        raise FileNotFoundError(f"Drill site file not found: {DRILL_FILE}")
    if not TREATMENT_FILE.exists():
        raise FileNotFoundError(f"Treatment vector file not found: {TREATMENT_FILE}")

    drill_df = pd.read_csv(DRILL_FILE, dtype=str, keep_default_na=False)
    treat_df = pd.read_csv(TREATMENT_FILE, dtype=str, keep_default_na=False)

    # Determine ID column from drill file
    id_col = ID_COL or drill_df.columns[0]
    if id_col not in drill_df.columns:
        raise ValueError(f"ID column '{id_col}' not found in drill file.")

    # Prepare drill data: ensure Average Type exists and is 2nd column; sort parameter columns
    drill = drill_df.copy()
    # If drill file already includes Average Type, keep it; otherwise add it
    if AVERAGE_TYPE_COL not in drill.columns:
        drill.insert(1, AVERAGE_TYPE_COL, "Drillsite")
    else:
        # Ensure all drill rows labeled consistently
        drill[AVERAGE_TYPE_COL] = "Drillsite"

    # Parameter columns for drill = all except ID and Average Type
    drill_param_cols = [c for c in drill.columns if c not in (id_col, AVERAGE_TYPE_COL)]
    drill_param_cols_sorted = sorted(drill_param_cols, key=lambda x: x.lower())

    # Reorder drill columns: [ID, Average Type, sorted params...]
    drill = drill[[id_col, AVERAGE_TYPE_COL] + drill_param_cols_sorted]

    # Prepare treatment vector: must have first two columns = ID + Average Type
    # Rename first two columns to match our schema if needed
    if treat_df.shape[1] < 2:
        raise ValueError("Treatment vector must have at least two columns (ID and Average Type) plus parameters.")

    treat_cols = list(treat_df.columns)
    # Rename first column to id_col if different
    if treat_cols[0] != id_col:
        treat_df = treat_df.rename(columns={treat_cols[0]: id_col})
    # Rename second column to AVERAGE_TYPE_COL if different
    if treat_df.columns[1] != AVERAGE_TYPE_COL:
        treat_df = treat_df.rename(columns={treat_df.columns[1]: AVERAGE_TYPE_COL})

    # Enforce treatment ID label
    treat_df[id_col] = TREATMENT_ID

    # Align treatment parameter columns to the drill parameter set:
    # - add missing columns as ""
    # - drop extra columns (not in drill set)
    treat_param_cols_current = [c for c in treat_df.columns if c not in (id_col, AVERAGE_TYPE_COL)]
    missing_for_treat = [c for c in drill_param_cols_sorted if c not in treat_param_cols_current]
    for col in missing_for_treat:
        treat_df[col] = ""
    # Keep only ID, Average Type, and drill params
    treat_df = treat_df[[id_col, AVERAGE_TYPE_COL] + drill_param_cols_sorted]

    # Combine: drill rows first, then both treatment rows
    combined = pd.concat([drill, treat_df], ignore_index=True)

    # Save combined
    combined.to_csv(OUT_FILE, index=False, na_rep="")

    # Report
    print(f"Saved combined file to: {OUT_FILE}")
    print(f"- Drill rows: {len(drill_df)}")
    print(f"- Treatment rows appended: {len(treat_df)} (expected 2: harmonic_mean, median)")
    print(f"- Identifier columns: [{id_col!r}, {AVERAGE_TYPE_COL!r}]")
    print(f"- Parameter columns (sorted): {len(drill_param_cols_sorted)}")
    if missing_for_treat:
        print(f"- Params missing in treatment (filled blank): {len(missing_for_treat)} "
              f"(first 15: {missing_for_treat[:15]})")

if __name__ == "__main__":
    main()

Saved combined file to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\anthropogenic_data.csv
- Drill rows: 7
- Treatment rows appended: 2 (expected 2: harmonic_mean, median)
- Identifier columns: ['FIELD_SAMPLE_ID', 'Average Type']
- Parameter columns (sorted): 32

In [20]:
#!/usr/bin/env python3
r"""
Intellus_matrix_builder
Build a location×date parameter matrix aligned to a predefined parameter set, taking the HIGHEST
(measured) value when there are multiple samples for the same (Location, Date, Parameter).

Update:
 - Removed the argument skipna=True from GroupBy.max(), which caused a TypeError in your pandas
   version (pandas GroupBy.max does not accept a skipna keyword there). The default behavior
   already ignores NaNs for numeric dtypes.

Process:
 1. Load manual parameter matrix (anthropogenic_data.csv) to determine final parameter columns.
 2. Load long-form chemistry file (CrWedge_Analytes_fr9_1_24_ao_10_21_25.csv).
 3. Resolve column names case-insensitively.
 4. Strip strings; keep literal tokens like 'NA' in parameter names.
 5. Drop truly blank parameter names (keep literal 'NA').
 6. Coerce result column to numeric (non-numeric -> NaN).
 7. Aggregate duplicate (Location, Date, Parameter) rows by maximum numeric value.
 8. Pivot to wide matrix (index = Location, Date).
 9. Reindex columns to manual parameter ordering (adding missing empty columns, dropping extras).
10. Write CSV with blanks for NaN.

Edit paths below if needed.
"""

from pathlib import Path
import pandas as pd
import numpy as np

# -------------------- CONFIGURABLE PATHS --------------------
MANUAL_PARAMS_PATH = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items/anthropogenic_data.csv")
CHEM_INPUT_PATH    = Path(r"C:/Users/kylian.robinson/MapRebuildItems/Chemistry/CrWedge_Analytes_fr9_1_24_ao_10_21_25.csv")
CHEM_OUTPUT_PATH   = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items/CrWedge_matrix_location_date.csv")
# ------------------------------------------------------------

def main():
    # 1. Manual parameter columns (order to enforce)
    manual_df = pd.read_csv(MANUAL_PARAMS_PATH, index_col=0, keep_default_na=False, dtype=str)
    manual_params = list(manual_df.columns)
    if not manual_params:
        raise ValueError(f"No parameter columns found in manual parameter matrix: {MANUAL_PARAMS_PATH}")

    # 2. Chemistry long-form
    chem_df = pd.read_csv(CHEM_INPUT_PATH, keep_default_na=False)

    # 3. Resolve columns
    lower_map = {c.lower().strip(): c for c in chem_df.columns}

    def resolve_col(possible_names, what):
        for name in possible_names:
            key = name.lower().strip()
            if key in lower_map:
                return lower_map[key]
        raise ValueError(
            f"Could not find required column for {what}. "
            f"Tried: {possible_names}. "
            f"Available: {list(chem_df.columns)}"
        )

    location_col = resolve_col(
        ["location", "location id", "location_id", "locationid", "site id", "site"],
        "Location"
    )
    date_col = resolve_col(
        ["date sampled", "sample date", "collection date", "sampled date", "date"],
        "Date Sampled"
    )
    param_col = resolve_col(
        ["parameter_code", "parameter name", "parameter", "analyte", "analyte name",
         "constituent", "analyte_name"],
        "Parameter"
    )
    result_col = resolve_col(
        ["lab_result", "report result", "result", "value", "result value",
         "reported value", "parameter result", "final result"],
        "Numeric Result"
    )

    # 4. Clean identifiers
    chem_df[location_col] = chem_df[location_col].astype(str).str.strip()
    chem_df[date_col]     = chem_df[date_col].astype(str).str.strip()
    chem_df[param_col]    = chem_df[param_col].astype(str).str.strip()

    # 5. Drop blank parameter names (keep literal 'NA')
    blank_param_mask = (chem_df[param_col] == "") | (chem_df[param_col].str.lower().isin({"", "nan", "none"}))
    dropped_blank = int(blank_param_mask.sum())
    if dropped_blank:
        chem_df = chem_df.loc[~blank_param_mask].copy()

    # 6. Coerce numeric results
    chem_df[result_col] = pd.to_numeric(chem_df[result_col], errors="coerce")

    # 7. Aggregate duplicates: maximum value per (Location, Date, Parameter)
    # Removed skipna=True because GroupBy.max() does not accept it in your pandas version.
    agg_df = (
        chem_df.groupby([location_col, date_col, param_col], dropna=False, sort=False)[result_col]
               .max()
               .reset_index()
    )

    # 8. Pivot
    wide = (
        agg_df.pivot(index=[location_col, date_col], columns=param_col, values=result_col)
              .sort_index(axis=0)
              .sort_index(axis=1)
    )

    # 9. Align to manual parameter set
    wide_aligned = wide.reindex(columns=manual_params)

    # 10. Output
    wide_out = wide_aligned.reset_index()
    wide_out = wide_out[[location_col, date_col] + manual_params]

    CHEM_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    wide_out.to_csv(CHEM_OUTPUT_PATH, index=False, na_rep="")

    extra_cols = [c for c in wide.columns if c not in manual_params]
    missing_cols = [c for c in manual_params if c not in wide.columns]

    print(f"✅ Input chemistry long-form: {CHEM_INPUT_PATH}")
    print(f"✅ Manual parameter matrix:  {MANUAL_PARAMS_PATH}")
    print(f"✅ Wrote aligned MAX matrix: {CHEM_OUTPUT_PATH}")
    print(f"   Rows (Location, Date): {wide_out.shape[0]} | Parameters (manual set): {len(manual_params)}")
    if dropped_blank:
        print(f"ℹ️ Dropped {dropped_blank} rows with blank parameter names (kept literal 'NA').")
    if extra_cols:
        print(f"ℹ️ Dropped {len(extra_cols)} parameters not in manual set (first 10): "
              f"{extra_cols[:10]}{'...' if len(extra_cols) > 10 else ''}")
    if missing_cols:
        print(f"ℹ️ Added {len(missing_cols)} empty columns from manual set absent in chemistry (first 10): "
              f"{missing_cols[:10]}{'...' if len(missing_cols) > 10 else ''}")

if __name__ == "__main__":
    main()

✅ Input chemistry long-form: C:\Users\kylian.robinson\MapRebuildItems\Chemistry\CrWedge_Analytes_fr9_1_24_ao_10_21_25.csv
✅ Manual parameter matrix:  C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\anthropogenic_data.csv
✅ Wrote aligned MAX matrix: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_matrix_location_date.csv
   Rows (Location, Date): 1026 | Parameters (manual set): 33
ℹ️ Dropped 391 parameters not in manual set (first 10): ['1,3,5-Naphthalene trisulfonic acid', '1,3,6-Naphthalene trisulfonic acid', '1,5-Naphthalenedisulfonic acid', '1,6-Naphthalene disulfonic acid', '1-Naphthalene sulfonic acid', '11-Chloroeicosafluoro-3-oxaundecane-1-sulfonic acid', '1H, 1H, 2H, 2H-Perfluorododecanesulphonic acid', '1H, 1H, 2H, 2H-Perfluorohexanesulfonic acid', '1H, 1H, 2H, 2H-perfluorodecane sulfonic acid', '1H, 1H, 2H, 2H-perfluorooctane sulfonic acid']...
ℹ️ Added 1 empty columns from manual set absent in chemistry (first 10): ['Type']

In [22]:
import pandas as pd
import numpy as np
from pathlib import Path

# Default input: the aligned matrix with Location and Date Sampled columns
# If you saved with the earlier script, this should exist:
default_input = Path(r"C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_matrix_location_date.csv")

# If the exact filename changed, we’ll fall back to any *_matrix_manualcols_location_date.csv in the Chemistry folder
if not default_input.exists():
    chem_dir = default_input.parent
    candidates = sorted(chem_dir.glob("*_matrix_manualcols_location_date.csv"))
    if not candidates:
        raise FileNotFoundError(f"Could not find an input matrix like *_matrix_manualcols_location_date.csv in {chem_dir}")
    input_path = candidates[0]
else:
    input_path = default_input

# Output path
output_path = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items/CrWedge_AnalytesTruncated_MR.csv")

# Read the saved matrix; blanks will come back as NaN by default
df = pd.read_csv(input_path, keep_default_na=True)

# Resolve id columns (case-insensitive)
lower_map = {c.lower().strip(): c for c in df.columns}
def resolve_col(possible, what):
    for n in possible:
        if n in lower_map:
            return lower_map[n]
    raise ValueError(f"Missing required column for {what}. Looked for: {possible}. Found: {list(df.columns)}")

location_col = resolve_col(["location", "location id", "location_id", "site", "site id"], "Location")
date_col     = resolve_col(["date sampled", "sample date", "collection date", "date"], "Date Sampled")

# Parse dates; drop rows where date cannot be parsed
df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
df = df.dropna(subset=[date_col])

# Parameter columns are everything except the id columns
param_cols = [c for c in df.columns if c not in {location_col, date_col}]

# Coerce parameter columns to numeric to standardize completeness checks
for c in param_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Keep only rows with a complete parameter set (no NaNs across all parameter columns)
complete_mask = df[param_cols].notna().all(axis=1)
df_complete = df.loc[complete_mask].copy()

# For each location, select the most recent row (max date)
if df_complete.empty:
    raise ValueError("No rows have a complete parameter set; nothing to output.")

idx_latest = df_complete.groupby(location_col, as_index=False)[date_col].idxmax()[date_col]
latest_rows = df_complete.loc[idx_latest].copy()

# Sort by Location for readability and keep column order as in the input
latest_rows = latest_rows.sort_values(by=[location_col])

# Save to CSV with blanks for any (should be none) missing values
output_path.parent.mkdir(parents=True, exist_ok=True)
latest_rows.to_csv(output_path, index=False, na_rep="")

# Report summary
total_locs = df[location_col].nunique(dropna=True)
covered_locs = latest_rows[location_col].nunique(dropna=True)
print(f"✅ Input: {input_path}")
print(f"✅ Wrote most-recent complete rows to: {output_path}")
print(f"   Locations covered: {covered_locs} / {total_locs}")

✅ Input: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_matrix_location_date.csv
✅ Wrote most-recent complete rows to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_AnalytesTruncated_MR.csv
   Locations covered: 87 / 282

In [24]:
#!/usr/bin/env python3
r"""
Purpose: assign well-based categories (Cat) on verified date-specific data, and overwrite the Date
column in-place with Cat for downstream plotting.

What this does:
 1) Load the analyte matrix (expects Location and Date columns present).
 2) Load WellsOfInterest.xls and build category mappings using:
      - Exact Location_ID -> Cat
      - Exact Well_ID -> Cat
      - (BaseWell, screen rank) -> Cat via DepthEnd or explicit S# suffix
      - Singleton base-well fallback -> Cat
 3) Resolve Cat for each matrix row based on its Location.
 4) Overwrite the Date column (same position) with Cat.
 5) Any row that still lacks a Cat is assigned "Intermediate" (dataset-specific rule).
 6) Save an unmatched report listing rows that had no Cat BEFORE the "Intermediate" fill.

Notes:
 - Column order is preserved except that the Date column is replaced by a new column named "Cat"
   at the exact same position as Date.
"""

import re
from pathlib import Path
import pandas as pd
import numpy as np

# Paths
base_dir = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items/")
input_matrix = base_dir / "CrWedge_AnalytesTruncated_MR.csv"
wells_path = base_dir / "WellsOfInterest.xls"
output_matrix = base_dir / "CrWedge_AnalytesTruncated_MR_withCat.csv"
unmatched_out = base_dir / "CrWedge_Analytes_UnmatchedToCat.csv"

# Load truncated matrix (expects Location and Date columns present)
df = pd.read_csv(input_matrix, keep_default_na=True)

# Resolve key columns in matrix (case-insensitive, strip whitespace)
lower_map = {c.lower().strip(): c for c in df.columns}
def resolve_col(possible, what):
    for n in possible:
        if n in lower_map:
            return lower_map[n]
    raise ValueError(f"Missing required column for {what}. Looked for: {possible}. Found: {list(df.columns)}")

location_col = resolve_col(["location", "location id", "location_id", "site", "site id"], "Location")
date_col     = resolve_col(["date sampled", "sample date", "collection date", "date"], "Date Sampled")

# Require Aluminum to be present (kept from base script; not used for placement anymore)
al_col = None
for c in df.columns:
    if c.strip().lower() == "aluminum":
        al_col = c
        break
if al_col is None:
    raise ValueError("Expected an 'Aluminum' column in the matrix, but it was not found.")

# Load WellsOfInterest.xls with deterministic ID priority (Location_ID > Well_ID > Site_ID)
xls = pd.ExcelFile(wells_path)

def canon(s: str) -> str:
    s = str(s).lower()
    return "".join(ch for ch in s if ch.isalnum())

id_priority = [
    "location_id", "location id", "location",
    "well_id", "well id", "well",
    "site_id", "site id", "site"
]
cat_keys = ["cat"]
depth_candidates = [
    "perforation_zone_end_depth", "perforation zone end depth",
    "perforation_end_depth", "perforation end depth",
    "perforation_end", "perforation end",
    "screen_end_depth", "screen end depth",
    "screen_end", "screen end",
    "perforation_bottom", "perforation bottom",
    "perf_end_depth", "perf end depth",
]

wells_frames = []
for sheet in xls.sheet_names:
    w_raw = pd.read_excel(xls, sheet_name=sheet)
    cm = {canon(c): c for c in w_raw.columns}

    # Cat
    cat_col_src = None
    for k in cat_keys:
        if canon(k) in cm:
            cat_col_src = cm[canon(k)]
            break
    if not cat_col_src:
        continue

    # IDs (deterministic priority)
    loc_id_src = None; well_id_src = None; site_id_src = None
    for key in id_priority:
        ck = canon(key)
        if ck in cm:
            if "location" in key and loc_id_src is None:
                loc_id_src = cm[ck]
            elif "well" in key and well_id_src is None:
                well_id_src = cm[ck]
            elif "site" in key and site_id_src is None:
                site_id_src = cm[ck]

    if not any([loc_id_src, well_id_src, site_id_src]):
        continue

    # Depth (optional)
    depth_col_src = None
    for k in depth_candidates:
        ck = canon(k)
        if ck in cm:
            depth_col_src = cm[ck]
            break

    keep_cols = [c for c in [loc_id_src, well_id_src, site_id_src, cat_col_src, depth_col_src] if c]
    sub = w_raw[keep_cols].copy()

    rename_map = {}
    if loc_id_src:  rename_map[loc_id_src] = "Location_ID"
    if well_id_src: rename_map[well_id_src] = "Well_ID"
    if site_id_src: rename_map[site_id_src] = "Site_ID"
    rename_map[cat_col_src] = "Cat"
    if depth_col_src: rename_map[depth_col_src] = "DepthEnd"
    sub = sub.rename(columns=rename_map)
    wells_frames.append(sub)

if not wells_frames:
    raise ValueError(f"No suitable sheet in {wells_path} with an ID column and Cat column.")

wells = pd.concat(wells_frames, ignore_index=True)

# Normalize ID strings and depth
for col in ["Location_ID", "Well_ID", "Site_ID"]:
    if col in wells.columns:
        wells[col] = wells[col].astype(str).str.strip()
if "DepthEnd" in wells.columns:
    wells["DepthEnd"] = pd.to_numeric(wells["DepthEnd"], errors="coerce")
else:
    wells["DepthEnd"] = np.nan

# Choose a name to parse screens from (prefer Well_ID, else Location_ID, else Site_ID)
def name_for_parsing(row):
    for c in ["Well_ID", "Location_ID", "Site_ID"]:
        if c in wells.columns:
            v = row.get(c, None)
            if pd.notna(v) and str(v).strip() not in ("", "nan", "None"):
                return str(v).strip()
    return ""

# Parse base well and explicit screen number "S#"
def parse_base_screen(name: str):
    s = str(name).strip()
    m = re.search(r"(.*?)[\s_-]*s\s*(\d+)$", s, flags=re.IGNORECASE)
    if m:
        base = m.group(1).strip()
        try:
            scr = int(m.group(2))
        except Exception:
            scr = None
        return base, scr
    return s, None

wells["NameParse"] = wells.apply(name_for_parsing, axis=1)
wells["BaseWell"], wells["ScreenExplicit"] = zip(*wells["NameParse"].map(parse_base_screen))

# Depth-based rank within each base well: shallower DepthEnd => rank 1 (S1)
wells["RankByDepth"] = np.nan
for base_u, g in wells.groupby(wells["BaseWell"].str.upper(), dropna=False):
    if g["DepthEnd"].notna().any():
        wells.loc[g.index, "RankByDepth"] = g["DepthEnd"].rank(method="dense")  # ascending: S1, S2, ...
    else:
        if g["ScreenExplicit"].notna().any():
            wells.loc[g.index, "RankByDepth"] = g["ScreenExplicit"]
        else:
            wells.loc[g.index, "RankByDepth"] = 1.0 if len(g) == 1 else np.nan

# Exact maps
exact_map_loc  = {str(k).upper(): v for k, v in wells[["Location_ID", "Cat"]].itertuples(index=False)} if "Location_ID" in wells else {}
exact_map_well = {str(k).upper(): v for k, v in wells[["Well_ID", "Cat"]].itertuples(index=False)} if "Well_ID" in wells else {}

# Screen tuple map: (BaseWell, rank by depth) -> Cat
tuple_map = {}
for _, row in wells.iterrows():
    base_u = str(row["BaseWell"]).upper()
    key_scr = None
    if pd.notna(row["RankByDepth"]):
        key_scr = int(row["RankByDepth"])
    elif pd.notna(row["ScreenExplicit"]):
        key_scr = int(row["ScreenExplicit"])
    if key_scr is not None and base_u:
        tuple_map[(base_u, key_scr)] = row["Cat"]

# Singleton fallback: base well present exactly once
singleton_cat = (
    wells.groupby(wells["BaseWell"].str.upper(), dropna=False)["Cat"]
         .agg(lambda s: s.iloc[0] if len(s) == 1 else np.nan)
)

def normalize_key(s):
    return re.sub(r"\s+", " ", str(s or "")).strip().upper()

match_counts = {"exact_location": 0, "exact_well": 0, "screen_rank": 0, "singleton_base": 0}

def cat_for_location(loc: str):
    s = normalize_key(loc)
    if not s:
        return np.nan
    # Exact by Location_ID
    if s in exact_map_loc:
        match_counts["exact_location"] += 1
        return exact_map_loc[s]
    # Exact by Well_ID
    if s in exact_map_well:
        match_counts["exact_well"] += 1
        return exact_map_well[s]
    # Screen-based (e.g., 'R-70 S2')
    base, scr = parse_base_screen(s)
    base_u = normalize_key(base)
    if scr is not None:
        val = tuple_map.get((base_u, int(scr)))
        if val is not None:
            match_counts["screen_rank"] += 1
            return val
    # Singleton base fallback
    val = singleton_cat.get(base_u, np.nan)
    if pd.notna(val):
        match_counts["singleton_base"] += 1
        return val
    return np.nan

# Compute Cat values
cat_values = df[location_col].map(cat_for_location)

# Capture rows that originally had no Cat
unmatched_mask = cat_values.isna() | (cat_values.astype(str).str.strip() == "")
unmatched = df.loc[unmatched_mask, [location_col, date_col]].copy().sort_values([location_col, date_col])

# Dataset-specific rule: assign "Intermediate" to any remaining blanks
cat_values_filled = cat_values.copy()
cat_values_filled = cat_values_filled.fillna("Intermediate")
cat_values_filled = cat_values_filled.replace("", "Intermediate")

# Overwrite the Date column IN PLACE (same position) with 'Cat'
out = df.copy()
date_idx = out.columns.get_loc(date_col)
# Drop the original date column and insert 'Cat' at the same index
out = out.drop(columns=[date_col])
out.insert(date_idx, "Cat", cat_values_filled)

# Save outputs
out.to_csv(output_matrix, index=False, na_rep="")
if len(unmatched) > 0:
    unmatched.to_csv(unmatched_out, index=False)
else:
    pd.DataFrame(columns=[location_col, date_col]).to_csv(unmatched_out, index=False)

# Report
total = len(out)
matched = total - len(unmatched)
print(f"✅ Input matrix: {input_matrix}")
print(f"✅ Wells catalog: {wells_path}")
print(f"✅ Wrote matrix with Cat overwriting '{date_col}' at the same position: {output_matrix}")
print(f"✅ Unmatched report (pre-fill) written to: {unmatched_out} (count={len(unmatched)})")
print(f"Resolved columns -> Location: '{location_col}' | Date: '{date_col}' | Aluminum: '{al_col}'")
print(f"Cat column position: {out.columns.get_loc('Cat')} (should equal original Date position {date_idx})")
print(f"Match breakdown: {match_counts} | Matched (pre-fill) {matched}/{total} rows")

✅ Input matrix: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_AnalytesTruncated_MR.csv
✅ Wells catalog: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\WellsOfInterest.xls
✅ Wrote matrix with Cat overwriting 'Date Sampled' at the same position: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_AnalytesTruncated_MR_withCat.csv
✅ Unmatched report (pre-fill) written to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\CrWedge_Analytes_UnmatchedToCat.csv (count=11)
Resolved columns -> Location: 'Location' | Date: 'Date Sampled' | Aluminum: 'Aluminum'
Cat column position: 1 (should equal original Date position 1)
Match breakdown: {'exact_location': 33, 'exact_well': 0, 'screen_rank': 40, 'singleton_base': 4} | Matched (pre-fill) 76/87 rows

In [5]:
#!/usr/bin/env python3
"""
Build a simple profile for numeric analytes in AllWells_V3_nInt.

Fixes applied:
 - Corrected profile_out path construction (previous code used an invalid `base_dir / + "/..."`).
 - Ensure output directory is created before writing.
 - Made resolve_col robust to capitalization/whitespace and return the original column name.
 - Guard against missing optional Cat column.
 - Ensure id_like excludes None values.
 - Simplified and corrected zero count calculation.
 - Improved some small robustness checks and clearer error messages.

Run from a Jupyter cell with:
    %run Intellus_profile_builder.py
"""

from pathlib import Path
import pandas as pd
import numpy as np

# -------- Paths (edit if needed) --------
base_dir = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items")
input_path = base_dir / "AllWells_V3_nInt.csv"
profile_out = base_dir / "results_3.1" / "AllWells_V3_nInt_pca_profile.csv"
# ---------------------------------------

# Load input (support csv or xlsx)
if not input_path.exists():
    raise FileNotFoundError(f"Input not found: {input_path}")
if input_path.suffix.lower() == ".xlsx":
    df = pd.read_excel(input_path)
else:
    df = pd.read_csv(input_path)

# Resolve identifiers (case-insensitive, whitespace-insensitive)
lower_map = {c.lower().strip(): c for c in df.columns}
def resolve_col(options, label, required=True):
    for o in options:
        key = o.lower().strip()
        if key in lower_map:
            return lower_map[key]
    if required:
        raise ValueError(f"Missing required column for {label}. Looked for {options}. Found: {list(df.columns)}")
    return None

location_col = resolve_col(["location", "location id", "location_id"], "Location")
cat_col      = resolve_col(["cat"], "Cat", required=False)

# Numeric analyte columns: exclude Location and Cat only (if cat_col not found, ignore)
id_like = {location_col, cat_col} - {None}
candidate_cols = [c for c in df.columns if c not in id_like]

# Coerce candidates to numeric when possible (>=70% numeric or column dtype numeric)
numeric_cols = []
for c in candidate_cols:
    s_num = pd.to_numeric(df[c], errors="coerce")
    frac_numeric = s_num.notna().mean() if len(s_num) else 0.0
    if frac_numeric >= 0.7 or pd.api.types.is_numeric_dtype(df[c]):
        numeric_cols.append(c)
if not numeric_cols:
    raise ValueError("No numeric analyte columns detected based on the current heuristics.")

# Ensure output directory exists
profile_out.parent.mkdir(parents=True, exist_ok=True)

# Profile each numeric analyte
rows = []
for c in numeric_cols:
    s = pd.to_numeric(df[c], errors="coerce")
    n = len(s)
    nmiss = int(s.isna().sum())
    miss_pct = 100.0 * nmiss / n if n else np.nan
    s_valid = s.dropna()
    zero_ct = int((s_valid == 0).sum())
    nonpos_ct = int((s_valid <= 0).sum())
    uniq = int(s_valid.nunique(dropna=True))
    const = (uniq <= 1)
    vmin = float(np.nanmin(s_valid)) if len(s_valid) else np.nan
    vmax = float(np.nanmax(s_valid)) if len(s_valid) else np.nan
    p1 = float(np.nanpercentile(s_valid, 1)) if len(s_valid) else np.nan
    p50 = float(np.nanpercentile(s_valid, 50)) if len(s_valid) else np.nan
    p99 = float(np.nanpercentile(s_valid, 99)) if len(s_valid) else np.nan
    skew = float(pd.Series(s_valid).skew()) if len(s_valid) else np.nan

    if len(s_valid) == 0 or const:
        sugg = "drop (no variance or no data)"
    else:
        skew_val = skew if np.isfinite(skew) else 0.0
        if nonpos_ct == 0 and skew_val > 1.0:
            sugg = "log10"
        elif skew_val > 1.0:
            sugg = "yeo-johnson"
        else:
            sugg = "none"

    rows.append({
        "parameter": c,
        "n": n,
        "missing_count": nmiss,
        "missing_pct": round(miss_pct, 2),
        "unique_non_nan": uniq,
        "zero_count": zero_ct,
        "nonpositive_count": nonpos_ct,
        "min": vmin,
        "p01": p1,
        "p50": p50,
        "p99": p99,
        "max": vmax,
        "skew": skew,
        "suggested_transform": sugg,
    })

profile = pd.DataFrame(rows).sort_values(["suggested_transform", "missing_pct", "parameter"])
profile.to_csv(profile_out, index=False)

print(f"✅ Profile written: {profile_out}")
print(f"- Numeric analytes profiled: {len(numeric_cols)}")
print(f"- High missing (>20%): {profile[profile['missing_pct'] > 20].shape[0]}")
print(f"- Constant/no-variance: {profile[profile['suggested_transform'].str.startswith('drop')].shape[0]}")
print(f"- Log10 candidates: {profile[profile['suggested_transform']=='log10'].shape[0]}")
print(f"- Yeo-Johnson candidates: {profile[profile['suggested_transform']=='yeo-johnson'].shape[0]}")

✅ Profile written: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\AllWells_V3_nInt_pca_profile.csv
- Numeric analytes profiled: 22
- High missing (>20%): 0
- Constant/no-variance: 0
- Log10 candidates: 22
- Yeo-Johnson candidates: 0

In [8]:
#!/usr/bin/env python3
r"""
PCA scores creator + plotter

This script will:
 - Use results_3.1 under V 2.1 items as the results folder.
 - If PCA outputs (pca_scores.csv, pca_rotation.csv, pca_explained_variance.csv) exist, it will load them.
 - If not, it will build PCA from a numeric matrix source (default: AllWells_V3_nInt.csv),
   save scores, rotation (loadings), and explained-variance CSVs into results_3.1.
 - Print percent variance explained for the first three PCs.
 - Save a PNG bar plot of percent explained for all PCs.
 - Save a labeled PC1 vs PC2 scatter (with convex hull labels) into results_3.1 and export hull vertices.

Notes:
 - PCA building uses sklearn (SimpleImputer + StandardScaler + PCA). Install scikit-learn if missing.
 - Adjust numeric-detection heuristics (70% numeric) if you want different behavior.
"""

from pathlib import Path
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import patheffects as mpe

# Optional label de-overlap
try:
    from adjustText import adjust_text
    HAVE_ADJUSTTEXT = True
except Exception:
    HAVE_ADJUSTTEXT = False

# PCA dependencies
try:
    from sklearn.decomposition import PCA
    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import StandardScaler
except Exception as e:
    raise ImportError("scikit-learn is required. Install with: pip install scikit-learn") from e

# ---------------- Paths ----------------
BASE_DIR = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items")
RESULTS_DIR = BASE_DIR / "results_3.1"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

SCORES_PATH = RESULTS_DIR / "pca_scores.csv"
ROTATION_PATH = RESULTS_DIR / "pca_rotation.csv"
EXPLAINED_CSV = RESULTS_DIR / "pca_explained_variance.csv"
EXPLAINED_PNG = RESULTS_DIR / "pca_explained_variance.png"
SCATTER_PNG = RESULTS_DIR / "pca_pc1_pc2_scatter_labeled_deoverlap.png"
HULL_CSV = RESULTS_DIR / "pca_convex_hull_vertices.csv"

# Default matrix source to build PCA from if scores not present
MATRIX_SOURCE = BASE_DIR / "AllWells_V3_nInt.csv"
# ---------------------------------------

def resolve_col_in_df(df, candidates, required=True):
    lower_map = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        key = cand.lower().strip()
        if key in lower_map:
            return lower_map[key]
    if required:
        raise ValueError(f"Missing required column among: {candidates}. Available cols: {list(df.columns)}")
    return None

def detect_numeric_features(df, exclude_cols):
    id_like = set(exclude_cols) - {None}
    candidate_cols = [c for c in df.columns if c not in id_like]
    numeric_cols = []
    for c in candidate_cols:
        s_num = pd.to_numeric(df[c], errors="coerce")
        frac_numeric = s_num.notna().mean() if len(s_num) else 0.0
        if frac_numeric >= 0.7 or pd.api.types.is_numeric_dtype(df[c]):
            numeric_cols.append(c)
    return numeric_cols

def build_and_save_pca(df_matrix, matrix_path, numeric_cols, location_col=None, cat_col=None, n_components=None):
    # Extract numeric feature matrix
    X = df_matrix[numeric_cols].copy()
    X_num = X.apply(pd.to_numeric, errors="coerce")

    # Impute missing -> column mean
    imputer = SimpleImputer(strategy="mean")
    X_imputed = imputer.fit_transform(X_num.values)

    # Standardize
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)

    # Determine n_components
    if n_components is None:
        n_components = min(X_scaled.shape[0], X_scaled.shape[1])

    pca = PCA(n_components=n_components)
    scores = pca.fit_transform(X_scaled)

    # Build scores DataFrame
    pc_cols = [f"PC{i}" for i in range(1, scores.shape[1] + 1)]
    scores_df = pd.DataFrame(scores, columns=pc_cols, index=df_matrix.index)

    # Insert identifier columns if available
    if location_col and location_col in df_matrix.columns:
        scores_df.insert(0, location_col, df_matrix[location_col].astype(str).values)
    else:
        scores_df.insert(0, "Location", [""] * len(scores_df))

    if cat_col and cat_col in df_matrix.columns:
        scores_df.insert(1, cat_col, df_matrix[cat_col].astype(str).values)
    else:
        scores_df.insert(1, "Cat", [""] * len(scores_df))

    # Save scores
    scores_df.to_csv(SCORES_PATH, index=False, float_format="%.8g")

    # Rotation/loadings: features x PCs
    loadings = pd.DataFrame(pca.components_.T, index=numeric_cols, columns=pc_cols)
    loadings.to_csv(ROTATION_PATH, index=True, float_format="%.8g")

    # Explained variance ratios
    pct = 100.0 * pca.explained_variance_ratio_
    explained_df = pd.DataFrame({"PC": pc_cols, "percent_explained": pct})
    explained_df.to_csv(EXPLAINED_CSV, index=False, float_format="%.8g")

    return scores_df, loadings, pct

def detect_pc_columns(columns):
    pc_list = []
    pat = re.compile(r'(?:^|[^a-z0-9])pc[^\d]*(\d+)', flags=re.IGNORECASE)
    pat2 = re.compile(r'(?:^|[^a-z0-9])pca[^\d]*(\d+)', flags=re.IGNORECASE)
    for col in columns:
        col_low = str(col).lower()
        m = pat.search(col_low) or pat2.search(col_low)
        if m:
            idx = int(m.group(1))
            pc_list.append((idx, col))
            continue
        m2 = re.search(r'\bcomponent[^\d]*(\d+)\b', col_low)
        if m2:
            pc_list.append((int(m2.group(1)), col))
            continue
        m3 = re.search(r'\bpc_(\d+)\b', col_low)
        if m3:
            pc_list.append((int(m3.group(1)), col))
            continue
    pc_list_sorted = [col for idx, col in sorted(pc_list, key=lambda x: x[0])]
    return pc_list_sorted

# ---------------- Main ----------------

# Try to load existing PCA outputs; otherwise build
if SCORES_PATH.exists() and ROTATION_PATH.exists() and EXPLAINED_CSV.exists():
    df_scores = pd.read_csv(SCORES_PATH)
    df_rotation = pd.read_csv(ROTATION_PATH, index_col=0)
    explained_df = pd.read_csv(EXPLAINED_CSV)
    pct_explained = explained_df["percent_explained"].values
    pc_cols_all = detect_pc_columns(df_scores.columns)
    if not pc_cols_all:
        # fallback to columns matching PC\d+
        fallback = [c for c in df_scores.columns if re.fullmatch(r'pc\d+', str(c).strip().lower())]
        pc_cols_all = sorted(fallback, key=lambda c: int(re.search(r'(\d+)', c).group(1))) if fallback else []
else:
    # Build PCA from source matrix
    if not MATRIX_SOURCE.exists():
        raise FileNotFoundError(
            f"PCA scores not found in {RESULTS_DIR} and matrix source not found: {MATRIX_SOURCE}"
        )

    df_mat = pd.read_csv(MATRIX_SOURCE, keep_default_na=True)

    # Detect identifier columns
    location_col = resolve_col_in_df(df_mat, ["location", "location id", "location_id"], required=False)
    cat_col = resolve_col_in_df(df_mat, ["cat", "category"], required=False)

    numeric_cols = detect_numeric_features(df_mat, exclude_cols=[location_col, cat_col])
    if not numeric_cols:
        raise ValueError(f"No numeric features detected in matrix source: {MATRIX_SOURCE}")

    # Build PCA and save outputs
    df_scores, df_rotation, pct_explained = build_and_save_pca(df_mat, MATRIX_SOURCE, numeric_cols, location_col, cat_col)
    pc_cols_all = [f"PC{i}" for i in range(1, len(pct_explained) + 1)]

# Print percent explained for first 3 PCs
print("Percent variance explained (first 3 PCs):")
for i in range(min(3, len(pct_explained))):
    print(f"  PC{i+1}: {pct_explained[i]:.2f}%")

# Save explained variance bar plot (PNG)
plt.figure(figsize=(10, 5))
pc_labels = [f"PC{i+1}" for i in range(len(pct_explained))]
sns.barplot(x=pc_labels, y=pct_explained, color="C0")
plt.xticks(rotation=45)
plt.ylabel("% Variance Explained")
plt.xlabel("Principal Component")
plt.title("PCA: Percent Variance Explained by PC")
for i, v in enumerate(pct_explained):
    plt.text(i, v + 0.3, f"{v:.2f}%", ha="center", va="bottom", fontsize=9)
plt.tight_layout()
plt.savefig(EXPLAINED_PNG, dpi=300, bbox_inches="tight")
plt.close()
print(f"✅ Explained-variance figure saved: {EXPLAINED_PNG}")

# Prepare scatter data (use df_scores variable from build or load)
if 'df_scores' not in locals():
    df_scores = pd.read_csv(SCORES_PATH)

# Resolve identifiers and PC1/PC2 names in df_scores
location_col = resolve_col_in_df(df_scores, ["location", "location id", "location_id", "site"], required=True)
cat_col = resolve_col_in_df(df_scores, ["cat", "category"], required=True)

pc_cols_detected = detect_pc_columns(df_scores.columns)
if not pc_cols_detected:
    pc_cols_detected = [c for c in df_scores.columns if re.search(r'pc\d+', str(c).strip().lower())]
if not pc_cols_detected:
    raise ValueError("No PC columns detected in scores dataframe.")

pc1_col = pc_cols_detected[0]
pc2_col = pc_cols_detected[1] if len(pc_cols_detected) > 1 else pc_cols_detected[0]

plot_df = df_scores[[location_col, cat_col, pc1_col, pc2_col]].copy().dropna(subset=[pc1_col, pc2_col])
plot_df[pc1_col] = pd.to_numeric(plot_df[pc1_col], errors="coerce")
plot_df[pc2_col] = pd.to_numeric(plot_df[pc2_col], errors="coerce")

# Anthropogenic mask (case-insensitive)
anthro_mask = plot_df[cat_col].astype(str).str.strip().str.lower().eq("anthropogenic")

# Convex hull
def convex_hull_indices(xy: np.ndarray):
    uniq_pts = np.unique(xy, axis=0)
    if len(uniq_pts) < 3:
        return np.array([], dtype=int)
    order = np.argsort(uniq_pts[:, 0], kind="mergesort")
    pts = uniq_pts[order]
    idxs = np.arange(len(uniq_pts))[order]
    def cross(o, a, b):
        return (a[0]-o[0])*(b[1]-o[1]) - (a[1]-o[1])*(b[0]-o[0])
    lower, lower_idx = [], []
    for i, p in enumerate(pts):
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop(); lower_idx.pop()
        lower.append(p); lower_idx.append(idxs[i])
    upper, upper_idx = [], []
    for i, p in enumerate(pts[::-1]):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop(); upper_idx.pop()
        upper.append(p); upper_idx.append(idxs[len(pts)-1-i])
    hull_unique_idx = np.array(lower_idx[:-1] + upper_idx[:-1], dtype=int)
    hull_points = uniq_pts[hull_unique_idx]
    original_indices = []
    for hp in hull_points:
        matches = np.where((xy == hp).all(axis=1))[0]
        original_indices.append(matches[0])
    return np.array(original_indices, dtype=int)

coords = plot_df[[pc1_col, pc2_col]].to_numpy()
try:
    from scipy.spatial import ConvexHull
    if coords.shape[0] >= 3 and np.unique(coords, axis=0).shape[0] >= 3:
        hull = ConvexHull(coords)
        hull_idx = hull.vertices
    else:
        hull_idx = np.array([], dtype=int)
except Exception:
    hull_idx = convex_hull_indices(coords)

hull_mask = np.zeros(len(plot_df), dtype=bool)
if hull_idx.size > 0:
    hull_mask[hull_idx] = True

# Scatter with labels
plt.figure(figsize=(10.5, 8.5))
ax = sns.scatterplot(
    data=plot_df,
    x=pc1_col, y=pc2_col,
    hue=cat_col, palette="tab10",
    s=70, edgecolor="k", linewidth=0.6, alpha=0.95
)

def outline(text_obj, lw=3):
    text_obj.set_path_effects([mpe.Stroke(linewidth=lw, foreground="white"), mpe.Normal()])

texts = []
for i in np.where(hull_mask)[0]:
    row = plot_df.iloc[i]
    t = ax.text(row[pc1_col] + 0.01, row[pc2_col] + 0.01, f"{row[location_col]}\n{row[cat_col]}", fontsize=9.5, weight="bold", zorder=6)
    outline(t, lw=3)
    texts.append(t)

for i in np.where(anthro_mask)[0]:
    if hull_mask[i]:
        continue
    row = plot_df.iloc[i]
    t = ax.text(row[pc1_col] + 0.01, row[pc2_col] - 0.01, f"{row[location_col]}", fontsize=9, weight="bold", zorder=6)
    outline(t, lw=3)
    texts.append(t)

if HAVE_ADJUSTTEXT and texts:
    adjust_text(
        texts,
        x=plot_df[pc1_col].values, y=plot_df[pc2_col].values,
        expand_points=(1.2, 1.2),
        force_points=(0.3, 0.3),
        force_text=(0.4, 0.4),
        only_move={"points": "none", "text": "xy"},
        autoalign="xy",
        lim=200,
        arrowprops=None
    )
else:
    for j, t in enumerate(texts):
        dx = (j % 5) * 0.01
        dy = ((j // 5) % 5) * 0.01
        t.set_position((t.get_position()[0] + dx, t.get_position()[1] + dy))

leg = ax.legend(title="Cat", loc="lower right", frameon=True, framealpha=0.9)
if leg:
    leg.set_zorder(1)

ax.margins(x=0.08, y=0.08)
plt.title("PCA: PC1 vs PC2 (Hull: Location+Cat; Anthropogenic: Location)")
plt.xlabel(pc1_col); plt.ylabel(pc2_col)
plt.tight_layout()
plt.savefig(SCATTER_PNG, dpi=240, bbox_inches="tight")
plt.close()

# Save hull vertices table
hull_table = plot_df.iloc[hull_idx][[location_col, cat_col, pc1_col, pc2_col]].copy() if hull_idx.size > 0 else pd.DataFrame(columns=[location_col, cat_col, pc1_col, pc2_col])
hull_table.to_csv(HULL_CSV, index=False)

print(f"✅ PCA scores/rotation/explained are in: {RESULTS_DIR}")
print(f"✅ Scatter saved: {SCATTER_PNG}")
print(f"✅ Explained-variance saved: {EXPLAINED_PNG}")
print(f"✅ Convex hull vertices saved: {HULL_CSV} (n={len(hull_table)})")

Percent variance explained (first 3 PCs):
  PC1: 36.25%
  PC2: 16.28%
  PC3: 8.60%
✅ Explained-variance figure saved: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_explained_variance.png
✅ PCA scores/rotation/explained are in: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1
✅ Scatter saved: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_pc1_pc2_scatter_labeled_deoverlap.png
✅ Explained-variance saved: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_explained_variance.png
✅ Convex hull vertices saved: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_convex_hull_vertices.csv (n=10)

In [2]:
#!/usr/bin/env python3
r"""
Interactive 3D PCA scatter with selected labels and 3D convex-hull export.

Behavior:
 - Finds pca_scores.csv (preferring results_3.1 under V 2.1 items).
 - Ensures PC1/PC2/PC3 numeric columns (fills PC3 with zeros if missing).
 - Computes the convex hull in 3-space (PC1,PC2,PC3) and writes hull vertices to CSV.
 - Labels (projected) on the 3D scatter:
     * all 3D hull vertices (Location + Cat),
     * all rows with Cat == "Anthropogenic" (Location),
     * explicit locations: ["CrPZ-3", "R-44 S1", "R-45 S1", "R-42"] (case-insensitive, non-alphanumeric ignored)
 - Removes legend entries whose label includes the string "Aa" (font-sample items).
 - Writes interactive HTML only (no PNG snapshot).
 - Writes pca_3d_hull_vertices.csv with the 3D hull vertices.

Requirements:
    pip install pandas scipy plotly

Notes:
 - PNG snapshot (kaleido) has been removed per request so no kaleido dependency or PNG write occurs.
"""

from pathlib import Path
import re
import sys
import gc
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

# ---------- Robust path resolution (prefer results_3.1 root) ----------
DEFAULT_ROOT = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items")
PREFERRED_SUBDIR = "results_3.1"

def find_pca_scores(root: Path = DEFAULT_ROOT, preferred_subdir: str = PREFERRED_SUBDIR):
    cand = root / preferred_subdir / "pca_scores.csv"
    if cand.exists():
        return cand
    cand2 = root / preferred_subdir / "PCA_Step1" / "pca_scores.csv"
    if cand2.exists():
        return cand2
    cand3 = root / "PCA_Step1" / "pca_scores.csv"
    if cand3.exists():
        return cand3
    found = list(root.rglob("pca_scores.csv"))
    if not found:
        cwd_found = list(Path.cwd().rglob("pca_scores.csv"))
        if cwd_found:
            found = cwd_found
    if not found:
        raise FileNotFoundError(f"No pca_scores.csv found under {root} or cwd {Path.cwd()}.")
    for f in found:
        if preferred_subdir.lower() in str(f).lower():
            return f
    # fallback to first found (and print list for debugging)
    print("Multiple/alternate pca_scores.csv candidates found; using the first one. Full list:")
    for f in found:
        print(" -", f)
    return found[0]

SCORES_PATH = find_pca_scores()
BASE_DIR = SCORES_PATH.parent   # directory containing pca_scores.csv (PCA_v2 root or results_3.1)
OUT_DIR = BASE_DIR
OUT_HTML = OUT_DIR / "pca_3d_interactive.html"
HULL_CSV_3D = OUT_DIR / "pca_3d_hull_vertices.csv"

print(f"Using PCA scores at: {SCORES_PATH}")
print(f"Outputs will be written to: {OUT_DIR}")

# ---- Load data ----
df = pd.read_csv(SCORES_PATH)

# Resolve columns (case-insensitive helpers)
def resolve_col(df, candidates):
    low_map = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        key = cand.lower().strip()
        if key in low_map:
            return low_map[key]
    raise KeyError(f"Could not resolve any of {candidates} in columns: {list(df.columns)[:20]}")

location_col = resolve_col(df, ["location", "location id", "location_id"])
cat_col = resolve_col(df, ["cat", "category"])
pc1_col = resolve_col(df, ["pc1", "PC1", "PC 1", "pc 1"])
pc2_col = resolve_col(df, ["pc2", "PC2", "PC 2", "pc 2"])
# PC3 optional: if missing, create PC3 filled with zeros so we can still view in 3D
try:
    pc3_col = resolve_col(df, ["pc3", "PC3", "PC 3", "pc 3"])
    has_pc3 = True
except KeyError:
    df["PC3"] = 0.0
    pc3_col = "PC3"
    has_pc3 = False
    print("PC3 not found; using zeros for PC3 for a flat 3D view.")

# coerce numeric
for c in [pc1_col, pc2_col, pc3_col]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# drop rows missing PC1/PC2 (PC3 can be NaN only if we created it)
df_clean = df.dropna(subset=[pc1_col, pc2_col]).copy()
if df_clean.empty:
    raise ValueError("No valid PC1/PC2 data found after coercion to numeric.")

# Normalized keys for matching explicit labels and R-42:
def norm_key(s: str):
    # remove non-alphanumeric, lower-case
    return re.sub(r'[^a-z0-9]', '', str(s or "").lower())

df_clean["_loc_norm_alnum"] = df_clean[location_col].astype(str).map(norm_key)

# Prepare coords for 3D hull (PC1, PC2, PC3)
coords3 = df_clean[[pc1_col, pc2_col, pc3_col]].to_numpy()

# Compute 3D convex hull vertices (indices into coords3 array) and map to original df_clean indices
hull3_idx_local = np.array([], dtype=int)
have_scipy = False
try:
    from scipy.spatial import ConvexHull
    have_scipy = True
except Exception:
    have_scipy = False

if coords3.shape[0] >= 4 and np.unique(coords3, axis=0).shape[0] >= 4 and have_scipy:
    try:
        hull3 = ConvexHull(coords3)
        hull3_idx_local = np.array(hull3.vertices, dtype=int)
    except Exception as e:
        print("scipy ConvexHull failed:", e)
        hull3_idx_local = np.array([], dtype=int)
else:
    # not enough unique points or scipy missing -> no 3D hull
    hull3_idx_local = np.array([], dtype=int)

# Map local indices to the df_clean global indices
if hull3_idx_local.size > 0:
    df_clean_local_index_array = df_clean.index.to_numpy()
    hull3_idx_global = df_clean_local_index_array[hull3_idx_local]
else:
    hull3_idx_global = np.array([], dtype=int)

# Write 3D hull vertices CSV
if hull3_idx_global.size > 0:
    hull3_table = df_clean.loc[hull3_idx_global, [location_col, cat_col, pc1_col, pc2_col, pc3_col]].copy()
else:
    hull3_table = pd.DataFrame(columns=[location_col, cat_col, pc1_col, pc2_col, pc3_col])
hull3_table.to_csv(HULL_CSV_3D, index=False)
print(f"3D convex hull vertices written to: {HULL_CSV_3D} (n={len(hull3_table)})")

# Build base 3D scatter with Plotly Express for categorical coloring
fig_base = px.scatter_3d(
    df_clean,
    x=pc1_col, y=pc2_col, z=pc3_col,
    color=cat_col,
    hover_name=location_col,
    opacity=0.9,
    title="PCA 3D: PC1 vs PC2 vs PC3"
)
fig = go.Figure(fig_base)

# Add 3D hull vertex labels (Location + Cat) projected into 3D points
if hull3_idx_local.size > 0:
    hull3_df = df_clean.iloc[hull3_idx_local].copy().reset_index(drop=True)
    hull3_text = hull3_df[location_col].astype(str) + "<br>" + hull3_df[cat_col].astype(str)
    fig.add_trace(
        go.Scatter3d(
            x=hull3_df[pc1_col],
            y=hull3_df[pc2_col],
            z=hull3_df[pc3_col],
            mode="text",
            text=hull3_text,
            textposition="top center",
            textfont=dict(size=11, color="black", family="Arial"),
            hoverinfo="text",
            name="Hull vertices (3D)",
            showlegend=False,   # labels speak for themselves
            marker=dict(size=1),
            opacity=1.0,
        )
    )

# Add anthropogenic labels (Location), skipping ones already labeled as hull
anthro_mask_local = df_clean[cat_col].astype(str).str.strip().str.lower() == "anthropogenic"
if anthro_mask_local.any():
    # exclude hull-local positions
    anthro_df = df_clean[anthro_mask_local].copy()
    if hull3_idx_local.size > 0:
        anthro_df = anthro_df.loc[~anthro_df.index.isin(hull3_idx_global)]
    if not anthro_df.empty:
        fig.add_trace(
            go.Scatter3d(
                x=anthro_df[pc1_col],
                y=anthro_df[pc2_col],
                z=anthro_df[pc3_col],
                mode="text",
                text=anthro_df[location_col].astype(str),
                textposition="middle right",
                textfont=dict(size=10, color="black", family="Arial"),
                hoverinfo="text",
                name="Anthropogenic (Location)",
                showlegend=False,  # labels speak for themselves
                marker=dict(size=1),
                opacity=1.0,
            )
        )

# Explicit labels requested by user (include R-42 as well)
EXTRA_LABELS = ["CrPZ-3", "R-44 S1", "R-45 S1", "R-42"]
# create normalized set
norm_targets = {norm_key(t): t for t in EXTRA_LABELS}
found_local_idx = []
for idx_local, loc_norm in enumerate(df_clean["_loc_norm_alnum"].values):
    if loc_norm in norm_targets:
        found_local_idx.append(idx_local)

if found_local_idx:
    extra_df = df_clean.iloc[found_local_idx].copy().reset_index(drop=True)
    extra_text = extra_df[location_col].astype(str)
    fig.add_trace(
        go.Scatter3d(
            x=extra_df[pc1_col],
            y=extra_df[pc2_col],
            z=extra_df[pc3_col],
            mode="text",
            text=extra_text,
            textposition="bottom center",
            textfont=dict(size=12, color="black", family="Arial"),
            hoverinfo="text",
            name="Explicit labels",
            showlegend=False,
            marker=dict(size=1),
            opacity=1.0,
        )
    )
    print(f"Added explicit labels for: {', '.join(extra_df[location_col].astype(str).tolist())}")
else:
    print("No explicit label matches found for the requested list. Check exact Location names in pca_scores.csv.")

# Make sure R-42 is included: if no explicit match above, try a substring search in normalized keys
if not any(norm_key(t) in df_clean["_loc_norm_alnum"].values for t in ["r42"]):
    # search by substring match on raw location strings
    r42_mask = df_clean[location_col].astype(str).str.replace(r'\s+', '', regex=True).str.upper().str.contains("R42")
    if r42_mask.any():
        r42_df = df_clean.loc[r42_mask].copy().reset_index(drop=True)
        # add labels for these if not already included
        fig.add_trace(
            go.Scatter3d(
                x=r42_df[pc1_col],
                y=r42_df[pc2_col],
                z=r42_df[pc3_col],
                mode="text",
                text=r42_df[location_col].astype(str),
                textposition="middle left",
                textfont=dict(size=12, color="black", family="Arial"),
                hoverinfo="text",
                name="R-42 (match)",
                showlegend=False,
                marker=dict(size=1),
                opacity=1.0,
            )
        )
        print(f"Added R-42 labels for: {', '.join(r42_df[location_col].astype(str).tolist())}")

# Legend cleanup: hide traces whose legend label contains "Aa" (font-sample artifacts).
# Also hide any internal annotation traces we explicitly set showlegend=False for already.
for tr in fig.data:
    try:
        if tr.name and "Aa" in str(tr.name):
            tr.showlegend = False
    except Exception:
        pass

# Layout tweaks: move legend outside and centered vertically; keep traceorder normal
fig.update_layout(
    legend=dict(
        title="Cat",
        x=1.02,
        y=0.5,
        xanchor="left",
        yanchor="middle",
        bgcolor="rgba(255,255,255,0.9)",
        bordercolor="rgba(200,200,200,0.6)",
        borderwidth=0.6,
        traceorder="normal",
    ),
    margin=dict(l=60, r=240, t=80, b=60),
    scene=dict(
        xaxis_title=pc1_col,
        yaxis_title=pc2_col,
        zaxis_title=pc3_col,
    ),
    title=dict(x=0.5),
)

# Save interactive HTML (the single desired output)
fig.write_html(str(OUT_HTML), include_plotlyjs="cdn")
print(f"Wrote interactive 3D HTML to: {OUT_HTML}")

# Save 3D hull vertices CSV already done above; report
total_points = len(df_clean)
anthro_count = int(anthro_mask_local.sum())
hull3_count = len(hull3_table)

print("\nSummary:")
print(f" - total points plotted: {total_points}")
print(f" - anthropogenic labeled points: {anthro_count}")
print(f" - 3D convex hull vertices saved: {hull3_count}")
if not has_pc3:
    print(" - NOTE: PC3 was not present in input; plotted PC3 as zeros (flat).")

# Notebook-star explanation
print("\nNote: If you see a running-star [*] next to the notebook cell, it means the kernel is still busy.")
print("If the script finished producing files but the cell still shows a star, interrupt the cell/kernel.")
print("A continuously busy kernel can block subsequent calculations; stop/interrupt it if it doesn't finish.")

# ---------------- Safe cleanup and graceful exit ----------------
# Close/cleanup large objects and exit so notebook cells finish without lingering busy state.
try:
    # Delete large objects we created
    for name in (
        "fig", "fig_base", "hull3", "hull3_df", "hull3_table", "hull3_idx_local",
        "hull3_idx_global", "coords3", "df_clean", "df", "df_clean_local_index_array",
        "r42_df", "extra_df", "anthro_df",
    ):
        if name in globals():
            try:
                del globals()[name]
            except Exception:
                pass

    # Close matplotlib if any (defensive)
    try:
        import matplotlib.pyplot as _plt
        _plt.close("all")
    except Exception:
        pass

    gc.collect()
except Exception:
    pass

# Exit the script cleanly. In a notebook this will end the cell execution.
try:
    sys.exit(0)
except SystemExit:
    # ensure termination if running as a script
    raise

Using PCA scores at: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_scores.csv
Outputs will be written to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1
3D convex hull vertices written to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_3d_hull_vertices.csv (n=18)
Added explicit labels for: CRPZ-3, R-42, R-44 S1, R-45 S1
Wrote interactive 3D HTML to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_3d_interactive.html

Summary:
 - total points plotted: 85
 - anthropogenic labeled points: 7
 - 3D convex hull vertices saved: 18

Note: If you see a running-star [*] next to the notebook cell, it means the kernel is still busy.
If the script finished producing files but the cell still shows a star, interrupt the cell/kernel.
A continuously busy kernel can block subsequent calculations; stop/interrupt it if it doesn't finish.

SystemExit: 0

C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.

In [4]:
#!/usr/bin/env python3
"""
Fast plotting of PCA loadings for all variables (max -> min for each PC),
with consistent colors per parameter across panels, variable names shown
on every vertical axis, and no legend.

This script will:
 - Look for pca_loadings.csv in <DEFAULT_ROOT>/results_3.1/.
 - If not found, try to load an existing pca_rotation.csv and write it to pca_loadings.csv.
 - If neither exists, build PCA from the numeric matrix (AllWells_V3_nInt.csv),
   save loadings to pca_loadings.csv (and also pca_rotation.csv, pca_scores.csv, pca_explained_variance.csv)
   in results_3.1, then continue to plotting.
 - Produce:
   - pca_loadings_all_pcs_labeled_big.png
   - pca_loadings_all_pcs_labeled_big.pdf
   - pca_loadings_all_ordered.csv
"""

from pathlib import Path
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import gc
import sys

# PCA building dependencies
try:
    from sklearn.decomposition import PCA
    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import StandardScaler
except Exception as e:
    raise ImportError("scikit-learn is required to build loadings. Install with `pip install scikit-learn`.") from e

# ---- Configuration ----
DEFAULT_ROOT = Path(r"C:/Users/kylian.robinson/MapRebuildItems/V 2.1 items")
PCA_DIR = DEFAULT_ROOT / "results_3.1"
PCA_DIR.mkdir(parents=True, exist_ok=True)

LOADINGS_FILE = PCA_DIR / "pca_loadings.csv"
ROTATION_FILE = PCA_DIR / "pca_rotation.csv"   # alternate name used elsewhere
SCORES_FILE = PCA_DIR / "pca_scores.csv"
EXPLAINED_FILE = PCA_DIR / "pca_explained_variance.csv"

OUT_DIR = PCA_DIR
OUT_PNG = OUT_DIR / "pca_loadings_all_pcs_labeled_big.png"
OUT_PDF = OUT_DIR / "pca_loadings_all_pcs_labeled_big.pdf"
OUT_CSV = OUT_DIR / "pca_loadings_all_ordered.csv"

PC_NAMES_PREFERRED = ["PC1", "PC2", "PC3"]   # case-insensitive resolve

# Increased size and resolution for screenshot / document use
FIGSIZE = (30, 14)   # very wide
DPI = 300            # high resolution for crisp screenshots
FONT_SIZE = 11       # slightly larger font for readability in documents

# Source matrix if we need to build PCA
MATRIX_SOURCE = DEFAULT_ROOT / "AllWells_V3_nInt.csv"

# ---- Helpers ----
def detect_numeric_features(df, exclude_cols):
    id_like = set(exclude_cols) - {None}
    candidate_cols = [c for c in df.columns if c not in id_like]
    numeric_cols = []
    for c in candidate_cols:
        s_num = pd.to_numeric(df[c], errors="coerce")
        frac_numeric = s_num.notna().mean() if len(s_num) else 0.0
        if frac_numeric >= 0.7 or pd.api.types.is_numeric_dtype(df[c]):
            numeric_cols.append(c)
    return numeric_cols

def resolve_pc_names_from_df(df, preferred_list):
    cols_lower = {c.lower().strip(): c for c in df.columns}
    def resolve(name):
        key = name.lower().strip()
        if key in cols_lower:
            return cols_lower[key]
        for c in cols_lower:
            if c.replace(" ", "").replace("_", "") == key.replace(" ", "").replace("_", ""):
                return cols_lower[c]
        return None
    resolved = [resolve(p) for p in preferred_list]
    return resolved

# ---- Ensure loadings exist (or build them) ----
t0 = time.time()

if not LOADINGS_FILE.exists():
    # Try to recover from alternate rotation file
    if ROTATION_FILE.exists():
        rot_df = pd.read_csv(ROTATION_FILE, index_col=0)
        rot_df.to_csv(LOADINGS_FILE)
        print(f"Recovered loadings from {ROTATION_FILE} -> wrote {LOADINGS_FILE}.")
    else:
        # Need to build PCA from matrix source
        if not MATRIX_SOURCE.exists():
            raise FileNotFoundError(
                f"No loadings found ({LOADINGS_FILE}) and no rotation file ({ROTATION_FILE}).\n"
                f"Also matrix source not found: {MATRIX_SOURCE}\n"
                "Place pca_loadings.csv or pca_rotation.csv in results_3.1, or provide the matrix file."
            )

        print(f"No loadings present. Building PCA from matrix source: {MATRIX_SOURCE}")
        df_mat = pd.read_csv(MATRIX_SOURCE, keep_default_na=True)

        # identify id columns (optional)
        lower_map = {c.lower().strip(): c for c in df_mat.columns}
        def resolve_col(options):
            for o in options:
                key = o.lower().strip()
                if key in lower_map:
                    return lower_map[key]
            return None

        location_col = resolve_col(["location", "location id", "location_id"])
        cat_col = resolve_col(["cat", "category"])

        numeric_cols = detect_numeric_features(df_mat, exclude_cols=[location_col, cat_col])
        if not numeric_cols:
            raise ValueError("No numeric features detected in matrix source to build PCA.")

        # Prepare numeric matrix
        X_num = df_mat[numeric_cols].apply(pd.to_numeric, errors="coerce").values

        # Impute and scale
        imputer = SimpleImputer(strategy="mean")
        X_imputed = imputer.fit_transform(X_num)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X_imputed)

        # PCA
        n_components = min(X_scaled.shape[0], X_scaled.shape[1])
        pca = PCA(n_components=n_components)
        scores = pca.fit_transform(X_scaled)

        # Loadings: features x PCs (components_.T)
        pc_cols = [f"PC{i}" for i in range(1, scores.shape[1] + 1)]
        loadings = pd.DataFrame(pca.components_.T, index=numeric_cols, columns=pc_cols)

        # Save loadings (pca_loadings.csv) and also save rotation alias and scores/explained for completeness
        loadings.to_csv(LOADINGS_FILE)
        loadings.to_csv(ROTATION_FILE)  # alias for other scripts
        scores_df = pd.DataFrame(scores, columns=pc_cols, index=df_mat.index)
        # insert optional location/cat if present
        if location_col:
            scores_df.insert(0, location_col, df_mat[location_col].astype(str).values)
        else:
            scores_df.insert(0, "Location", [""] * len(scores_df))
        if cat_col:
            scores_df.insert(1, cat_col, df_mat[cat_col].astype(str).values)
        else:
            scores_df.insert(1, "Cat", [""] * len(scores_df))
        scores_df.to_csv(SCORES_FILE, index=False)
        explained_df = pd.DataFrame({
            "PC": pc_cols,
            "percent_explained": 100.0 * pca.explained_variance_ratio_
        })
        explained_df.to_csv(EXPLAINED_FILE, index=False)

        print(f"Built PCA and wrote loadings to {LOADINGS_FILE}, rotation alias {ROTATION_FILE}, scores to {SCORES_FILE}, explained to {EXPLAINED_FILE}.")

# ---- Load the loadings file for plotting ----
df = pd.read_csv(LOADINGS_FILE, index_col=0)
if df.empty:
    raise ValueError("pca_loadings.csv appears empty after attempted recovery/build.")

# Resolve PC names (case-insensitive), ensure PC3 exists
resolved = resolve_pc_names_from_df(df, PC_NAMES_PREFERRED)
if resolved[0] is None or resolved[1] is None:
    raise KeyError(f"Could not find PC1/PC2 columns in loadings. Columns found: {list(df.columns)}")
if resolved[2] is None:
    df["PC3"] = 0.0
    resolved[2] = "PC3"

pc1_col, pc2_col, pc3_col = resolved

# Ensure numeric
for c in (pc1_col, pc2_col, pc3_col):
    df[c] = pd.to_numeric(df[c], errors="coerce")

# List of all variables
variables = list(df.index)
n_vars = len(variables)
print(f"Found {n_vars} variables. Will plot all of them (from max to min for each PC).")

# Build consistent color map for variables (deterministic)
cmap = mpl.cm.get_cmap("tab20", max(20, n_vars))
colors = [mpl.colors.rgb2hex(cmap(i % cmap.N)) for i in range(n_vars)]
color_map = {var: colors[i] for i, var in enumerate(sorted(variables))}

# Prepare per-PC sorted series (max -> min)
s_pc1 = df[pc1_col].sort_values(ascending=False)
s_pc2 = df[pc2_col].sort_values(ascending=False)
s_pc3 = df[pc3_col].sort_values(ascending=False)

# Save ordered CSV with rank columns for each PC
ordered_df = pd.DataFrame(index=sorted(variables))
ordered_df[pc1_col] = df.loc[ordered_df.index, pc1_col]
ordered_df[pc2_col] = df.loc[ordered_df.index, pc2_col]
ordered_df[pc3_col] = df.loc[ordered_df.index, pc3_col]
ordered_df[f"{pc1_col}_rank_desc"] = ordered_df[pc1_col].rank(method="dense", ascending=False).astype(int)
ordered_df[f"{pc2_col}_rank_desc"] = ordered_df[pc2_col].rank(method="dense", ascending=False).astype(int)
ordered_df[f"{pc3_col}_rank_desc"] = ordered_df[pc3_col].rank(method="dense", ascending=False).astype(int)
ordered_df.to_csv(OUT_CSV)
print(f"Wrote ordered loadings CSV to: {OUT_CSV}")

# Plotting: three horizontal subplots with variable names on each vertical axis
plt.rcParams.update({"font.size": FONT_SIZE})
fig, axes = plt.subplots(ncols=3, nrows=1, figsize=FIGSIZE, constrained_layout=False)

pc_series = [(pc1_col, s_pc1), (pc2_col, s_pc2), (pc3_col, s_pc3)]
for ax, (pcname, series) in zip(axes, pc_series):
    vars_order = list(series.index)
    y_pos = np.arange(len(vars_order))
    values = series.values
    bar_colors = [color_map[v] for v in vars_order]

    ax.barh(y_pos, values, color=bar_colors, edgecolor="k", linewidth=0.25)
    ax.set_yticks(y_pos)
    # Show y-labels on every subplot for fast reading
    ax.set_yticklabels(vars_order, fontsize=FONT_SIZE - 1)
    ax.invert_yaxis()
    ax.set_xlabel(f"{pcname} loading", fontsize=FONT_SIZE + 1)
    ax.axvline(0, color="0.35", linewidth=0.9)
    ax.grid(axis="x", linestyle="--", linewidth=0.4, alpha=0.6)

    # Annotate numeric values (small but readable)
    vmax = np.nanmax(np.abs(values)) if values.size else 0.0
    offset = 0.005 * max(1.0, vmax)
    for yi, val in enumerate(values):
        ha = "left" if val >= 0 else "right"
        xpos = val + (offset if val >= 0 else -offset)
        ax.text(xpos, yi, f"{val:.3f}", va="center", ha=ha, fontsize=FONT_SIZE - 2, color="black")

# Remove legend entirely (user requested)
plt.subplots_adjust(left=0.06, right=0.98, wspace=0.18, top=0.94, bottom=0.04)
fig.suptitle("PCA loadings: all variables (max -> min per PC). Variable names on every vertical axis.", fontsize=FONT_SIZE + 2)

# Save high-resolution PNG and PDF for screenshots/doc inclusion
t1 = time.time()
fig.savefig(OUT_PNG, dpi=DPI, bbox_inches="tight")
fig.savefig(OUT_PDF, dpi=DPI, bbox_inches="tight")
plt.close(fig)
t2 = time.time()

print(f"Wrote PNG to {OUT_PNG} and PDF to {OUT_PDF} (save time {t2-t1:.2f}s). Total runtime {time.time()-t0:.2f}s.")

# Cleanup
try:
    del df, ordered_df, loadings
except Exception:
    pass
gc.collect()
sys.exit(0)

Recovered loadings from C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_rotation.csv -> wrote C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_loadings.csv.
Found 22 variables. Will plot all of them (from max to min for each PC).
Wrote ordered loadings CSV to: C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_loadings_all_ordered.csv

C:\Users\kylian.robinson\AppData\Local\Temp\ipykernel_10996\3210248554.py:188: MatplotlibDeprecationWarning:

The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.

Wrote PNG to C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_loadings_all_pcs_labeled_big.png and PDF to C:\Users\kylian.robinson\MapRebuildItems\V 2.1 items\results_3.1\pca_loadings_all_pcs_labeled_big.pdf (save time 1.75s). Total runtime 1.85s.

SystemExit: 0

C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.